### ISSUE TITLE
Describe new config options

### ISSUE THREAD

**Issue by rpath** [PromyLOPh/pianobar#297]
There are many new config options which are non-obvious, but have no description:

```
   partner_password = AC7IBG09A3DTSYM4R41UJWL07VLN8JI7

   partner_user = android

   decrypt_password = R=U!LH$O2B#

   device = android-generic

   encrypt_password = 6#26FRL$ZWD
```

**Comment by webbe** [comment]
This basically authenticates the app to use pandora's endpoints. More information: [Unofficial Pandora Documentation](https://6xq.net/pandora-apidoc/json/partners/)
