### ISSUE TITLE
First song plays fine, second song always fails with: "ao_alsa ERROR: Unable to open ALSA device 'default' for playback => Invalid argument"

### ISSUE THREAD

**Issue by jleaders** [PromyLOPh/pianobar#312]
On old toshiba laptop with Arch Linux. No other program seem to have sound problems except for pianobar.
It plays some music. I'm jamming to it. Maybe dancing. All's good. Then next song comes on..... BAM. Silence. Error:

ao_alsa WARNING: Unable to open surround playback.  Trying default device...
ao_alsa ERROR: Unable to open ALSA device 'default' for playback => Invalid argument
/!\ Cannot open audio device

Sometimes it'll last for several songs before dying with this error.

**Comment by Nomarian** [comment]
Same problem on voidlinux
`ao_alsa WARNING: Unable to open surround playback.  Trying default device...
ao_alsa ERROR: Unable to open ALSA device 'default' for playback => Invalid argument
/!\ Cannot open audio device.`


I had it configured with alsa and it didn't work, I changed libao.conf to use oss and it did work, but it took over the audio (same if change libao to driver to pulse) trying to play anything with mpv -v hits me with this error


`[ao/pulse] The stream is suspended. Bailing out.`


However, if I use play or mpg123 it just hangs, if I stop pianobar then everything else starts playing. /etc/asound.conf is configured to use pulseaudio, so I'm not sure what is happening.


[asound.conf](http://tpaste.us/DD4l)
[libao.conf](http://tpaste.us/BjdR)
[alsainfo.txt](https://github.com/PromyLOPh/pianobar/files/4555984/alsainfo.txt)

**Comment by PromyLOPh** [comment]
I’ve got `default_driver=pulse` in my `~/.libao` and it works fine. OSS will take over the audio, but pulse should not.

**Comment by Nomarian** [comment]
Yeah, that fixed it. Was changing ~/.libao.conf so I never actually changed libao. Still, I thought asound.conf would have pushed the stream to pulse. anyway; Fixed. Thanks!
