### ISSUE TITLE
pulseaudio

### ISSUE THREAD

**Issue by ag4ve** [PromyLOPh/pianobar#318]
i'm guessing this is a feature request.

what i'd like to be able to do is listen to pianobar on my bluetooth device and have pulseaudio route calls as well (either pausing or adjusting the volume of the source). it also seems that i need to play with the alsa config if i even want music at all while using my bluetooth device as i get this error:
ALSA lib pcm_dmix.c:1018:(snd_pcm_dmix_open) unable to open slave
/!\ Cannot open audio device
which is fine. but i still don't see another way pianobar on my bluetooth device. maybe there's a way to redirect the audio into raw and then i can pipe it?

**Comment by specious** [comment]
I ran into the same issue after installing pulse audio on arch linux, and the solution also involved removing the line:

`dev=default`

from `/etc/libao.conf`. See: https://bugs.archlinux.org/task/57783
