### ISSUE TITLE
jackd support?

### ISSUE THREAD

**Issue by ghost** [PromyLOPh/pianobar#32]
I am trying to determine if pianobar supports jack?  http://jackaudio.org/  I don't see any mention of it in the README file, but I didn't want to assume without asking.

If it does not have jack support, would it be possible to add it?

Thank you!

Josh

**Comment by FallingSnow** [comment]
https://aur.archlinux.org/packages/libao-jack/

Change `default_driver=alas` in `/etc/libao.conf` to `default_driver=jack`.
