### ISSUE TITLE
(i) Login... Network error: TLS handshake failed.  

### ISSUE THREAD

**Issue by fapestniegd** [PromyLOPh/pianobar#321]
I could not get mp3-hifi to work, so so I used the following (from 
https://github.com/ghuntley/pianobarfly/issues/37) to get a bit rate of 193 kpbs instead of 64kbps, and it stopped working with 
"(i) Login... Network error: TLS handshake failed.  " some time this afternoon. I assumed they changed one of these parameters, but have no idea where to find the new ones.

or if audio_format = mp3-hifi would work that would be better. Any advice on how to get 192kbps again from my PandoraOne subscription would be appreciated.
# audio_format = mp3-hifi

audio_quality = high
rpc_host = internal-tuner.pandora.com
partner_user = pandora one
partner_password = TVCKIBGS9AO9TSYLNNFUML0743LH82D
device = D01
encrypt_password = 2%3WCL*JU$MP]4
decrypt_password = U#IO$RZPAB%VX2
tls_fingerprint = 394067EECB420E3911985C2CC02C12AE89BB09B2

**Comment by PromyLOPh** [comment]
This problem has been fixed long ago, make sure you have the latest
version (some distributions ship old versions).

**Comment by pixster** [comment]
I have 2012.05.06.  If that's not the latest, where do I go to get the latest?
thanks!

**Comment by PromyLOPh** [comment]
Clone this git repository, for instance.

**Comment by pixster** [comment]
Sorry, what is it the location for cloning and how do I clone it and then compile the whole thing?
Be patient, I'm old!

**Comment by PromyLOPh** [comment]
Well, it’s gonna be tough if you never used git and never compiled
software before. So your best bet is to ask your distribution’s pianobar
maintainer to build a new version for you.

**Comment by Eucrates** [comment]
For anyone else still kinda new to linux, there's info on how to get the current TLS fingerprint here: https://gist.github.com/r35krag0th/4173333

But other than that, I'm still having trouble actually figure out where to update the info.  Any more babysteps?  Be patient, I'm new!

**Comment by PromyLOPh** [comment]
See #560 and `man pianobar`.

**Comment by Eucrates** [comment]
Thank you.  I've got it working.  Looks like I might have had a level 6 wetware issue.
