### ISSUE TITLE
Login... Network error: TLS fingerprint mismatch.

### ISSUE THREAD

**Issue by nqzero** [PromyLOPh/pianobar#328]
i'm seeing "Login... Network error: TLS fingerprint mismatch." when i start pianobar. i've read thru several other TLS issues but don't see anyone with quite the same problem

i'm on the master branch
i've updated the TLS fingerprint using the contrib script
i'm using libgnutls26 which is 2.12.14-5ubuntu3.1

here's the current contrib options, but i've also tried with all of the below commented out

audio_quality = high
rpc_host = internal-tuner.pandora.com
partner_user = pandora one
partner_password = TVCKIBGS9AO9TSYLNNFUML0743LH82D
device = D01
encrypt_password = 2%3WCL*JU$MP]4
decrypt_password = U#IO$RZPAB%VX2
tls_fingerprint = 2D0AFDAFA16F4B5C0A43F3CB1D4752F9535507C0

anyone have any idea what i'm doing wrong ?

**Comment by daurnimator** [comment]
This came up again today

**Comment by PromyLOPh** [comment]
See #560.

**Comment by dmurvihill** [comment]
```
The certificate is valid until 2015, so we shouldn’t have to worry about that for the next few years anyway.
```

Lol.

**Comment by Patrick-123** [comment]
Haha, well I can't even get mad since it's not almost the end of 2015. 

But yeah, having the same issue.

**Comment by CaptainKraft** [comment]
> I updated the example config file. The certificate is valid until 2015,
> so we shouldn’t have to worry about that for the next few years anyway.

Well, it looks like it's been a few years :-)
Just got this error today.

**Comment by jasonkuehl** [comment]
Im also having this same issue.

**Comment by jasonkuehl** [comment]
(1:185)$ pianobar 
Welcome to pianobar (2014.06.08)! Press ? for a list of commands.
[?] Email: email@gmail.com
[?] Password: 
(i) Login... Network error: TLS fingerprint mismatch.
