### ISSUE TITLE
Default station config file

### ISSUE THREAD

**Issue by arjungm** [PromyLOPh/pianobar#378]
Can you add a default station name/number to the Config file?

Awesome project fyi, thanks.

**Comment by steveoh** [comment]
I can't make this work. I've tried the station number.

eg: `51`

I've tried this with quotes (single and double) etc.

I've also tried the radio name

eg:  `Phish Radio`

I've tried this with quotes etc and i still am presented with the station list.

What is the format for this option?

**Comment by steveoh** [comment]
well using $ while playing a station produced some more information. Mainly a stationId number. Now to try and find out the quickmix id number.

**Comment by steveoh** [comment]
I found it easiest to get from the pandora website. It would be great if the CLI would output this id somehow.

**Comment by PromyLOPh** [comment]
Unless you modified format_nowplaying_station the station id is
displayed when changing to that station: Station <name> (<id>).

**Comment by steveoh** [comment]
PromyLOPh, I didn't modify that and it didn't show up.

**Comment by PromyLOPh** [comment]
Pianobar either shows a format string you set in the config file or the
default, which includes the station id.
