### ISSUE TITLE
Fast forward song

### ISSUE THREAD

**Issue by philstahlfeld** [PromyLOPh/pianobar#403]
Built from source on Ubuntu and every once in a while the songs will start fast forwarding. The current song will cut out and you hear what sounds like static, but looking at the pianobar output shows that the song is being played at about 10x. Not sure if anyone else is having these problems. I'm using 2013.09.15-dev

**Comment by eliezerlp** [comment]
This also occurred to me using **Release 2013.09.15** on Linux Mint 17.3 Cinnamon 64-bit
(Ubuntu 14.04.1 base). Switching to `pulse` as mentioned in https://github.com/PromyLOPh/pianobar/issues/395#issuecomment-25294874 did the trick!
