### ISSUE TITLE
Next song plays 00:42 dead air over and over again

### ISSUE THREAD

**Issue by theAntiBob** [PromyLOPh/pianobar#413]
Skipping a song (just one press of n) immediately plays 42 secs of silence claiming to be the next track's title and continues playing 42sec silent tracks with playlist titles indefinately (as far as I can tell)
Changing stations will play audio again, but switching back to a station that has had a song skipped resumes playing 42sec blank tracks, at least for some time.
Another client (pithos) is not having this problem, so it must be pianobar.
Even (first) had this issue when starting pianobar right after closing another client (pithos) and selecting the same station I was playing.
Having this issue with pianobar-2012.12.01 and pianobar-2013.09.15
Did not include any flags when compiling

Update:
After a few hours of playing pianobar, this issue resolved itself... I have no idea why, and skipping songs functioned correctly, even skipped three songs in a row without issue

**Comment by fread2281** [comment]
> There are two skip limits: daily (12) and hourly (6). Usually they are enforced by the client software, so the server may behave slightly different.

Feature request: could pianobar display these to avoid accidentally going over (and maybe have a confirmation when the user skips when at skip limit)?

**Comment by PromyLOPh** [comment]
> Feature request: could pianobar display these to avoid accidentally
> going over (and maybe have a confirmation when the user skips when at
> skip limit)?
Sure, that should be possible. I’ll add it to my list, but I’m rather
busy at the moment.

**Comment by seliver** [comment]
Hello! How exactly do you detect the number of skips a user have?

**Comment by PromyLOPh** [comment]
Unless the client keeps track of your skips there is no way to tell how
many you have left per hour/day.

**Comment by seliver** [comment]
Ok then, considering that the client does counts the skips per hour made 
by user, how do you calculate the ones left to skip?

**Comment by PromyLOPh** [comment]
> Ok then, considering that the client does counts the skips per hour made 
> by user, how do you calculate the ones left to skip?
Either auth.partnerLogin or auth.userLogin[1] return the overall number
of skips allowed.

[1] http://6xq.net/playground/pandora-apidoc/json/authentication/

**Comment by seliver** [comment]
So, you must be talking about stationSkipLimit, which in my case almost 
always is 6.
Considering if i skip 6 songs in an hour, when will i be able to skip 
again? An hour after the last skip or after the first one?

**Comment by PromyLOPh** [comment]
> So, you must be talking about stationSkipLimit, which in my case almost 
> always is 6.
Yes. If you add includeDailySkipLimit to the auth.userLogin request
there’s also: dailySkipLimitSubscriber and dailySkipLimitNonSubscriber.

> Considering if i skip 6 songs in an hour, when will i be able to skip 
> again? An hour after the last skip or after the first one?
I don’t know. In case you find out send me a pull request[1].

[1] https://github.com/PromyLOPh/pandora-apidoc

**Comment by seliver** [comment]
Gotcha. Thank you, if i find something new, will make what you say ;)
