### ISSUE TITLE
A temporary loss of network connectivity results in a permanent stall to music playing

### ISSUE THREAD

**Issue by codyps** [PromyLOPh/pianobar#442]
If (for example), my router is reset and it takes ~1 minute for the system to regain access to the internet, the song currently being played stops and never continues playing.

**Comment by dathomsen** [comment]
Did this get added to the master? I'm in an area where I lose connectivity quite often and am seeing this issue.

**Comment by PromyLOPh** [comment]
Yes and no. See commit 436a1d4012553a2f33d0e3a5180b3b5ae0378bdd.
