### ISSUE TITLE
Build fails on Ubuntu 13.10

### ISSUE THREAD

**Issue by rjpcomputing** [PromyLOPh/pianobar#444]
I tried to build pianobar after the update to libav/ffmpeg. I am getting an error and not sure why. Here is the packages I installed before building:
`sudo apt-get install git libavcodec-dev libavformat-dev libavutil-dev libavfilter-dev libgnutls-dev libjson0-dev libgcrypt11-dev`

I get this error:

```
$ make
src/player.c:40:36: fatal error: libavfilter/buffersink.h: No such file or directory
 #include <libavfilter/buffersink.h>
                                    ^
compilation terminated.
    CC  src/player.c
src/player.c:40:36: fatal error: libavfilter/buffersink.h: No such file or directory
 #include <libavfilter/buffersink.h>
                                    ^
compilation terminated.
make: *** [src/player.o] Error 1
```

`libavfilter` directory exists, but there is no header named **buffersink.h**.

I am sure I did something wrong. Do I need to choose a different `LIBAV` in the makefile? Which is best? Any help would be appreciated.

**Comment by 92briank** [comment]
You need to uninstall libavfilter and install Libav from source. You can get the source here https://libav.org/download.html
