### ISSUE TITLE
Feature request: mp3 streaming source?

### ISSUE THREAD

**Issue by pjz** [PromyLOPh/pianobar#467]
Is there a way to have pianobar 'play' via an http mp3 socket ala icecast?  The idea is to put it on a handy network device that I can then point pandora-stupid devices/servers at, with controls via a webUI or something.  If there's a way to do this now, I'd love to hear it!

**Comment by disconn3ct** [comment]
FYI this is pretty easy with `audio_pipe` now. Patiobar sends commands via `fifo`, snapcast listens to `audio_pipe`, and it works fine under docker/k8s with no audio hardware.
(That said, it isn't perfect. Both ices and ezstream did not work for me. And the app acts weird if the audio fifo isn't being drained or if stdin/stdout backs up.)
