### ISSUE TITLE
Input/output error

### ISSUE THREAD

**Issue by o-ze** [PromyLOPh/pianobar#478]
after I load pianobar with my email and pass from the config, I can view my stations but whenever I chose one of them I get this:
(i) Receiving new playlist... Ok.
|> Track name and artist
/!\ Unable to open audio file (Input/output error)

**Comment by nicolas-g** [comment]
Hi,

I'm having the same problem on my MacBook Pro (OSX Yosemite 10.10.2), have installe ffmpeg and pianobar using brew install : 

```
   ffmpeg: stable 2.4.2 (bottled), HEAD
   pianobar: stable 2014.09.28, HEAD
```

Sometimes it works just fine while other times I keep getting the errors bellow 
```
|>  "Memories" by "David Guetta" on "One Love (Explicit)"
/!\ Unable to open audio file (Input/output error)
|>  "Beautiful People" by "Chris Brown" on "F.A.M.E. (Explicit)"
/!\ Unable to open audio file (Input/output error)
(i) Receiving new playlist... Ok.
|>  "On Fire" by "Modjo" on "Modjo"
/!\ Unable to open audio file (Input/output error)
|>  "Tomorrow Can Wait (Tocadisco Evil Mix)" by "David Guetta & Chris Willis" on "Tomorrow Can Wait"
/!\ Unable to open audio file (Input/output error)
|>  "Karate" by "Kennedy" on "Special K"
/!\ Unable to open audio file (Input/output error)
```

**Comment by PromyLOPh** [comment]
@nicolas-g: Can you apply the patch I posted above please? It should
make ffmpeg’s error messages more verbose.

**Comment by gdudek** [comment]
I was seeing the same thing intermittently from player.c on the call to avformat_open_input.  I needed to manually edit src/config.h to define HAVE_AV_TIMEOUT and then I increased the timeout in player.c (although the 10 second value might have been sufficient to help I increased it to a whopping 20 seconds).  I believe this is due to a slow DNS nameserver although my instance is also running on a slow embedded system.

This fully resolved the problem for me.

**Comment by PromyLOPh** [comment]
@gdudek: Can you tell me whether you used ffmpeg or libav and which
version it was exactly?

**Comment by gdudek** [comment]
I didn't install ffmpeg and did install libav, and so I assume I am using libav as a result.  pianobar (2014.09.28-dev)

libavutil  54.3.0
libavcodec 56

libavfilter/version.h
has
    LIBAVFILTER_VERSION_MAJOR  5
    LIBAVFILTER_VERSION_MINOR  0
    LIBAVFILTER_VERSION_MICRO  0

By the way: thanks for this!!

**Comment by PromyLOPh** [comment]
> libavformat 54.20.4
> libavutil  54.3.0
> libavcodec 56
Well, avformat seems to be from 9.16, avutil is from 11.3 and avcodec
from 10 or 11. What a mess…

Does the problem still occur if you just increase the timeout in
src/player.c:130 without modifying src/config.h?

The thing about HAVE_AV_TIMEOUT is that libav’s timeout applies to
connect() only and pianobar will get stuck if your network goes down or
you pause for too long. Thus we need that intCb().

**Comment by gdudek** [comment]
I tried doubling the time (from 10 to 20) in intCb, and that seems to have done the trick and it's working OK.

I also tried moving the increased timeout outside the ifdef block in player.c (without really understanding that bit of the code) and was back to seeing the error.

( BTW I did some ugly messing around to allow pianobar to be controlled via a web interface and I'll fork and apply those changes and you can do what you like with them. I need to make an absoluet volume-setting command first. )

Thanks again.

**Comment by PromyLOPh** [comment]
I’m curious: Does it actually take more than 10 seconds from pianobar
printing the song title and artist to the song actually playing?

**Comment by gdudek** [comment]
I just tried and saw an actual delay of about 15 seconds.  (Sorry for the delayed reply. I was on vacation.)
