### ISSUE TITLE
Input buffer exhausted before END element found

### ISSUE THREAD

**Issue by cburmeister** [PromyLOPh/pianobar#479]
Not sure if this is a pianobar specific issue or something up with `ffmpeg`.

```
|>  Station Gabriel Le Mar Radio
(i) Receiving new playlist... Ok.
|>  Ghosts In The Tree by Saafi Brothers on Live On The Roadblog
|>  Sol by Solar Fields on Movements
|>  Thomas Edison Invents The Lazy Dance by Quenum, Lee Van Dowski on As Told On The Eve Of...
|>  Inertia by Spire on Inertia
[aac @ 0x7fa489812200] TYPE_FIL: Input buffer exhausted before END element found
/!\ decode_audio4 (Undefined error: 0)
(i) Receiving new playlist... Ok.
|>  Avisa by Andre Castano on San Francisco Under A Groove, Vol. 1
|>  You Can't Have Your Cake by 2 Block Radius on Om Lounge 8 <3
#   -00:38/07:48
```

**Comment by ZevEisenberg** [comment]
> Afaik Pandora limits your download speed to 50kbps-ish if your account
is flagged (i.e. you get ads with pianobar).

Is there any way to tell if my account is flagged? I pay for Pandora, so I don’t get ads, but I occasionally see this audio skipping issue.

**Comment by PromyLOPh** [comment]
> Is there any way to tell if my account is flagged? I pay for Pandora,
> so I don’t get ads, but I occasionally see this audio skipping issue.
Pandora seems to serve audio files to flagged accounts through different
servers. Their name is usually mediaserver-XXX.pandora.com. You can see
the URL by pressing ‘$’.

**Comment by ZevEisenberg** [comment]
No such luck, at least on the track I'm currently playing. I'll try again if I get this error again. Here's the output of `$`, with the URLs redacted (let me know if the full URLs would be useful, and I can send them privately):

```
album:1:Brand New Frame
artist:	Natalia Zukerman
audioFormat:	1
audioUrl:	http://t3-1.p-cdn.com/access/5872649283875956878.mp4?version=4&lid=[redacted]&token=[redacted]
coverArt:	http://cont-ch1-2.pandora.com/images/public/amz/3/2/9/7/700261237923_500W_458H.jpg
detailUrl:	http://www.pandora.com/natalia-zukerman/brand-new-frame/early-bird?dc=232&ad=0:26:1:02601::0:pandorap1hq:0:1:506:530:MA:25001:2:0:0:0:0:1
fileGain:	-3.370000
musicId:	(null)
rating:	1
stationId:	250615477862786721
title:	Early Bird
trackToken:	[redacted]
```

**Comment by ZevEisenberg** [comment]
Update: I just got the “skips like a CD” glitch on that track after having been paused while I wrote the previous comment.

**Comment by PromyLOPh** [comment]
I suppose you could download the audio file and check whether your
download speed is restricted or not. But I guess we’re in the need of a
buffer…

**Comment by ZevEisenberg** [comment]
@PromyLOPh I just downloaded a 1.8 MB track in 1.053 seconds (`curl` reported an average speed of 1644k/s), so it doesn’t look like I’m being throttled.

**Comment by ZevEisenberg** [comment]
One more thing I've noticed: when I get the skip, the audio seems to be much lower quality for a fraction of a second when it comes back. I could be imagining it, but it seems like maybe it momentarily switched to a lower bitrate stream, and then bounces right back. Is that possible?

**Comment by PromyLOPh** [comment]
Indeed, you’re not throttled. As for your second question: No, pianobar
does not do adaptive streaming, i.e. it does not switch quality
mid-song.

**Comment by PromyLOPh** [comment]
I think we should use #500 to track the status of this buffering issues.
