### ISSUE TITLE
Using pianobar with Proxy after a while play will get ==> [http @ 0x2ec8b80] HTTP error 403 Forbidden

### ISSUE THREAD

**Issue by amazon83** [PromyLOPh/pianobar#496]
Using proxy to listen, every time hit below error after a while, keep asking Pandora reset account... 

|>  Station "Bossanova Radio" (2380944267948327874)
(i) Receiving new playlist... Ok.
|>  "Burnt Sienna And Avocado" by "Emperor Penguin" on "Mysterious Pony"
[http @ 0x2ec8b80] HTTP error 403 Forbidden
/!\ Unable to open audio file (Server returned 403 Forbidden (access denied))
|>  "Borboleta Da Cidade" by "Nu Braz" on "Seriously Good Music: Cocktail"
[http @ 0x2ec8b80] HTTP error 403 Forbidden
/!\ Unable to open audio file (Server returned 403 Forbidden (access denied))
|>  "Thank You MK" by "Tommy Guerrero" on "Soul Food Taqueria"
[http @ 0x2ed7990] HTTP error 403 Forbidden
/!\ Unable to open audio file (Server returned 403 Forbidden (access denied))
|>  "Eve" by "Lorna Lee" on "Rendezvous"
[http @ 0x2ed7990] HTTP error 403 Forbidden
/!\ Unable to open audio file (Server returned 403 Forbidden (access denied))
(i) Receiving new playlist... Ok.
|>  "The Girl From Ipanema" by "Stan Getz & Joao Gilberto" on "Getz/Gilberto"
[http @ 0x2ed6ae0] HTTP error 403 Forbidden
/!\ Unable to open audio file (Server returned 403 Forbidden (access denied))

**Comment by Royh9** [comment]
I Have the same issue using proxy outside the US. worked for a while, but then gives the error no matter what IP i choose.
Any update on this?

**Comment by PromyLOPh** [comment]
> Any update on this?
There won’t be a permanent solution, because it’s a server-side
restriction.
