### ISSUE TITLE
Feature Request: Store login information

### ISSUE THREAD

**Issue by connerpike** [PromyLOPh/pianobar#499]
I wish you would be able to login once, and have pianobar store your information to login upon executing pianobar.

**Comment by cburmeister** [comment]
You can do this using the pianobar configuration file. Please read the man page.

**Comment by steveoh** [comment]
A link to this man page would be awesome.

**Comment by steveoh** [comment]
this should be closed.

**Comment by cburmeister** [comment]
You could also try: `man pianobar`
