### ISSUE TITLE
Support adding "buffering time"

### ISSUE THREAD

**Issue by baskervald** [PromyLOPh/pianobar#500]
Having slower internet, I often find that once a song starts playing it will pause to buffer a lot unless actually paused by the user to give it time to load.

I think it'd be nice if, instead of doing this manually, pianobar could do this automatically with a config option for it. It'd wait until the specified number of seconds had loaded (or if that's complicated, just waiting the specified number of seconds), then start playing. Perhaps it could even start preloading so there's not a pause between songs, but that's not necessary.

**Comment by PromyLOPh** [comment]
I’m not even sure ffmpeg buffers more data than needed to decode the
audio stream. But if someone knows where that switch is we can certainly
expose it to the user.

**Comment by AshlynnInWonderland** [comment]
I just decided to see if I could find anything in the command-line arguments for ffmpeg using `ffmpeg -h full | grep delay` and sure enough!

I'm not sure if a command-line argument is what you needed, but it can be done with

`-preload <int>` where `<int>` is the delay in microseconds

**Comment by PromyLOPh** [comment]
As far as I understand this is used for encoding only.

Anyway, I digged up one of my old feature branches “externalplay” and
polished it. It spawns an external audio player (configureable, mpv for
example) for each file, which worked surprisingly well with older
versions of mpv. As soon as I fix mpv and get the changes accepted
upstream I think I’ll merge this change into master to get rid of all
the playback-related (think of pulseaudio) problems. In the meantime
everyone’s encouraged to try the branch with their favorite cli media
player.

**Comment by AshlynnInWonderland** [comment]
Alright. I'll poke around in that.

What're the problems with mpv you're talking about, though? That actually does happen to be my favorite cli media player, so I'm interested in what problems you've had with using it with pianobar.

**Comment by PromyLOPh** [comment]
I’m passing through all key events not handled by pianobar to the
forked process’ stdin. However mpv ignores them if stdin is not a tty
(line 422 of osdep/terminal-unix.c seems to be the “problem”).

**Comment by haarp** [comment]
Is this still on the table? Sounds like a decent idea.

**Comment by PromyLOPh** [comment]
> Is this still on the table?
I’m not working on it at the moment.
