### ISSUE TITLE
Quickmix is now Shuffle

### ISSUE THREAD

**Issue by aharris88** [PromyLOPh/pianobar#502]
I would like to use the quickmix/shuffle feature in pianobar so that I can select multiple stations for it to shuffle. But when I hit "x" for "select quickmix stations", it says "/!\ Not a QuickMix station."

How can I get this to work.

By the way, I found this post about Pandora renaming quickmix to shuffle. It seems like you used to be able to create a quickmix station as a new station, but now, you just hit shuffle and hit the checkmarks to select the stations that you want.

http://help.pandora.com/customer/portal/articles/85292-shuffle

**Comment by Aurifier** [comment]
For me, this works by playing my QuickMix station. Once it's playing, I can use "x" to toggle my other stations being shuffled in.

**Comment by aharris88** [comment]
Ok, awsome! I just noticed my QuickMix stations. But I actually have 2. Do you know what the difference is?

    58)  QS QuickMix
    59)  Q  QuickMix

**Comment by PromyLOPh** [comment]
The interface is a little clunky because quickmix is an ordinary station
(with an additional property, setting the shuffled stations). Patches
welcome.

**Comment by aharris88** [comment]
What's the difference between the one that says QS and the one that says Q?

**Comment by PromyLOPh** [comment]
> What's the difference between the one that says QS and the one that says Q?
Honestly, I don’t know why there’? two quickmix stations. “S” means the
station is shared, i.e. belongs to another user.
