### ISSUE TITLE
Proxy w/username & password support

### ISSUE THREAD

**Issue by noldog** [PromyLOPh/pianobar#504]
Does pianobar have support for this? I've done quite a bit of searching but no answers.

**Comment by PromyLOPh** [comment]
Yes, basic authorization is supported. Use `proxy =
http://user:password@host:port/`

**Comment by oogiedoogie** [comment]
I've tried the above suggestion, but no luck! My config file contains this line:

proxy = http://username:password@proxy.com/proxy.pac:8888/

where "http://proxy.com/proxy.pac" is the host proxy I use, and 8888 is the port. This host/port combo work in firefox, chrome, etc. But pianobar closes every time I try to run it with the proxy info.

 I've read elsewhere some variations regarding variables named "control_proxy", "http_proxy", and simply "proxy".  Any suggestions on why I can't get Pianobar to connect to my proxy?

**Comment by PromyLOPh** [comment]
> But pianobar closes every time I try to run it with the proxy info.
Any error message?

**Comment by oogiedoogie** [comment]
No error, the window just closes. I'm running in Windows 7. Pianobar was 
working beautifully in the US, but now that I'm outside, the window 
closes as soon as I enter my user name and password.

Thanks,
Douglas

**Comment by PromyLOPh** [comment]
Then you’re running the Windows port? That one’s not maintained here.
Head over to https://github.com/thedmd/pianobar-windows
