### ISSUE TITLE
Add `songpause` as an event

### ISSUE THREAD

**Issue by solidcell** [PromyLOPh/pianobar#505]
I'm not sure if this was intentionally not included, but it would be nice to have this one so that I could display the playing/not-playing state of the player externally.

If you aren't opposed to having this, I could take a crack at a PR.

**Comment by PromyLOPh** [comment]
There seems to be demand for this feature, see #320. Should I change my
mind?

**Comment by solidcell** [comment]
> My job is currently to check whether it's worth "violating" the rule "use eventcmd for xmlrpc only" or not :/

**Comment by solidcell** [comment]
I'd say in response to this:
> My job is currently to check whether it's worth "violating" the rule "use eventcmd for xmlrpc only" or not :/
Yea

However, you bring up a good point with:
> You can't tell which state pianobar is currently in from watching the two new events. You'd have to check all the other events (station change, next song, ...) and "guess" whether that event changed the pause state

In that case I'm inclined to agree.  Too bad :/

It would be great to have things like `songplay`, `songpause`, and `durationremaining`, etc., but it's not worth it in that case.

Thanks though.  I still love `pianobar` as is. :)
