### ISSUE TITLE
Feature Request - Toggle explicit language

### ISSUE THREAD

**Issue by jaduff** [PromyLOPh/pianobar#506]
If possible, it would be great to be able to toggle explicit language for when children are/are not present.

**Comment by PromyLOPh** [comment]
I’ll add it to the [list](https://github.com/PromyLOPh/pianobar/wiki/TODO). We could use user.changeSettings or user.setExplicitContentFilter here.

**Comment by jaduff** [comment]
Awesome! Thanks.
