### ISSUE TITLE
Prompt for password and store authToken

### ISSUE THREAD

**Issue by skeggse** [PromyLOPh/pianobar#507]
Instead of storing my password in plaintext, it would be nice if pianobar prompted me for my password, stored the authToken, and reprompted me for my password if/when the authToken expires.

**Comment by PromyLOPh** [comment]
I’m not sure it’s worth storing the authToken at all. Its lifetime is
very limited, four to six hours I think. Additionally there’s the
`password_command` config option (see manpage).

**Comment by skeggse** [comment]
Ah, ok. How does it work in the mobile app, then? Do they store the password as plaintext? The accepted pattern is to store some sort of authentication token, as that's the more secure route.

**Comment by PromyLOPh** [comment]
You can associate a “deviceId” (any string should work) with your
account that can be used to login afterwards.

**Comment by skeggse** [comment]
So it's like an app-password for Google Auth if you have two-step auth enabled?

**Comment by PromyLOPh** [comment]
Yes, similar. The deviceId replaces both, username and password.
