### ISSUE TITLE
Volume-settings-related pianobar crash

### ISSUE THREAD

**Issue by Aquassaut** [PromyLOPh/pianobar#508]
Hi,

I was turning the volume down in pianobar while it seemed kind of stuck trying to get the new playlist from the server.
After a couple of seconds, it crashed with terminal message:

```
pianobar: src/player.c:88: BarPlayerSetVolume: Assertion `player->fvolume != ((void *)0)' failed.
Aborted (core dumped)
```

Here is a potentially interesting list of versions of stuff I run:

* pianobar -> `2014.09.28`
* ffmpeg -> `2.5.4`,
* libao -> `1.2.0`.
* Arch linux -> `3.18.6-1-ARCH -- most things relatively up to date`

[removed link]

I'd like to also take this opportunity to say thank you for the good work.

Cheers

**Comment by PromyLOPh** [comment]
Indeed, there seems to be a race-condition – BarPlayerSetVolume should
not be called whenever the player is not fully set-up/running yet. I’ll
fix it this weekend.

A word of warning: The coredump you posted a) is useless without the
pianobar binary and b) contains your pandora.com password. If you want
to provide useful debugging information follow the hints on [1] (for
example), redact your account details and send me the output via email.
Thanks :)

[1] https://wiki.ubuntu.com/Backtrace

**Comment by Aquassaut** [comment]
And that is the essence of a true DevOops.

I'll send you all that tomorrow.

**Comment by PromyLOPh** [comment]
Commit 310900e4be52d11388792d776d9f6b89380bbecd should solve this issue.
Thanks for reporting!

**Comment by Aquassaut** [comment]
My pleasure!
