### ISSUE TITLE
Pianobar crashes if 'u' command is issued immediately after changing stations

### ISSUE THREAD

**Issue by 0xacf** [PromyLOPh/pianobar#509]
It appears that the upcoming songs action has a context of (BAR_DC_GLOBAL | BAR_DC_STATION), but its shortcut function asserts that (selSong != NULL). This assertion fails when a station has been selected, but no songs are queued yet. The context for this action could be changed to BAR_DC_SONG, which requires selSong != NULL for the shortcut function to be called.

    -               {'u', BAR_DC_GLOBAL | BAR_DC_STATION, BarUiActPrintUpcoming,
    +               {'u', BAR_DC_SONG, BarUiActPrintUpcoming,

Thanks,
Alan

**Comment by PromyLOPh** [comment]
It does not work this way, because BarUiActHistory filters the available
commands (by setting selSong) based on the context.

Commit 1cd5c5ec77ea43088982a439b58499be87c62087 fixes the issue. Thanks!
