### ISSUE TITLE
Prevent Pianobar from AutoLoading Station

### ISSUE THREAD

**Issue by reidcooper** [PromyLOPh/pianobar#511]
I did not set Pianobar to auto load a station, I was curious on why it was? Its not filled out in my config file.

**Comment by PromyLOPh** [comment]
Either set autostart_station to an invalid value or symlink
~/.config/pianobar/state to /dev/null.

**Comment by reidcooper** [comment]
I did not remember before it having a state file so I renamed it to state-example in case i can revert back to it. The state file had the auto load station listed in it.

**Comment by PromyLOPh** [comment]
It is created by pianobar.
