### ISSUE TITLE
Handshake problems on arm arch

### ISSUE THREAD

**Issue by fhenning09** [PromyLOPh/pianobar#516]
I get a Handshake fail message when logging in so tried from installing from source now I get this via make command: 

http://paste.debian.net/164769/

**Comment by PromyLOPh** [comment]
Looks like ffmpeg/libav is not installed.

**Comment by togakangaroo** [comment]
I also have handshake errors.

Any idea what the issue might be?

![TLS handshake error](http://content.screencast.com/users/togakangaroo/folders/Jing/media/6a462a4e-af42-40a7-be85-10de8267e5e5/2015-06-28_1449.png)

**Comment by PromyLOPh** [comment]
> Any idea what the issue might be?
Yes, that’s a known problem with release 2012.05.06. Please try the
current version.2014.09.28.

**Comment by togakangaroo** [comment]
I'd that not what is in apt get?

**Comment by togakangaroo** [comment]
```
pi@raspberrypi ~ $ sudo apt-cache policy pianobar
pianobar:
  Installed: 2012.05.06-2
  Candidate: 2012.05.06-2
  Version table:
 *** 2012.05.06-2 0
        100 /var/lib/dpkg/status
```

Looks like that is not available? This is for source

```
deb http://mirrordirector.raspbian.org/raspbian/ wheezy main contrib non-free rpi
```

**Comment by PromyLOPh** [comment]
> Looks like that is not available? This is for source
That is correct, Debian wheezy (and thus raspbian too) ships an old
version. You’ll have to build it from source yourself.

**Comment by togakangaroo** [comment]
I see...so that requires ffmpeg which I also have to compile from source which is not realistic on raspberry hardware so I have to somehow figure out how to cross-compile it on another computer.

Is there no easier way to use pianobar on raspberry?

**Comment by PromyLOPh** [comment]
There’s a minimal ffmpeg configuration in the wiki that shouldn’t take too long
to compile – even on the Pi.  https://github.com/PromyLOPh/pianobar/wiki/ffmpeg

I’m not too familiar with Debian, but jessie has a new version, so it may be
possible to just install that (plus dependencies).
