### ISSUE TITLE
Possible to define custom config location

### ISSUE THREAD

**Issue by aeewhite** [PromyLOPh/pianobar#517]
I'm trying to set up a portable installation of pianobar, which makes placing the config file at ~/.config/pianobar difficult. Is it possible to define another location (possibly relative to pianobar's location)?

**Comment by PromyLOPh** [comment]
pianobar respects the environment variable XDG_CONFIG_HOME, which by
default expands to ~/.config/. I guess you could write a shell script
wrapper that runs pianobar with this variable set to a relative path
(`dirname $0`). But the path always ends with /pianobar/config.

**Comment by aeewhite** [comment]
Thanks, that makes sense
