### ISSUE TITLE
Cannot access audio file: Unknown HTTP status code

### ISSUE THREAD

**Issue by filipkristo** [PromyLOPh/pianobar#518]
I get this error after almost every song. Do you now why. I running this on Raspberry pi 2 Model B. 
![capture](https://cloud.githubusercontent.com/assets/8782505/7191450/ede1f49c-e48d-11e4-836f-0b6b7331a302.PNG)

**Comment by PromyLOPh** [comment]
Can you tell me the pianobar version you are running?

**Comment by filipkristo** [comment]
2012.12.01-dev

**Comment by PromyLOPh** [comment]
Please try version 2014.09.28 or the current git master. The issue
should be fixed there.

**Comment by filipkristo** [comment]
I tired install from current repository and i got this error
![capture](https://cloud.githubusercontent.com/assets/8782505/7219951/21bc5d7c-e6b7-11e4-8c06-e507576bbb79.PNG)

**Comment by PromyLOPh** [comment]
pianobar uses libcurl again, you need to install the libcurl headers.

**Comment by filipkristo** [comment]
I installed it from sudo apt-get install libcurl4-gnutls-dev

**Comment by filipkristo** [comment]
Do You Know why i get this error before receiving new playlist?
![capture](https://cloud.githubusercontent.com/assets/8782505/7237880/d246a9e4-e79e-11e4-84e2-50b4dc374d61.PNG)

**Comment by PromyLOPh** [comment]
Uh, which one exactly?

**Comment by filipkristo** [comment]
All purple, red and yellow messages. If you don't receive this message, nevermind. Maybe today I have unstable Internet connection.
I 'm also developer, so I would like to add new command for setting station by id. What do you think about it?

**Comment by PromyLOPh** [comment]
> All purple, red and yellow messages. If you don't receive this
> message, nevermind. Maybe today I have unstable Internet connection.
Pandora is probably blocking/rate-limiting your account.

> I 'm also developer, so I would like to add new command for setting
> station by id. What do you think about it? 
What do you need it for?

**Comment by filipkristo** [comment]
I need because I have my PHP web site to control pianobar. Problem is because I can't change station. When pianobar starts it's always start last station, that is great, but I don't have commnad to change station from my extern application.

**Comment by PromyLOPh** [comment]
Have a look at contrib/eventcmd-examples/dmenu.pl and
contrib/change-station-dmenu.sh

**Comment by filipkristo** [comment]
What is best way to run it in background?

**Comment by PromyLOPh** [comment]
pianobar itself? A screen session.
