### ISSUE TITLE
Ubuntu 15.04 compile issues

### ISSUE THREAD

**Issue by ClashTheBunny** [PromyLOPh/pianobar#519]
By default ubuntu ships with libav, as this doesn't work with pianobar, it used to be a good idea to make your own local ffmpeg.  This is the error I get with libav dev packages installed:

```
LINK  pianobar
src/player.o: In function `BarPlayerThread':
player.c:(.text+0x98a): undefined reference to `av_buffersink_get_buffer_ref'
collect2: error: ld returned 1 exit status
Makefile:94: recipe for target 'pianobar' failed
make: *** [pianobar] Error 1
```

Ubuntu is now shipping with ffmpeg again starting with version 15.04.  If you want to compile pianobar, it's as easy as installing these packages from the default repos:

```bash
sudo apt-get install libavcodec-ffmpeg-dev \
                     libavdevice-ffmpeg-dev \
                     libavfilter-ffmpeg-dev \
                     libavformat-ffmpeg-dev \
                     libavresample-ffmpeg-dev \
                     libavutil-ffmpeg-dev \
                     libpostproc-ffmpeg-dev \
                     libswresample-ffmpeg-dev \
                     libswscale-ffmpeg-dev
```

Maybe a note in the readme would help, but this ticket is probably good enough for people googling for the same issue.  Is there a way to check if libav is installed and if so, suggest installing ffmpeg dev libraries in the Makefile?  That may be the best way.

**Comment by ClashTheBunny** [comment]
Also these packages:
```
apt-rdepends --build-depends --follow=DEPENDS pianobar | grep -v av | grep dev | awk '{print $2}' | xargs sudo apt-get install -y libcurl4-gnutls-dev
```

**Comment by PromyLOPh** [comment]
pianobar works fine with libav – I just built it against libav-11.3.
Assuming you’re building the current HEAD av_buffersink_get_buffer_ref
is used with ffmpeg 1.2 only (see src/config.h) and the error message
looks like your libavformat/version.h (likely installed by ffmpeg 1.2)
does not match the installed library (libav 11.2?).

**Comment by ClashTheBunny** [comment]
Yep, ignore this.  I had a problem with my upgrade removing some of the dev packages that my /usr/local build of ffmpeg depended on.  I then removed the libs without removing the headers, which were then messing up the compile.  I reverted back to the libav -dev packages and everything is working perfectly.  Both ways work.  Sorry for the confusion.
