### ISSUE TITLE
Problem with the SSL CA cert

### ISSUE THREAD

**Issue by ElBuki13** [PromyLOPh/pianobar#522]
Can't get pianobar to run. Any idea what we're doing wrong?

Welcome to pianobar (2014.09.28-dev)! Press ? for a list of commands.
(i) Control fifo at /home/pi/.config/pianobar/ctl opened
(i) Login... Network error: Problem with the SSL CA cert (path? access rights?)

uname -a Linux ElBukipi 3.18.12-v7+ #782 SMP PREEMPT Tue Apr 28 19:54:13 BST 2015 armv7l GNU/Linux

output from strace: http://pastebin.com/mESseVfQ

**Comment by PromyLOPh** [comment]
Line 164 of that paste looks fine, the ca bundle exists and is
accessible. So, not sure what’s the problem here. I assume you’re using
the current pianobar HEAD? Can you provide more details about the
libcurl you are using?

**Comment by PromyLOPh** [comment]
> Pretty sure, did a git pull before posting the issue just to be sure
> and it said "Already up-to-date." what's the best way to confirm that? 
`git pull` should be fine.

> ii  libcurl3:armhf                     7.26.0-1+wheezy13      armhf        library (OpenSSL flavour)
> ii  libcurl3-gnutls:armhf              7.26.0-1+wheezy13      armhf                  transfer library (GnuTLS flavour)
> ii  libcurl3-nss:armhf                 7.26.0-1+wheezy13      armhf            transfer library (NSS flavour)
> ii  libcurl4-gnutls-dev                7.26.0-1+wheezy13      armhf                  development files....
Can you remove libcurl3-nss and try again?

**Comment by ElBuki13** [comment]
Yes, here is what happened:

./pianobar: error while loading shared libraries: libcurl-nss.so.4: cannot open shared object file: No such file or directory

**Comment by PromyLOPh** [comment]
You’ll have to rebuild pianobar (`make clean && make`).

**Comment by ElBuki13** [comment]
That did the trick. Thanks

**Comment by josephwinston** [comment]
I'm having the same issue on OS X.

**Comment by PromyLOPh** [comment]
Can you post the output of `curl -V`?

**Comment by josephwinston** [comment]
```bash
/opt/local/bin/curl -V
curl 7.42.1 (x86_64-apple-darwin14.1.0) libcurl/7.42.1 OpenSSL/1.0.2a zlib/1.2.8 libidn/1.29
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: IDN IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP UnixSockets
```

**Comment by PromyLOPh** [comment]
Can you apply this patch https://gist.github.com/anonymous/2419a6412fe1c0a94e2a
and set `ca_bundle = /etc/ssl/certs/ca-certificates.crt` (you may have to
adjust the path) in your config file?

**Comment by glattercj** [comment]
I'm having the same issue on Ubuntu 14.04. 

I have the latest pull, tried applying the patch above and setting the ca_bundle in my config, but I still get the "Peer certificate cannot be authenticated with given CA certificates" error. I am also behind a proxy.

Here's the output of curl -V:
```
curl 7.35.0 (x86_64-pc-linux-gnu) libcurl/7.35.0 OpenSSL/1.0.1f zlib/1.2.8 libidn/1.28 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smtp smtps telnet tftp 
Features: AsynchDNS GSS-Negotiate IDN IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP
```

Any ideas?

**Comment by josephwinston** [comment]
I applied the patch https://gist.github.com/anonymous/2419a6412fe1c0a94e2a, `make clean`, `make`, and created the file `~/.config/pianobar/config` with the value of `ca_bundle = /opt/local/share/curl/curl-ca-bundle.crt`.  Yet, the error remains:

```bash
Network error: Peer certificate cannot be authenticated with given CA certificates
```

Debugging `pianobar` shows that `settings->caBundle` is set to the expected value.

**Comment by PromyLOPh** [comment]
Is `openssl s_client -CAfile /path/to/bundle -connect tuner.pandora.com:443`
showing the correct certificate chain? The output should start with this:
https://gist.github.com/anonymous/423c7c9d9afaeff2db7e

**Comment by josephwinston** [comment]
Here are the first few lines:
```bash
$ openssl s_client -CAfile /opt/local/share/curl/curl-ca-bundle.crt -connect tuner.pandora.com:443
CONNECTED(00000003)
depth=2 C = US, O = "VeriSign, Inc.", OU = VeriSign Trust Network, OU = "(c) 2006 VeriSign, Inc. - For authorized use only", CN = VeriSign Class 3 Public Primary Certification Authority - G5
verify error:num=20:unable to get local issuer certificate
---
Certificate chain
 0 s:/C=US/ST=California/L=Oakland/O=Pandora Media, Inc./OU=Engineering/OU=Terms of use at www.verisign.com/rpa (c)05/CN=tuner.pandora.com
   i:/C=US/O=VeriSign, Inc./OU=VeriSign Trust Network/OU=Terms of use at https://www.verisign.com/rpa (c)10/CN=VeriSign Class 3 Secure Server CA - G3
 1 s:/C=US/O=VeriSign, Inc./OU=VeriSign Trust Network/OU=Terms of use at https://www.verisign.com/rpa (c)10/CN=VeriSign Class 3 Secure Server CA - G3
   i:/C=US/O=VeriSign, Inc./OU=VeriSign Trust Network/OU=(c) 2006 VeriSign, Inc. - For authorized use only/CN=VeriSign Class 3 Public Primary Certification Authority - G5
 2 s:/C=US/O=VeriSign, Inc./OU=VeriSign Trust Network/OU=(c) 2006 VeriSign, Inc. - For authorized use only/CN=VeriSign Class 3 Public Primary Certification Authority - G5
   i:/C=US/O=VeriSign, Inc./OU=Class 3 Public Primary Certification Authority
---
```

**Comment by PromyLOPh** [comment]
> depth=2 C = US, O = "VeriSign, Inc.", OU = VeriSign Trust Network, OU = "(c) 2006 VeriSign, Inc. - For authorized use only", CN = VeriSign Class 3 Public Primary Certification Authority - G5
> verify error:num=20:unable to get local issuer certificate
Well, the certificate bundle seems to lack this intermediate certificate. I’m
not sure how we can get a copy of it though.

**Comment by PromyLOPh** [comment]
So, apparently you can download the Verisign CA bundle here: https://www.symantec.com/page.jsp?id=roots
Unzip it, then run `find /path/to/unzipped/file -name '*.pem' | while read -r L; do cat "$L"; echo; done >> /your/cabundle` (or put all the .pem files in one file by hand) and use it as ca_bundle instead.
