### ISSUE TITLE
Feature request: reduce song repetition

### ISSUE THREAD

**Issue by rdeforest** [PromyLOPh/pianobar#525]
Pandora itself is terrible about repeating songs. Years ago it used to be that the snooze feature would prevent a song from being played for 30 days. Now it seems to be 24 hours or less. It's so bad that I can tell when a bar is playing Pandora because I hear the same songs as on my own stations.

I already complained to Pandora customer service about this, but I do not expect any improvement from them.

The feature I want is the ability to set a maximum song repetition rate and have pianobar skip repeated songs without it counting against a skip limit (if/when that's implemented).

**Comment by PromyLOPh** [comment]
> I already complained to Pandora customer service about this, but I do
> not expect any improvement from them.
What was their response?

> The feature I want is the ability to set a maximum song repetition
> rate and have pianobar skip repeated songs without it counting against
> a skip limit (if/when that's implemented).
There are server-side limitations in place and fetching playlists too
fast (because songs were skipped) may result in a temporary ban.
See #413 and #415 for example.

**Comment by rdeforest** [comment]
Bleah. That's depressing. This is one of the reasons people violate audio and video copyright. (I object to referring to it as 'piracy'.) I'll close this issue and reconsider my Pandora subscription...
