### ISSUE TITLE
Network error: Connection refused

### ISSUE THREAD

**Issue by liuche** [PromyLOPh/pianobar#526]
Updated from Homebrew to 2014.09.28, and always get an immediate "Network error: Connection refused".
Homebrew is up to date, and this is running on Mountain Lion 10.9.5.

**Comment by PromyLOPh** [comment]
The release works fine here. Can you rule out a proxy or connectivity
issue?

**Comment by liuche** [comment]
I'm not using a proxy, and my normal internet connection works for everything else.

**Comment by PromyLOPh** [comment]
Well, homebrew is essentially “built from source”, isn’t it? Have you
tried capturing a trace with Wireshark/tcpdump? My best guess right now
would be an issue with IPv6 (i.e. address assigned, but no actual
connectivity).

**Comment by liuche** [comment]
I fixed this issue by removing my .config/pianobar/config file and logging in manually every time. Even having it around with everything commented out caused the "network error" message.

**Comment by PromyLOPh** [comment]
Does this happen with an empty config file as well? If not: Can you post
your config file here?

**Comment by liuche** [comment]
It turns out that I had a space between a # and the control_proxy line (and the proxy stopped being operational) and this was causing problems.

# control_proxy = xxx

**Comment by PromyLOPh** [comment]
That is a bug. Seems like we finally found ourselves a reason to fix the
config file parsing code :)
