### ISSUE TITLE
dyld: Library not loaded: /usr/local/lib/liblzma.5.dylib

### ISSUE THREAD

**Issue by reidcooper** [PromyLOPh/pianobar#530]
I get this issue when I run pianobar:

    dyld: Library not loaded: /usr/local/lib/liblzma.5.dylib
      Referenced from: /usr/local/lib/libavcodec.56.dylib
      Reason: Incompatible library version: libavcodec.56.dylib requires version 8.0.0 or later, but liblzma.5.dylib provides version 6.0.0
    [1]    13638 trace trap  pianobar

Any suggestions?

**Comment by gwark000** [comment]
I've also gotten this same error installing onto a new OS X machine via brew. Which OS/install method are you using?

**Comment by reidcooper** [comment]
I am currently using The most up to date Yosemite and I am using brew.

**Comment by PromyLOPh** [comment]
Please move this issue to the brew bug tracker. There’s nothing I can do
about it here.

**Comment by gwark000** [comment]
Issue has resolved itself for me after no significant action. Perhaps a simple restart or logout was needed.

@reidcooper, does this work for you?

**Comment by reidcooper** [comment]
I just tried it and it didn't work, unfortunately.

**Comment by reidcooper** [comment]
I found a fix, 

http://stackoverflow.com/questions/31612086/cannot-get-ffmpeg-to-work-after-installing-from-homebrew

Run:    

    brew install xz

That should fix it.
