### ISSUE TITLE
Proxy support no longer functional

### ISSUE THREAD

**Issue by cmansley** [PromyLOPh/pianobar#531]
I am using Ubuntu 14.04.

If I checkout/compile version 2013.09.15, proxy support works just fine. Everything functions correctly.

If I checkout the latest version, I get the following error
[tcp @ 0x7f31dc003840] Failed to resolve hostname audio-ch1-t1-1-v4v6.pandora.com: No address associated with hostname

Digging deeper this seems to arise from ffmpeg here:
http://ffmpeg.org/doxygen/trunk/tcp_8c_source.html#l00111

which is because the preceding call fails to resolve the hostname. 

It doesn't seem like their API supports proxies.

**Comment by PromyLOPh** [comment]
ffmpeg does support HTTP proxies, but I guess you set the proxy variable
in pianobar’s config file, right? Does it work if you set the
environment variable http_proxy instead?

**Comment by cmansley** [comment]
I have both the proxy settings in pianobar set and http_proxy variables
set.
-chris

**Comment by PromyLOPh** [comment]
> I have both the proxy settings in pianobar set and http_proxy variables
> set.
I suppose their values are equal? As far as I see libav 9.18 (as used by
Ubuntu 14.04) should respect the environment variable http_proxy. Thus
it should work.

**Comment by cmansley** [comment]
I just tried the latest head revision 34b6068d229ef and I still had the same issue :(

**Comment by PromyLOPh** [comment]
Hm, you could compile a recent ffmpeg release (see
https://github.com/PromyLOPh/pianobar/wiki/ffmpeg) and link pianobar
against that.
