### ISSUE TITLE
Error trying to run on Mac OS X installed via homebrew -- needs newer version of GMP

### ISSUE THREAD

**Issue by mikeokner** [PromyLOPh/pianobar#535]
I'm using homebrew to install pianobar on Mac OS X 10.10.5 and seeing the following output when trying to run it:

```shell
$ brew install pianobar
==> Downloading http://6xq.net/projects/pianobar/pianobar-2014.09.28.tar.bz2
==> Downloading from http://6xq.net/pianobar/pianobar-2014.09.28.tar.bz2
######################################################################## 100.0%
==> make PREFIX=/usr/local/Cellar/pianobar/2014.09.28
==> make install PREFIX=/usr/local/Cellar/pianobar/2014.09.28
🍺  /usr/local/Cellar/pianobar/2014.09.28: 18 files, 176K, built in 2 seconds
$ pianobar
dyld: Library not loaded: /usr/local/lib/libgmp.10.dylib
  Referenced from: /usr/local/lib/libgnutls.28.dylib
  Reason: Incompatible library version: libgnutls.28.dylib requires version 13.0.0 or later, but libgmp.10.dylib provides version 12.0.0
[1]    78772 trace trap  pianobar
```

Installing GMP 6.0.0 from source fixed the problem. I'm not familiar with homebrew's configuration process, but I'd guess you need to update a dependency version in there.

**Comment by PromyLOPh** [comment]
I’m not maintaining the homebrew package. Head over to their issue
tracker and file a bug: https://github.com/Homebrew/homebrew/issues

**Comment by mikeokner** [comment]
New issue created over there.

BTW this is probably one of the most useful random programs I've stumbled across in a long time, so thanks!
