### ISSUE TITLE
tmux: pianobar doesn't play

### ISSUE THREAD

**Issue by kudumi** [PromyLOPh/pianobar#538]
does pianobar work with tmux? I can successfully login, pianobar retrieves the playlist but doesn't play

i) Login... Ok.
(i) Get stations... Ok.
|>  Station "Today's Hits Radio" (1755939192117112328)
(i) Receiving new playlist... Ok.
|>  "Where Are U Now (Feat. Justin Bieber)" by "Skrillex & Diplo" on "Skrillex And Diplo Present Jack U"

that's all nothing happens afterwards but pianobar does play without tmux in terminal (it doesn't work only in tmux)

**Comment by PromyLOPh** [comment]
I don’t see a reason it shouldn’t work. The current master works for me
with a fresh tmux install (1.9a). Can you provide more information like
pianobar version, tmux version and configuration, OS, …

**Comment by kudumi** [comment]
Mac OSX (10.10.5)
pianobar 2014.09.28
tmux: 1.9a

both of them were installed from homebrew and there are no further updates available

tmux: either with default or custom configuration doesn't make any difference
Pianobar: $ cat config 
tls_fingerprint = 2D0AFDAFA16F4B5C0A43F3CB1D4752F9535507C0
user = username
password = password
control_proxy = http://127.0.0.1:8123
event_command = /Users/name/.config/pianobar/eventcommand.sh

**Comment by PromyLOPh** [comment]
> pianobar 2014.09.28
That release works for me too. I’m running Linux though. If you have gdb
installed and enabled/installed debugging symbols (no idea how to do
that with homebrew) then a backtrace might help us. See
https://wiki.ubuntu.com/Backtrace#Generation (As always: Make sure you
remove passwords before posting it)

**Comment by cburmeister** [comment]
I get this from time to time... using `pianobar 2014.09.28` and `tmux 2.0` on OSX 10.10.4

**Comment by lordB8r** [comment]
I'm on iTerm2, using tmux with zsh, and have no problem running (though Scrobbler gives me problems from time to time). 

OSX: 10.10.5
zsh: 5.0.7
pianobar: 2014.09.28
tmux: 1.9a
iterm2: 2.1.1

**Comment by cburmeister** [comment]
Restarting `pianobar` usually fixes the problem, sometimes it takes a couple times though.

**Comment by kudumi** [comment]
strange neither iTerm (2.1.1) nor terminal works for pianobar under tmux (OS X 10.10.5), restarting pianobar has no effect.

@lordB8r Could you share your pianobar config?
