### ISSUE TITLE
pianobar proxy username symbol support

### ISSUE THREAD

**Issue by vorell** [PromyLOPh/pianobar#539]
I am trying to route pianobar through a web proxy. Part of the authentication is the username which is an email address.

I have tried the following lines to no success and was wondering if there is a special delimiter or separate config declaration I can use to get around this.

http_proxy = http://user@domain.org:password@web.proxy:6060/

The first @ sign throws off the parameter since it then tries to use the email domain as the proxy domain.

Thanks

**Comment by shaggytwodope** [comment]
@vorell Seems like a silly response/question.But have you tried:

`http_proxy = "http://user@domain.org:password@web.proxy:6060"`

**Comment by PromyLOPh** [comment]
Looking at RFC 3986 the @ should be percent-encoded, i.e. replaced with
%40. The proxy is passed to libcurl as-is though and I don’t know if
libcurl decodes it.

**Comment by vorell** [comment]
I gave that a try and am now getting an unknown http response error code. I will look into it further as time permits.

Thanks for the pointer.

**Comment by fengshaun** [comment]
I think urls requiring basic authentication have the format: <http://user:password@example.com:1234>. At least that's what I've always used as far as urls are concerned and it's working in pianobar.

**Comment by thedmd** [comment]
`user` may expand to an email address. I had to [deal with this situation](https://github.com/thedmd/pianobar-windows/commit/e1eed89e03c0aadbd6c7781ce680768a16be7c03) on Windows port of pianobar. You may find `HttpUrlDecodeInplace` which I use to decode username and password for proxy.
