### ISSUE TITLE
Input Buffer Exhausted and element type mismatch 1 != 0 errors

### ISSUE THREAD

**Issue by ZevEisenberg** [PromyLOPh/pianobar#542]
Occasionally, while I’m listening, I get this:

```
|>  "Too Late To Cry" by "Alison Krauss" on "Too Late To Cry" <3
[aac @ 0x7fe99d800000] Input buffer exhausted before END element found
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7fe99c00da00] stream 0, offset 0xad75e: partial file
[aac @ 0x7fe99d00a000] element type mismatch 1 != 0
[aac @ 0x7fe99d00a000] element type mismatch 1 != 0
[aac @ 0x7fe99d00a000] element type mismatch 1 != 0
[aac @ 0x7fe99d00a000] element type mismatch 1 != 0
[aac @ 0x7fe99d00a000] element type mismatch 1 != 0
[aac @ 0x7fe99d00a000] element type mismatch 1 != 0
[aac @ 0x7fe99d00a000] element type mismatch 1 != 0
[aac @ 0x7fe99d00a000] element type mismatch 1 != 0
[aac @ 0x7fe99d00a000] element type mismatch 1 != 0
[aac @ 0x7fe99d00a000] element type mismatch 1 != 0
```

The audio stutters for a fraction of a second, then keeps playing. As far as I know, my Internet connection is fast and reliable, so I don’t think I’m running into network issues. Any logs I can post that will help?

**Comment by ZevEisenberg** [comment]
I feel like I’ve filed something like this before, but I couldn’t find it, and this looks like a slightly different error message.

**Comment by PromyLOPh** [comment]
Yeah, that happens whenever the connection to the server is interrupted.
The error message depends on decoder and file position, but there’s
always “input buffer exhaused” and “partial file” in there. There are no
logfiles, only the messages you see on your screen, so you’ll have to
use tcpdump/wireshark to debug this issue.

See https://github.com/PromyLOPh/pianobar/search?q=Input+buffer+exhausted&type=Issues&utf8=%E2%9C%93
