### ISSUE TITLE
Use of deprecated Carbon Component Manager on OS X 10.11

### ISSUE THREAD

**Issue by ZevEisenberg** [PromyLOPh/pianobar#543]
When launching Pianobar for the first time on OS X 10.11, I get this warning just after the first song starts playing:

>2015-10-01 15:07:27.136 pianobar[18384:687874] 15:07:27.136 WARNING:  140: This application, or a library it uses, is using the deprecated Carbon Component Manager for hosting Audio Units. Support for this will be removed in a future release. Also, this makes the host incompatible with version 3 audio units. Please transition to the API's in AudioComponent.h.

**Comment by ZevEisenberg** [comment]
This warning reappears every time a new song starts playing.

**Comment by PromyLOPh** [comment]
See #529.

**Comment by ZevEisenberg** [comment]
Thanks.
