### ISSUE TITLE
Carbon Component Manager Deprecated

### ISSUE THREAD

**Issue by steveoh** [PromyLOPh/pianobar#545]
After updating to el cap, pianobar looks like this will require an update to some new api's. 

>2015-10-05 09:18:33.270 pianobar[4892:34862] 09:18:33.269 WARNING:  140: This application, or a library it uses, is using the deprecated Carbon Component Manager for hosting Audio Units. Support for this will be removed in a future release. Also, this makes the host incompatible with version 3 audio units. Please transition to the API's in AudioComponent.h.

**Comment by PromyLOPh** [comment]
See #529
