### ISSUE TITLE
New version pushed to homebrew

### ISSUE THREAD

**Issue by stdavis** [PromyLOPh/pianobar#546]
Is there anyway a new version can be pushed to homebrew? Looks like the current one is over a year old.

**Comment by lordB8r** [comment]
Just made a pull request to homebrew with the updated file, but not sure if
that'll make a difference. Not sure how often they look for changes and/or
accept pull requests...

On Fri, Oct 9, 2015 at 10:08 AM, Scott Davis <notifications@github.com>
wrote:

> Is there anyway a new version can be pushed to homebrew? Looks like the
> current one is over a year old.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PromyLOPh/pianobar/issues/546>.
>



-- 
JP Bader
Principal
Next Health Choice, LLC
jp@nexthealthchoice.com | 312.614.1267

**Comment by stdavis** [comment]
I'm not a brew expert but don't you need to cut a new release on github,
then make a PR to brew that points to the new release?

On Fri, Oct 9, 2015 at 9:35 AM, JP Bader <notifications@github.com> wrote:

> Just made a pull request to homebrew with the updated file, but not sure if
> that'll make a difference. Not sure how often they look for changes and/or
> accept pull requests...
>
> On Fri, Oct 9, 2015 at 10:08 AM, Scott Davis <notifications@github.com>
> wrote:
>
> > Is there anyway a new version can be pushed to homebrew? Looks like the
> > current one is over a year old.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/PromyLOPh/pianobar/issues/546>.
> >
>
>
>
> --
> JP Bader
> Principal
> Next Health Choice, LLC
> jp@nexthealthchoice.com | 312.614.1267
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PromyLOPh/pianobar/issues/546#issuecomment-146905337>.
>



-- 
*Scott Davis*
Utah AGRC <http://gis.utah.gov/developer/>
stdavis@utah.gov
@SThomasDavis <https://twitter.com/SThomasDavis>

**Comment by lordB8r** [comment]
I tried all of that, and then was told that I was out of date. Apparently
this was already done:
https://github.com/Homebrew/homebrew/commit/52ef42d55132c2e14abc10cfe8dae56f3f10473e


On Fri, Oct 9, 2015 at 12:16 PM, Scott Davis <notifications@github.com>
wrote:

> I'm not a brew expert but don't you need to cut a new release on github,
> then make a PR to brew that points to the new release?
>
> On Fri, Oct 9, 2015 at 9:35 AM, JP Bader <notifications@github.com> wrote:
>
> > Just made a pull request to homebrew with the updated file, but not sure
> if
> > that'll make a difference. Not sure how often they look for changes
> and/or
> > accept pull requests...
> >
> > On Fri, Oct 9, 2015 at 10:08 AM, Scott Davis <notifications@github.com>
> > wrote:
> >
> > > Is there anyway a new version can be pushed to homebrew? Looks like the
> > > current one is over a year old.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/PromyLOPh/pianobar/issues/546>.
> > >
> >
> >
> >
> > --
> > JP Bader
> > Principal
> > Next Health Choice, LLC
> > jp@nexthealthchoice.com | 312.614.1267
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/PromyLOPh/pianobar/issues/546#issuecomment-146905337
> >.
> >
>
>
>
> --
> *Scott Davis*
> Utah AGRC <http://gis.utah.gov/developer/>
> stdavis@utah.gov
> @SThomasDavis <https://twitter.com/SThomasDavis>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PromyLOPh/pianobar/issues/546#issuecomment-146936305>.
>



-- 
JP Bader
Principal
Zavteq, Inc.
@lordB8r | jp@zavteq.com
608.692.2468

**Comment by stdavis** [comment]
The PR that you submitted points to the release of pianobar that's over a
year old (2014.09.28).

On Fri, Oct 9, 2015 at 11:19 AM, JP Bader <notifications@github.com> wrote:

> I tried all of that, and then was told that I was out of date. Apparently
> this was already done:
>
> https://github.com/Homebrew/homebrew/commit/52ef42d55132c2e14abc10cfe8dae56f3f10473e
>
>
> On Fri, Oct 9, 2015 at 12:16 PM, Scott Davis <notifications@github.com>
> wrote:
>
> > I'm not a brew expert but don't you need to cut a new release on github,
> > then make a PR to brew that points to the new release?
> >
> > On Fri, Oct 9, 2015 at 9:35 AM, JP Bader <notifications@github.com>
> wrote:
> >
> > > Just made a pull request to homebrew with the updated file, but not
> sure
> > if
> > > that'll make a difference. Not sure how often they look for changes
> > and/or
> > > accept pull requests...
> > >
> > > On Fri, Oct 9, 2015 at 10:08 AM, Scott Davis <notifications@github.com
> >
> > > wrote:
> > >
> > > > Is there anyway a new version can be pushed to homebrew? Looks like
> the
> > > > current one is over a year old.
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <https://github.com/PromyLOPh/pianobar/issues/546>.
> > > >
> > >
> > >
> > >
> > > --
> > > JP Bader
> > > Principal
> > > Next Health Choice, LLC
> > > jp@nexthealthchoice.com | 312.614.1267
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> https://github.com/PromyLOPh/pianobar/issues/546#issuecomment-146905337
> > >.
> > >
> >
> >
> >
> > --
> > *Scott Davis*
> > Utah AGRC <http://gis.utah.gov/developer/>
> > stdavis@utah.gov
> > @SThomasDavis <https://twitter.com/SThomasDavis>
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/PromyLOPh/pianobar/issues/546#issuecomment-146936305
> >.
> >
>
>
>
> --
> JP Bader
> Principal
> Zavteq, Inc.
> @lordB8r | jp@zavteq.com
> 608.692.2468
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PromyLOPh/pianobar/issues/546#issuecomment-146937286>.
>



-- 
*Scott Davis*
Utah AGRC <http://gis.utah.gov/developer/>
stdavis@utah.gov
@SThomasDavis <https://twitter.com/SThomasDavis>

**Comment by lordB8r** [comment]
Brew takes the latest tarball that is available. I just looked at the date
here: http://6xq.net/pianobar/. Maybe that's out of date, but I don't see a
tarball that's newer.

On Fri, Oct 9, 2015 at 12:24 PM, Scott Davis <notifications@github.com>
wrote:

> The PR that you submitted points to the release of pianobar that's over a
> year old (2014.09.28).
>
>
> On Fri, Oct 9, 2015 at 11:19 AM, JP Bader <notifications@github.com>
> wrote:
>
> > I tried all of that, and then was told that I was out of date. Apparently
> > this was already done:
> >
> >
> https://github.com/Homebrew/homebrew/commit/52ef42d55132c2e14abc10cfe8dae56f3f10473e
> >
> >
> > On Fri, Oct 9, 2015 at 12:16 PM, Scott Davis <notifications@github.com>
> > wrote:
> >
> > > I'm not a brew expert but don't you need to cut a new release on
> github,
> > > then make a PR to brew that points to the new release?
> > >
> > > On Fri, Oct 9, 2015 at 9:35 AM, JP Bader <notifications@github.com>
> > wrote:
> > >
> > > > Just made a pull request to homebrew with the updated file, but not
> > sure
> > > if
> > > > that'll make a difference. Not sure how often they look for changes
> > > and/or
> > > > accept pull requests...
> > > >
> > > > On Fri, Oct 9, 2015 at 10:08 AM, Scott Davis <
> notifications@github.com
> > >
> > > > wrote:
> > > >
> > > > > Is there anyway a new version can be pushed to homebrew? Looks like
> > the
> > > > > current one is over a year old.
> > > > >
> > > > > —
> > > > > Reply to this email directly or view it on GitHub
> > > > > <https://github.com/PromyLOPh/pianobar/issues/546>.
> > > > >
> > > >
> > > >
> > > >
> > > > --
> > > > JP Bader
> > > > Principal
> > > > Next Health Choice, LLC
> > > > jp@nexthealthchoice.com | 312.614.1267
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <
> > https://github.com/PromyLOPh/pianobar/issues/546#issuecomment-146905337
> > > >.
> > > >
> > >
> > >
> > >
> > > --
> > > *Scott Davis*
> > > Utah AGRC <http://gis.utah.gov/developer/>
> > > stdavis@utah.gov
> > > @SThomasDavis <https://twitter.com/SThomasDavis>
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> https://github.com/PromyLOPh/pianobar/issues/546#issuecomment-146936305
> > >.
> > >
> >
> >
> >
> > --
> > JP Bader
> > Principal
> > Zavteq, Inc.
> > @lordB8r | jp@zavteq.com
> > 608.692.2468
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/PromyLOPh/pianobar/issues/546#issuecomment-146937286
> >.
>
> >
>
>
>
> --
> *Scott Davis*
> Utah AGRC <http://gis.utah.gov/developer/>
> stdavis@utah.gov
> @SThomasDavis <https://twitter.com/SThomasDavis>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PromyLOPh/pianobar/issues/546#issuecomment-146938705>.
>



-- 
JP Bader
Principal
Zavteq, Inc.
@lordB8r | jp@zavteq.com
608.692.2468

**Comment by stdavis** [comment]
I assumed that you would need to cut a new GitHub release to create a new
tarball here: https://github.com/PromyLOPh/pianobar/releases

On Fri, Oct 9, 2015 at 11:26 AM, JP Bader <notifications@github.com> wrote:

> Brew takes the latest tarball that is available. I just looked at the date
> here: http://6xq.net/pianobar/. Maybe that's out of date, but I don't see
> a
> tarball that's newer.
>
> On Fri, Oct 9, 2015 at 12:24 PM, Scott Davis <notifications@github.com>
>
> wrote:
>
> > The PR that you submitted points to the release of pianobar that's over a
> > year old (2014.09.28).
> >
> >
> > On Fri, Oct 9, 2015 at 11:19 AM, JP Bader <notifications@github.com>
> > wrote:
> >
> > > I tried all of that, and then was told that I was out of date.
> Apparently
> > > this was already done:
> > >
> > >
> >
> https://github.com/Homebrew/homebrew/commit/52ef42d55132c2e14abc10cfe8dae56f3f10473e
> > >
> > >
> > > On Fri, Oct 9, 2015 at 12:16 PM, Scott Davis <notifications@github.com
> >
> > > wrote:
> > >
> > > > I'm not a brew expert but don't you need to cut a new release on
> > github,
> > > > then make a PR to brew that points to the new release?
> > > >
> > > > On Fri, Oct 9, 2015 at 9:35 AM, JP Bader <notifications@github.com>
> > > wrote:
> > > >
> > > > > Just made a pull request to homebrew with the updated file, but not
> > > sure
> > > > if
> > > > > that'll make a difference. Not sure how often they look for changes
> > > > and/or
> > > > > accept pull requests...
> > > > >
> > > > > On Fri, Oct 9, 2015 at 10:08 AM, Scott Davis <
> > notifications@github.com
> > > >
> > > > > wrote:
> > > > >
> > > > > > Is there anyway a new version can be pushed to homebrew? Looks
> like
> > > the
> > > > > > current one is over a year old.
> > > > > >
> > > > > > —
> > > > > > Reply to this email directly or view it on GitHub
> > > > > > <https://github.com/PromyLOPh/pianobar/issues/546>.
> > > > > >
> > > > >
> > > > >
> > > > >
> > > > > --
> > > > > JP Bader
> > > > > Principal
> > > > > Next Health Choice, LLC
> > > > > jp@nexthealthchoice.com | 312.614.1267
> > > > >
> > > > > —
> > > > > Reply to this email directly or view it on GitHub
> > > > > <
> > >
> https://github.com/PromyLOPh/pianobar/issues/546#issuecomment-146905337
> > > > >.
> > > > >
> > > >
> > > >
> > > >
> > > > --
> > > > *Scott Davis*
> > > > Utah AGRC <http://gis.utah.gov/developer/>
> > > > stdavis@utah.gov
> > > > @SThomasDavis <https://twitter.com/SThomasDavis>
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <
> > https://github.com/PromyLOPh/pianobar/issues/546#issuecomment-146936305
> > > >.
> > > >
> > >
> > >
> > >
> > > --
> > > JP Bader
> > > Principal
> > > Zavteq, Inc.
> > > @lordB8r | jp@zavteq.com
> > > 608.692.2468
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> https://github.com/PromyLOPh/pianobar/issues/546#issuecomment-146937286
> > >.
> >
> > >
> >
> >
> >
> > --
> > *Scott Davis*
> > Utah AGRC <http://gis.utah.gov/developer/>
> > stdavis@utah.gov
> > @SThomasDavis <https://twitter.com/SThomasDavis>
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/PromyLOPh/pianobar/issues/546#issuecomment-146938705
> >.
>
> >
>
>
>
> --
> JP Bader
> Principal
> Zavteq, Inc.
> @lordB8r | jp@zavteq.com
> 608.692.2468
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PromyLOPh/pianobar/issues/546#issuecomment-146939047>.
>



-- 
*Scott Davis*
Utah AGRC <http://gis.utah.gov/developer/>
stdavis@utah.gov
@SThomasDavis <https://twitter.com/SThomasDavis>

**Comment by lordB8r** [comment]
I *think* @PromyLOPH has to push the newest tarball to releases, then
homebrew could be updated for that.

On Fri, Oct 9, 2015 at 12:31 PM, Scott Davis <notifications@github.com>
wrote:

> I assumed that you would need to cut a new GitHub release to create a new
> tarball here: https://github.com/PromyLOPh/pianobar/releases
>
> On Fri, Oct 9, 2015 at 11:26 AM, JP Bader <notifications@github.com>
> wrote:
>
> > Brew takes the latest tarball that is available. I just looked at the
> date
> > here: http://6xq.net/pianobar/. Maybe that's out of date, but I don't
> see
> > a
> > tarball that's newer.
> >
> > On Fri, Oct 9, 2015 at 12:24 PM, Scott Davis <notifications@github.com>
> >
> > wrote:
> >
> > > The PR that you submitted points to the release of pianobar that's
> over a
> > > year old (2014.09.28).
> > >
> > >
> > > On Fri, Oct 9, 2015 at 11:19 AM, JP Bader <notifications@github.com>
> > > wrote:
> > >
> > > > I tried all of that, and then was told that I was out of date.
> > Apparently
> > > > this was already done:
> > > >
> > > >
> > >
> >
> https://github.com/Homebrew/homebrew/commit/52ef42d55132c2e14abc10cfe8dae56f3f10473e
> > > >
> > > >
> > > > On Fri, Oct 9, 2015 at 12:16 PM, Scott Davis <
> notifications@github.com
> > >
> > > > wrote:
> > > >
> > > > > I'm not a brew expert but don't you need to cut a new release on
> > > github,
> > > > > then make a PR to brew that points to the new release?
> > > > >
> > > > > On Fri, Oct 9, 2015 at 9:35 AM, JP Bader <notifications@github.com
> >
> > > > wrote:
> > > > >
> > > > > > Just made a pull request to homebrew with the updated file, but
> not
> > > > sure
> > > > > if
> > > > > > that'll make a difference. Not sure how often they look for
> changes
> > > > > and/or
> > > > > > accept pull requests...
> > > > > >
> > > > > > On Fri, Oct 9, 2015 at 10:08 AM, Scott Davis <
> > > notifications@github.com
> > > > >
> > > > > > wrote:
> > > > > >
> > > > > > > Is there anyway a new version can be pushed to homebrew? Looks
> > like
> > > > the
> > > > > > > current one is over a year old.
> > > > > > >
> > > > > > > —
> > > > > > > Reply to this email directly or view it on GitHub
> > > > > > > <https://github.com/PromyLOPh/pianobar/issues/546>.
> > > > > > >
> > > > > >
> > > > > >
> > > > > >
> > > > > > --
> > > > > > JP Bader
> > > > > > Principal
> > > > > > Next Health Choice, LLC
> > > > > > jp@nexthealthchoice.com | 312.614.1267
> > > > > >
> > > > > > —
> > > > > > Reply to this email directly or view it on GitHub
> > > > > > <
> > > >
> > https://github.com/PromyLOPh/pianobar/issues/546#issuecomment-146905337
> > > > > >.
> > > > > >
> > > > >
> > > > >
> > > > >
> > > > > --
> > > > > *Scott Davis*
> > > > > Utah AGRC <http://gis.utah.gov/developer/>
> > > > > stdavis@utah.gov
> > > > > @SThomasDavis <https://twitter.com/SThomasDavis>
> > > > >
> > > > > —
> > > > > Reply to this email directly or view it on GitHub
> > > > > <
> > >
> https://github.com/PromyLOPh/pianobar/issues/546#issuecomment-146936305
> > > > >.
> > > > >
> > > >
> > > >
> > > >
> > > > --
> > > > JP Bader
> > > > Principal
> > > > Zavteq, Inc.
> > > > @lordB8r | jp@zavteq.com
> > > > 608.692.2468
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <
> > https://github.com/PromyLOPh/pianobar/issues/546#issuecomment-146937286
> > > >.
> > >
> > > >
> > >
> > >
> > >
> > > --
> > > *Scott Davis*
> > > Utah AGRC <http://gis.utah.gov/developer/>
> > > stdavis@utah.gov
> > > @SThomasDavis <https://twitter.com/SThomasDavis>
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> https://github.com/PromyLOPh/pianobar/issues/546#issuecomment-146938705
> > >.
> >
> > >
> >
> >
> >
> > --
> > JP Bader
> > Principal
> > Zavteq, Inc.
> > @lordB8r | jp@zavteq.com
> > 608.692.2468
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/PromyLOPh/pianobar/issues/546#issuecomment-146939047
> >.
> >
>
>
>
> --
> *Scott Davis*
> Utah AGRC <http://gis.utah.gov/developer/>
> stdavis@utah.gov
> @SThomasDavis <https://twitter.com/SThomasDavis>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PromyLOPh/pianobar/issues/546#issuecomment-146940049>.
>



-- 
JP Bader
Principal
Zavteq, Inc.
@lordB8r | jp@zavteq.com
608.692.2468

**Comment by PromyLOPh** [comment]
Right now there’s one change in my queue. If no issues pop up a few
weeks after pushing that to master I’ll prepare a release.

**Comment by stdavis** [comment]
Sweet! Thanks!

-Scott
Sent from a mobile device

On Oct 10, 2015, at 1:34 PM, PromyLOPh <notifications@github.com> wrote:

Right now there’s one change in my queue. If no issues pop up a few
weeks after pushing that to master I’ll prepare a release.

—
Reply to this email directly or view it on GitHub
<https://github.com/PromyLOPh/pianobar/issues/546#issuecomment-147119531>.

**Comment by burlesona** [comment]
Just curious, how's it looking for this to be pushed to homebrew?

**Comment by PromyLOPh** [comment]
There’s no new release yet.

**Comment by steveoh** [comment]
`brew reinstall --HEAD pianobar` should checkout the master branch if you want that

**Comment by PromyLOPh** [comment]
There we go, just released a new version 2015.11.22.

**Comment by steveoh** [comment]
Great news. It is not in brew yet. Does someone need to update the recipe there?

**Comment by lordB8r** [comment]
I believe you have to make a pull request against the homebrew repo. From
there they'll update.

On Mon, Nov 23, 2015 at 11:24 AM, steveoh <notifications@github.com> wrote:

> Great news. It is not in brew yet. Does someone need to update the recipe
> there?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PromyLOPh/pianobar/issues/546#issuecomment-159002244>.
>



-- 
JP Bader
Principal
Zavteq, Inc.
@lordB8r | jp@zavteq.com
608.692.2468
