### ISSUE TITLE
Unable to open audio file (End of file)

### ISSUE THREAD

**Issue by kevin-george** [PromyLOPh/pianobar#547]
Using pianobar on Arch Linux with pulseaudio
Keep getting the error message

"Unable to open audio file (End of file)"

when trying to play a station. Is there anyway to debug this?
P.S I've been using it for 2 months at least and it worked fine until it stopped today and i did an update today on the Arch.

**Comment by kevin-george** [comment]
Same problem on Mac 10.10.5

**Comment by rkam** [comment]
and 10.11

It comes and goes - It lasts a long time (hours). It has cleared up on its own (only to reoccur).

**Comment by PromyLOPh** [comment]
Looks like you might be running into server-side rate limits. See #301,
#415 and many more.

For network-related issues I recommend Wireshark or tcpdump.

**Comment by rkam** [comment]
yeah, sorry, I meant to say that I was just adding info, not looking for a solution :)  I agree it's probably server-side.

That said, I don't think it's a server-side *rate limit*, because I noticed it after I had gone several days w/o playing and it happened upon playing the first song.

**Comment by kevin-george** [comment]
It was definitely something wrong server-side, the web client and android client refused to work either. Definitely not a bug with pianobar.
