### ISSUE TITLE
Deleting a station crashes pianobar

### ISSUE THREAD

**Issue by lordB8r** [PromyLOPh/pianobar#548]
When I select a station and delete it, pianobar crashes out.

OSX 10.10.5
iTerm2 2.1.4
Pianobar 2014.09.28

i can submit a diagnostic report, but don't have anything else to share.

**Comment by PromyLOPh** [comment]
Works for me.

> i can submit a diagnostic report, but don't have anything else to share.
If that diagnostic report includes a full stack trace, please do.
