### ISSUE TITLE
Scratchy Audio

### ISSUE THREAD

**Issue by KenMacD** [PromyLOPh/pianobar#550]
Hello,

Do you have any instructions on how to improve the audio output? I'm getting artifacts during playback. They almost sound like a bad audio cable, like a short drop-out.

I'm running Arch Linux, using Pulseaudio.

My config has `audio_quality = high`. I tried downloading one of the aac files and playing it with `ffplay`, they play perfectly clear. That seems like it should eliminate the possibility of it being network and typical playback issues.

I also notice that the pulseaudio process uses more CPU when playing a file through `pianobar` vs `ffplay` (5% vs 2.5%). The cpu is not pegged during either though (under 10% total), and I've tried with both `pulseaudio` and `pianobar` at nice level `-19` with no effect.

My `/etc/libao.conf` contains: `default_driver=pulse`.

I'm using the latest master branch.

Is there anything you can suggest?

**Comment by PromyLOPh** [comment]
I don’t know what’s wrong with pulseaudio[1]. If you do, go ahead and
fix it.

[1] https://github.com/PromyLOPh/pianobar/search?q=pulseaudio&type=Issues&utf8=%E2%9C%93

**Comment by KenMacD** [comment]
haha. I was hopeful you did.

I may take a look to see if I can see anything that's done differently that other audio programs. It's a little odd, the only programs I have any audio issues in are this one and Google Hangouts. Playing music from Google Music, vlc, fplay, speakertest, and random games all seem to work.

I'll let you know if I find anything.

**Comment by m4nukum4r** [comment]
Using
`$ PULSE_LATENCY_MSEC=60 pianobar`
fixes the scratchy audio for me, so I'm guessing it's latency issues with pulseaudio. Although beyond that I have no idea.

**Comment by PromyLOPh** [comment]
Yeah, the problem seems to be that pianobar does not buffer decoded
audio. And if pulseaudio is not fed with the next few samples
_immediately_ after ao_play returns the described behavior occurs.
