### ISSUE TITLE
TLS Error

### ISSUE THREAD

**Issue by tealethetoolman** [PromyLOPh/pianobar#554]
Hi guys,

I know there are some older closed bugs that are showing this but the TLS is giving problems.

I have pianobar on my mac (from homebrew)
pianobar on ubuntu (2 different machines) (2013.09.15)

I am getting this error across all of my machines though they were all working 2 days ago.

(i) Login... Network error: TLS fingerprint mismatch.

Also note that I am a pandora one user and I've been using pandora for more than a year and it works fine. My ubuntu machines are all running the old version because the newer version never installs properly (dependency that I have but it says that I don't)

Please look into this if you can. Perhaps they renewed their SSL certificates?

**Comment by PromyLOPh** [comment]
> Perhaps they renewed their SSL certificates?
They did and the new fingerprint is
7F2BFD338D08D6F952D215C0FC8C3C4C1DC1772F. This does not affect the
current git HEAD, since it’s using curl’s certificate validation.

**Comment by tealethetoolman** [comment]
awesome thanks a million! how do you grab their fingerprint?

**Comment by PromyLOPh** [comment]
Add this line to your config file (or replace existing):

tls_fingerprint = 7F2BFD338D08D6F952D215C0FC8C3C4C1DC1772F

**Comment by tealethetoolman** [comment]
I did and it worked. I was asking how do you get their fingerprint when they change it?

**Comment by PromyLOPh** [comment]
Use contrib/tls_fingerprint.sh from the repository. Note that you’ll
need to change the host tuner.pandora.com to internal-tuner.pandora.com.

**Comment by chaseadam** [comment]
I am on HEAD and tried to use the fingerprint config option. Grepping through the code, I only see a reference to this config in an example config file. Did you remove this option when we switched to curl's certificate validation?

Note, I have up to date fedora ca-certs and curl cert check fails. The discussion from Pithos owner pegs why this certificate fails on most systems even using curl: https://github.com/pithos/pithos/issues/251#issuecomment-155240542

        achasen@localhost Downloads]$ curl -vvv https://internal-tuner.pandora.com
        * Rebuilt URL to: https://internal-tuner.pandora.com/
        *   Trying 208.85.40.48...
        * Connected to internal-tuner.pandora.com (208.85.40.48) port 443 (#0)
        * Initializing NSS with certpath: sql:/etc/pki/nssdb
        *   CAfile: /etc/pki/tls/certs/ca-bundle.crt
          CApath: none
        * Server certificate:
        *       subject: CN=internal-tuner.pandora.com,OU=operations,O="Pandora Media, Inc.",L=Oakland,ST=California,C=US
        *       start date: Oct 27 00:00:00 2015 GMT
        *       expire date: Nov 25 23:59:59 2016 GMT
        *       common name: internal-tuner.pandora.com
        *       issuer: CN=VeriSign Class 3 International Server CA - G3,OU=Terms of use at https://www.verisign.com/rpa (c)10,OU=VeriSign Trust Network,O="VeriSign, Inc.",C=US
        * NSS error -8179 (SEC_ERROR_UNKNOWN_ISSUER)
        * Peer's Certificate issuer is not recognized.
        * Closing connection 0
        curl: (60) Peer's Certificate issuer is not recognized.
        More details here: http://curl.haxx.se/docs/sslcerts.html
       
        curl performs SSL certificate verification by default, using a "bundle"
         of Certificate Authority (CA) public keys (CA certs). If the default
         bundle file isn't adequate, you can specify an alternate file
         using the --cacert option.
        If this HTTPS server uses a certificate signed by a CA represented in
         the bundle, the certificate verification probably failed due to a
         problem with the certificate (it might be expired, or the name might
         not match the domain name in the URL).
        If you'd like to turn off curl's verification of the certificate, use
         the -k (or --insecure) option.
        [achasen@localhost Downloads]$ rpm -q ca-certificates
        ca-certificates-2015.2.5-1.0.fc22.noarch
        [achasen@localhost Downloads]$ dnf update ca-certificates
        Error: This command has to be run under the root user.
        [achasen@localhost Downloads]$ sudo dnf update ca-certificates
        [sudo] password for achasen:
        Last metadata expiration check performed 2:38:43 ago on Tue Nov 10 10:10:04 2015.
        Dependencies resolved.
        Nothing to do.
        Complete!
