### ISSUE TITLE
TLS fingerprint configuration and internal-tuner SSL cert

### ISSUE THREAD

**Issue by chaseadam** [PromyLOPh/pianobar#555]
I am on HEAD and tried to use the fingerprint config option. Grepping through the code, I only see a reference to this config in an example config file (recommended solution for older versions per previous issues). Did we remove this option when we switched to curl's certificate validation?

Note, I have up to date fedora ca-certs and curl cert check fails. The discussion from Pithos owner pegs why this certificate fails on most systems even using curl: https://github.com/pithos/pithos/issues/251#issuecomment-155240542

        achasen@localhost Downloads]$ curl -vvv https://internal-tuner.pandora.com
        * Rebuilt URL to: https://internal-tuner.pandora.com/
        *   Trying 208.85.40.48...
        * Connected to internal-tuner.pandora.com (208.85.40.48) port 443 (#0)
        * Initializing NSS with certpath: sql:/etc/pki/nssdb
        *   CAfile: /etc/pki/tls/certs/ca-bundle.crt
          CApath: none
        * Server certificate:
        *       subject: CN=internal-tuner.pandora.com,OU=operations,O="Pandora Media, Inc.",L=Oakland,ST=California,C=US
        *       start date: Oct 27 00:00:00 2015 GMT
        *       expire date: Nov 25 23:59:59 2016 GMT
        *       common name: internal-tuner.pandora.com
        *       issuer: CN=VeriSign Class 3 International Server CA - G3,OU=Terms of use at https://www.verisign.com/rpa (c)10,OU=VeriSign Trust Network,O="VeriSign, Inc.",C=US
        * NSS error -8179 (SEC_ERROR_UNKNOWN_ISSUER)
        * Peer's Certificate issuer is not recognized.
        * Closing connection 0
        curl: (60) Peer's Certificate issuer is not recognized.
        More details here: http://curl.haxx.se/docs/sslcerts.html
       
        curl performs SSL certificate verification by default, using a "bundle"
         of Certificate Authority (CA) public keys (CA certs). If the default
         bundle file isn't adequate, you can specify an alternate file
         using the --cacert option.
        If this HTTPS server uses a certificate signed by a CA represented in
         the bundle, the certificate verification probably failed due to a
         problem with the certificate (it might be expired, or the name might
         not match the domain name in the URL).
        If you'd like to turn off curl's verification of the certificate, use
         the -k (or --insecure) option.
        [achasen@localhost Downloads]$ rpm -q ca-certificates
        ca-certificates-2015.2.5-1.0.fc22.noarch
        [achasen@localhost Downloads]$ dnf update ca-certificates
        Error: This command has to be run under the root user.
        [achasen@localhost Downloads]$ sudo dnf update ca-certificates
        [sudo] password for achasen:
        Last metadata expiration check performed 2:38:43 ago on Tue Nov 10 10:10:04 2015.
        Dependencies resolved.
        Nothing to do.
        Complete!

**Comment by PromyLOPh** [comment]
> Did we remove this option when we switched to curl's certificate
> validation?
Replaced. See commit 61dbc218e747f1b550a2615ffe3065024db29239.

> Note, I have up to date fedora ca-certs and curl cert check fails. The
> discussion from Pithos owner pegs why this certificate fails on most
> systems even using curl:
> https://github.com/pithos/pithos/issues/251#issuecomment-155240542
I’ve seen the discussion. See issue #522 for a solution.

**Comment by chaseadam** [comment]
I did attempt #522, but because the server doesn't return the CA chain, it never hands an issuer which is published at https://www.symantec.com/page.jsp?id=roots. It only hands an intermediate certificate, specifically "VeriSign Class 3 International Server CA - G3". It appears modern browsers include this CA. Github won't allow me to attach the PEM.

**Comment by trrbl** [comment]
I have the same problem on my archlinux

**Comment by PromyLOPh** [comment]
Works for me with this bundle:
https://gist.github.com/cfed4d0b49da8b129dd0

**Comment by trrbl** [comment]
hm. thanks for the gist. works with it

**Comment by PromyLOPh** [comment]
Closing, https://github.com/mcrute/pydora/issues/27#issuecomment-162265368
