### ISSUE TITLE
Unrecognized key tls_fingerprint at /root/.config/pianobar/config

### ISSUE THREAD

**Issue by UltiBots** [PromyLOPh/pianobar#556]
Hi all -

Pianobar runs OK in audio_quality = low BUT fails in audio_quality = high. I get the following...
```
(i) Unrecognized key tls_fingerprint at /root/.config/pianobar/config:66
Welcome to pianobar (2014.09.28-dev)! Press ? for a list of commands.
(i) Login... Network error: Peer certificate cannot be authenticated with given CA certificates
```
My search for "Unrecognized key" in issues came up empty.

My config file has the following:
```
audio_quality = high
rpc_host = internal-tuner.pandora.com
partner_user = pandora one
partner_password = TVCKIBGS9AO9TSYLNNFUML0743LH82D
device = D01
encrypt_password = 2%3WCL*JU$MP]4
decrypt_password = U#IO$RZPAB%VX2
tls_fingerprint = 2D0AFDAFA16F4B5C0A43F3CB1D4752F9535507C0
```
I also tried ```tls_fingerprint = 7F2BFD338D08D6F952D215C0FC8C3C4C1DC1772F```

Thoughts, comments, suggestions...  TIA - Brad

**Comment by PromyLOPh** [comment]
See issue #555 and #522.

**Comment by ski522** [comment]
I followed the above post, but I still get the same error even after downloading the new certs...this just started happening about 2 weeks ago for me.  Look for a recommendation on what next steps might be.

**Comment by PromyLOPh** [comment]
Please post your config file and pianobar version.

**Comment by ski522** [comment]
I just pulled the latest on git...make clean && make install...still no go. 

Welcome to pianobar (2015.11.22-dev)! Press ? for a list of commands.
(i) Login... Network error: Peer certificate cannot be authenticated with given CA certificates

My config

tls_fingerprint = 2D0AFDAFA16F4B5C0A43F3CB1D4752F9535507C0
password = ************
user = ***********
format_nowplaying_song = "%t" by "%a" on "%l"%r%@%s
event_command = /home/bc/.config/pianobar/eventcommand.sh
#audio_quality = high
rpc_host = internal-tuner.pandora.com
partner_user = pandora one
partner_password = TVCKIBGS9AO9TSYLNNFUML0743LH82D
device = D01
encrypt_password = 2%3WCL*JU$MP]4
decrypt_password = U#IO$RZPAB%VX2
ca_bundle = /etc/ssl/certs/ca-certificates.crt

**Comment by PromyLOPh** [comment]
> ca_bundle = /etc/ssl/certs/ca-certificates.crt
Does it work if you put the contents of the gist I posted
(https://gist.github.com/anonymous/cfed4d0b49da8b129dd0) in a separate
file and use that instead of /etc/ssl/…? What is your OS and libcurl
version?

**Comment by ski522** [comment]
Yes that did work!

For reference I'm using this on Raspberry Pi

*curl 7.26.0 (arm-unknown-linux-gnueabihf) libcurl/7.26.0 OpenSSL/1.0.1e zlib/1.2.7 libidn/1.25 libssh2/1.4.2 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap pop3 pop3s rtmp rtsp scp sftp smtp smtps telnet tftp 
Features: Debug GSS-Negotiate IDN IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP*

OS Version

*PRETTY_NAME="Raspbian GNU/Linux 7 (wheezy)"
NAME="Raspbian GNU/Linux"
VERSION_ID="7"
VERSION="7 (wheezy)"
ID=raspbian
ID_LIKE=debian*

**Comment by UltiBots** [comment]
Hi All -

I am up and running again! **BUT** I am not sure why I didn't need...
```
tls_fingerprint = 2D0AFDAFA16F4B5C0A43F3CB1D4752F9535507C0
```
Using PC Engines ALIX board running Voyage Linux.
```
Linux voyage 3.16.7-ckt9-voyage #1 SMP Thu Apr 23 11:10:44 HKT 2015 i586 GNU/Linux
```
On the latest head version
```
root@voyage:~/pianobar# git pull
Already up-to-date.
root@voyage:pianobar
Welcome to pianobar (2015.11.22-dev)! Press ? for a list of commands.
(i) Control fifo at /root/.config/pianobar/ctl opened
(i) Login... Ok.
['artist=\n', 'title=\n', 'album=\n', 'coverArt=\n', 'stationName=\n', 'songStationName=\n', 'pRet=1\n', 'pRetStr=Everything is fine :)\n', 'wRet=0\n', 'wRetStr=No error\n', 'songDuration=0\n', 'songPlayed=0\n', 'rating=0\n', 'detailUrl=\n', 'stationCount=0\n']
(i) Get stations... Ok.
```
I created a new file called ca-cert-pianobar and pasted the contents of https://gist.github.com/anonymous/cfed4d0b49da8b129dd0. Then I referenced it in my config file.
```
user = brad@xxxxx.com
password = xxxxxxx

# Misc
autostart_station = 211321788527784607
event_command = /root/.config/pianobar/pandora.py
fifo = /root/.config/pianobar/ctl

ca_bundle = /root/.config/pianobar/ca-cert-pianobar

# high-quality audio (192k mp3, for Pandora One subscribers only!)
audio_quality = high
rpc_host = internal-tuner.pandora.com
partner_user = pandora one
partner_password = TVCKIBGS9AO9TSYLNNFUML0743LH82D
device = D01
encrypt_password = 2%3WCL*JU$MP]4
decrypt_password = U#IO$RZPAB%VX2
```
Lastly the output of curl -V is:
```
curl 7.38.0 (i586-pc-linux-gnu) libcurl/7.38.0 OpenSSL/1.0.1k zlib/1.2.8 libidn/1.29 libssh2/1.4.3 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API SPNEGO NTLM NTLM_WB SSL libz TLS-SRP
 ```
Thanks ***PromyLOPh*** and all that have contributed to this project.
