### ISSUE TITLE
Network error: TLS handshake failed

### ISSUE THREAD

**Issue by ZevEisenberg** [PromyLOPh/pianobar#557]
```
Welcome to pianobar (2014.09.28)! Press ? for a list of commands.
(i) Control fifo at /Users/zev/.config/pianobar/ctl opened
(i) Login... Network error: TLS handshake failed.
```

Getting this every time I try to start Pianobar on one machine. It works fine on another machine on a different network. They're using the same configuration.

**Comment by PromyLOPh** [comment]
Have you tried compiling the current git master?

**Comment by ZevEisenberg** [comment]
No, but it started working again. No idea what happened. Maybe something was up with my network? I used it all day today and everything was fine, so closing this.
