### ISSUE TITLE
Feature request - I want a CLI command to figure out if pianobar is currently playing.

### ISSUE THREAD

**Issue by sagotsky** [PromyLOPh/pianobar#558]
I have an event that dumps stdin into a file I can inspect to see what's playing.  But I can't tell from that file whether or not pianobar is playing right now.  

Since event's seem to be pianobar's interface of choice, could we have a playerState or something that shows if pianobar is played or paused.  This would also mean adding an event for playing, pausing, stopping, and quitting. Probably a few others.

**Comment by jarussell** [comment]
something like `pgrep pianobar && cat yourfile`?

**Comment by PromyLOPh** [comment]
Events were never meant to do that. If you need better remote control
try pianod instead.

**Comment by sagotsky** [comment]
So no fix?  I'll try something else.  Thanks!
