### ISSUE TITLE
libavutil/frame.h: No such file or directory

### ISSUE THREAD

**Issue by megrimm** [PromyLOPh/pianobar#559]
hello,

when trying to make on the raspberry pi i get the following:   

 CC  src/main.c
    CC  src/player.c
src/player.c:48:29: fatal error: libavutil/frame.h: No such file or directory
compilation terminated.
Makefile:99: recipe for target 'src/player.o' failed
make: *** [src/player.o] Error 1

thanks!

**Comment by ski522** [comment]
*sudo apt-get install libavutil-dev*

You might need to install other dev files too as you try to compile.

**Comment by megrimm** [comment]
yup that was installed:

"libavutil-dev is already the newest version."

that is the only error i have been giving and afaik all dependencies are installed....

hmmmm

**Comment by PromyLOPh** [comment]
Note that you need ffmpeg >= 2.1 or libav >= 10 (see commit
39de1355e8f0565594bac973218d347c1fe02c69).

**Comment by megrimm** [comment]
got it... 
compiled current FFmpeg from github repo (took several hours on rpi)
compiled pianobar and installed
all working

Thanks!

**Comment by bSkwared** [comment]
Hi all,

I am having same problem. I installed ffmpeg from a ppa, but I am still getting the same message megrimm was. When I go to /opt/ffmpeg/include/libavutils/ there is a frame.h. Could this be because I was installing all these libav packages trying to get it to work? I wanted to try and compile this so I could maybe help but at least use the latest version.

**Comment by PromyLOPh** [comment]
Did you adjust the PKG_CONFIG_PATH environment variable to include
/opt/ffmpeg/lib/pkgconfig (or similar)?

**Comment by bSkwared** [comment]
Thank you! I tried setting PKG_CONFIG_PATH to ffmpeg, include, and libavutils, but none of these worked. 

Now, everything compiles correctly, but the linker runs into problems:
`/usr/bin/ld: cannot find -lXv`
It shows that and multiple others with various characters after the -lX.

When I run make with elevated privileges, I get errors like the one in issue [#453](https://github.com/PromyLOPh/pianobar/issues/453). You say wrong libav selected in makefile; is this something else I need to point over to a location in the  ffmpeg directory?

**Comment by bSkwared** [comment]
I do not see any LIBAV variable at the top of MakeFile. Is there some other problem with where I cloned to? Does the code need to be in a specific directory like under src for make to work?

**Comment by PromyLOPh** [comment]
That variable is long gone. Which version are you trying to compile?

**Comment by bSkwared** [comment]
I just forked and cloned this week so it should be the current one. I realized I was trying to link without exporting pkgconfig, but that just changed the error messages to the cannot find ones from my previous comment.

**Comment by PromyLOPh** [comment]
Can you post the commands/environment variables you’re using and the
output of `make V=1` please?

**Comment by Wardevour** [comment]
I'm also trying to compile pianobar on Ubuntu 14.04 with the latest ffmpeg from the mc3man ppa. The linker says I'm missing all kinds of libs and had to install them all with:
```
sudo apt-get install libavutil-dev libavfilter-dev libavformat-dev libsdl2-dev libavcodec-dev libx264-dev libxvidcore-dev libvdpau-dev libva-dev libxcb-shm0-dev libwavpack-dev libvpx-dev libvorbis-dev libogg-dev libvidstab-dev libspeex-dev libopus-dev libopencore-amrnb-dev libopencore-amrwb-dev libmp3lame-dev libfreetype6-dev libfdk-aac-dev libass-dev libbz2-dev libsoxr-dev
```

Does it seem strange that I would need all these?

now I'm getting:
```
/opt/ffmpeg/lib/libavutil.a(hwcontext_vaapi.o): In function `vaapi_device_free':
(.text+0x179c): undefined reference to `XCloseDisplay'
/opt/ffmpeg/lib/libavutil.a(hwcontext_vaapi.o): In function `vaapi_device_create':
(.text+0x1810): undefined reference to `XOpenDisplay'
/opt/ffmpeg/lib/libavutil.a(hwcontext_vaapi.o): In function `vaapi_device_create':
(.text+0x1825): undefined reference to `vaGetDisplay'
/opt/ffmpeg/lib/libavutil.a(hwcontext_vaapi.o): In function `vaapi_device_create':
(.text+0x1839): undefined reference to `XDisplayName'
/opt/ffmpeg/lib/libavutil.a(hwcontext_vaapi.o): In function `vaapi_device_create':
(.text+0x18bf): undefined reference to `vaGetDisplayDRM'
/opt/ffmpeg/lib/libavutil.a(hwcontext_vaapi.o): In function `vaapi_device_create':
(.text+0x18f4): undefined reference to `XDisplayName'
/opt/ffmpeg/lib/libavutil.a(hwcontext_vaapi.o): In function `vaapi_device_create':
(.text+0x1995): undefined reference to `XDisplayName'
/opt/ffmpeg/lib/libavutil.a(hwcontext_vdpau.o): In function `vdpau_device_create':
(.text+0x58e): undefined reference to `XOpenDisplay'
/opt/ffmpeg/lib/libavutil.a(hwcontext_vdpau.o): In function `vdpau_device_create':
(.text+0x5a3): undefined reference to `XDisplayString'
/opt/ffmpeg/lib/libavutil.a(hwcontext_vdpau.o): In function `vdpau_device_create':
(.text+0x5af): undefined reference to `XDefaultScreen'
/opt/ffmpeg/lib/libavutil.a(hwcontext_vdpau.o): In function `vdpau_device_create':
(.text+0x5c1): undefined reference to `vdp_device_create_x11'
/opt/ffmpeg/lib/libavutil.a(hwcontext_vdpau.o): In function `vdpau_device_create':
(.text+0x68b): undefined reference to `XDisplayName'
/opt/ffmpeg/lib/libavutil.a(hwcontext_vdpau.o): In function `vdpau_device_free':
(.text+0x6cc): undefined reference to `XCloseDisplay'
collect2: error: ld returned 1 exit status
make: *** [pianobar] Error 1
```

**Comment by PromyLOPh** [comment]
> Does it seem strange that I would need all these?
Not at all. ffmpeg supports a lot of external codecs.

LDFLAGS seems to be missing a few libraries, including -lX and something
related to VDPAU/VAAPI. Not sure what exactly it is though. If you want
to avoid these dependencies you can build ffmpeg with minimal
dependencies, see https://github.com/PromyLOPh/pianobar/wiki/ffmpeg
