### ISSUE TITLE
Network error: TLS fingerprint mismatch

### ISSUE THREAD

**Issue by ian-kelling** [PromyLOPh/pianobar#560]
I start pianobar and it immediately exits. It just suddenly stopped working.

Welcome to pianobar (2013.09.15-dev)! Press ? for a list of commands.
(i) Login... Network error: TLS fingerprint mismatch.

Also, seems like the exit code should be non-zero.

**Comment by mikeokner** [comment]
Yeah just started seeing this as well.

**Comment by JoshuaRogers** [comment]
Running `brew update && brew upgrade pianobar` solved the problem for me.

**Comment by has207** [comment]
Same here as well

**Comment by mikeokner** [comment]
Updating fixed it for me, too. Shoulda let it finish before I chimed in!

**Comment by ian-kelling** [comment]
Yes, updating fixed it for me too. I figured it might, but it wouldn't hurt to have a bug since a lot of people's distro packages are broken.

**Comment by bradtaniguchi** [comment]
Pianobar build (2013.09.15) 
I manually log into mine and get an error after entering the correct login. Used apt-get update (Ubuntu 14.04 ) and apt-get upgrade pianobar. Says its the newest version, still get the same Network Error as mentioned.
Haven't had this problem before. Any ideas of what I can do as updating normally didn't work?

**Comment by shaggytwodope** [comment]
There was a recent gnutls update  if I remember right, Might be the case of all current builds needing to be re-compiled against the new version.

**Comment by ian-kelling** [comment]
@bradtaniguchi, I updated to the git version. You probably need to do that too.

**Comment by PromyLOPh** [comment]
For those who can upgrade to a newer version, please do so, because
2013.09.15 is _two_years_old_.

Everyone else: Set

tls_fingerprint = 13CC51AC0C31CD96C55015C76914360F7AC41A00

in your config file.

**Comment by nulldigit90** [comment]
pianobar in the Arch official packages is out of date. After trying to update, it's set at 2014.09.28. The fix @PromyLOPh provided works.

**Comment by JoshuaJB** [comment]
Same situation as @nulldigit90 with pianobar on Ubuntu.

**Comment by Stratus3D** [comment]
Setting tls_fingerprint in `~/.config/pianobar/config` fixed this issue for me:

    tls_fingerprint = 13CC51AC0C31CD96C55015C76914360F7AC41A00

I am on Ubuntu Gnome 14.04.

**Comment by MarkMichaelis** [comment]
On windows I tried updating Pianobar.cfg with the same setting but I still get the same error.  Suggestions?

**Comment by bradtaniguchi** [comment]
@PromyLOPh fix got things working back for me, thanks!

**Comment by gwtnz** [comment]
Pandora updated their certificate for https://tuner.pandora.com . The new one will run through to ~12/24/2016 according to the info my browser tells me. Then you'll need to update again similar to the note above from PromyLOPh, but the value will be different (you can get the new one from the browser info then)

**Comment by Stratus3D** [comment]
@gwtnz Can you share with us how to find out what the TLS fingerprint is? It will save me time when the next change occurs if I know how to find the new value.

**Comment by gwtnz** [comment]
@Stratus3D asically I used a web browser to view the site's certificate. In Firefox (should be similar steps in other browsers) I browsed to https://tuner.pandora.com (based on the info in the man page for where pianobar connects). I get a "403 Forbidden" message on the web page but that's ok. In the address bar I click on the locked padlock icon and choose "More information". In the dialog that comes up choose "View certificate" and you should see the fingerprint at the bottom of the new dialog. It will look like:

SHA1 Fingerprint    13:CC:51:AC:0C:31:CD:96:C5:50:15:C7:69:14:36:0F:7A:C4:1A:00

copy the 13:....:00 text.

In Linux and probably Mac open a shell and type:

  cat | tr -d ':'

and paste the text. You should then get the resulting fingerprint text without ':'s in it for pianobar.

In windows, paste it into Notepad and remove the ':' from the text. (I haven't confirmed this works in windows :) )

**Comment by sarana1** [comment]
@MarkMichaelis uh, Mark, being the moron that I am, I changed the fingerprint, then did not uncomment the line (in Windows) Perhaps uncommenting the line? :)

**Comment by Stratus3D** [comment]
Thanks @gwtnz !

**Comment by PromyLOPh** [comment]
> @gwtnz Can you share with us how to find out what the TLS fingerprint is? It will save me time when the next change occurs if I know how to find the new value.
There’s also a script for that: contrib/tls_fingerprint.sh

**Comment by Eucrates** [comment]
Curses.  I'm not sure which doc worked for me because after trying several I finally double checked my config file again and was missing a digit in my new told fingerprint, which is the first thing I tried to do.

But there was a lot to update / upgrade so that might have helped too.

**Comment by MarkMichaelis** [comment]
Can anyone confirm that the suggested fixes work on Windows for them? It is still not Working on windows for me.
(@sarana1 my entry is not commented out.)

**Comment by PromyLOPh** [comment]
For the windows client head over to
https://github.com/thedmd/pianobar-windows

**Comment by sarana1** [comment]
@MarkMichaelis it worked for me, but nothing else is commented out below the "Uncomment these if you're using GlobalPandora.com" line. On Windows XP. This is on the 2013 version of pianobar for windows, but it looks like there is a more recent one just put up possibly in response to this which I have not tried yet. Just going to thank everyone responsible for this program while I'm here.. I HATE the browser version of Pandora.

**Comment by ijustlovemath** [comment]
Using 2013.05.19-win32, as it's the most recent one (that I know of) without that horrible LAVA backend. All the newer versions I've tried don't respond to keyboard presses, freeze often etc., and it's a simple enough program that I'm okay using an older one. Setting

tls_fingerprint = 13CC51AC0C31CD96C55015C76914360F7AC41A00

in my config file fixed this issue.

**Comment by thedmd** [comment]
@MarkMichaelis, @ijustlovemath 
Please give a try to latest release on Windows 2015.12.10. tls_fingerprint is no longer relevant there. If your Windows accept new certificate also pianobar will. HTTP backend was implemented using WinHTTP, so such problems are offloaded from player itself.

**Comment by diethnis** [comment]
Can someone add something to have pianobar automatically get the TLS fingerprint from Pandora? This here https://gist.github.com/r35krag0th/4173333 does it in bash/openssh. Not familiar enough in C myself to do it.

**Comment by PromyLOPh** [comment]
That would defeat the purpose, don’t you think, @diethnis ?

**Comment by jasonkuehl** [comment]
Fix for myself anyways 

sudo su -
cd /usr/share/doc/pianobar/contrib/
chmod 755 tls_fingerprint.sh
./tls_fingerprint.sh
(Grab fingerprint)
(Exit root)

nano/vim /home/invader/.config/pianobar/config
(Add This)
tls_fingerprint = fingerprint
(Save and Exit)
Run pianobar.
