### ISSUE TITLE
QuickMix segmentation fault error

### ISSUE THREAD

**Issue by OvalPiston** [PromyLOPh/pianobar#561]
So I've been running pianobar for a few months on my Pi2, now when I choose the Quickmix option, on when switching to the fourth song, every once in a while, it will show this message:

QuickMix error: "Receiving new playlist...Error: access denied. Try again later."

Pressing $ give this error:
Segmentation fault

And then Pianobar goes back to the prompt. Sometimes restarting a new terminal session works. But sometimes even rebooting the Pi2 doesn't even help.

**Comment by PromyLOPh** [comment]
Which version are you running?

**Comment by OvalPiston** [comment]
Version (2013.09.15)

**Comment by OvalPiston** [comment]
Just wondering if it could be a bad station or an issue with the userid? A few stations listed aren't in Pandora, and with one of the stations, Pandora said "We couldnt' find any songs"

**Comment by PromyLOPh** [comment]
Can you try the latest release, 2015.11.22, please?

**Comment by OvalPiston** [comment]
Where do I download it?

**Comment by PromyLOPh** [comment]
If your distribution’s package manager does not have a more recent
version you’ll have to build it from source. Binary releases are not
available here.

**Comment by OvalPiston** [comment]
That's what I mean, where do I download the source so I can get it compile it.

**Comment by PromyLOPh** [comment]
https://6xq.net/pianobar/
