### ISSUE TITLE
Add command to show station URL

### ISSUE THREAD

**Issue by specious** [PromyLOPh/pianobar#563]
A command to print the currently playing station's URL (for example: http://www.pandora.com/station/play/397417301128675034) could be very handy.  A station can be shared that way with anybody, even if they don't have a Pandora account.

Perhaps `U` (since lower case `u` is already taken).

**Comment by PromyLOPh** [comment]
You could set

format_nowplaying_station = Station %n (http://www.pandora.com/station/play/%i)

in your config file, which then shows the URL after station selection.
(%i is replaced with the station id, %n with its name)

**Comment by specious** [comment]
Sweet, that works! :smile_cat: 

![pianobar-showing-station-url](https://cloud.githubusercontent.com/assets/451178/11799094/0a12efe8-a29f-11e5-847f-06cbbd3ece21.png)
