### ISSUE TITLE
SIGINT does not kill pianobar process

### ISSUE THREAD

**Issue by mumrah** [PromyLOPh/pianobar#564]
Since the last update, I cannot ctrl+c the pianobar process. I have to drop it to the background and explicitly `kill -TERM` it.

Version: 2015.11.22
OS: Mac OS X 10.11.1

**Comment by moimikey** [comment]
noticed the same. but i also started to instead do `q` so it saves my last listened station because of the clean exit.

**Comment by PromyLOPh** [comment]
That’s intended behavior, see commit
436a1d4012553a2f33d0e3a5180b3b5ae0378bdd and ChangeLog.

**Comment by mumrah** [comment]
ok, interesting. I'll use `q` from now on, but I will say that this is strange from a usability perspective. i would think that ctrl+c is pretty widely recognized as a way to terminate a command line program.

**Comment by PromyLOPh** [comment]
Well, ^C generates SIGINT, which is defined as “interrupt signal”. It
defaults to program termination though and most programs won’t override
that.

I doubt there’s anything I can do to make it more obvious what it does,
can I?

**Comment by nviennot** [comment]
how about ctrl+c twice -> terminate pianobar?

**Comment by jbain** [comment]
Can you elaborate on "^C now works as expected" ? Personally, I feel it works counter to what's expected with a CLI application. What's the practical reason for interrupting API requests, input prompts, and audio streaming in this way? What bug was this fixing or what feature was it to support?

In my frustration of mashing ^C and having it NOT quit I've been getting odd results and the application often becomes completely unresponsive, while other times it simply behaves oddly for a few moments and then resumes operation.

I often have issues where after resuming from sleep (on OSX) pianobar is unresponsive and previously I would ^C to close it and restart it, now I have to close the terminal or open a second to send a SIGTERM

**Comment by PromyLOPh** [comment]
> how about ctrl+c twice -> terminate pianobar?
I like this idea.

> Can you elaborate on "^C now works as expected" ? Personally, I feel
> it works counter to what's expected with a CLI application.
The ncurses applications (i.e. interactive) I tested either ignore
SIGINT or handle it in a similar fashion. (pianobar does not use
ncurses, but I’d say it is “interactive”.)

> What's the practical reason for interrupting API requests, input
> prompts, and audio streaming in this way? What bug was this fixing or
> what feature was it to support?
As the commit message states “Timeouts have been removed.” ^C is the
replacement. As far as I remember there was a problem with timeouts
here:
https://github.com/PromyLOPh/pianobar/issues/478#issuecomment-122698637

> I often have issues where after resuming from sleep (on OSX) pianobar
> is unresponsive and previously I would ^C to close it and restart it,
> now I have to close the terminal or open a second to send a SIGTERM
Can you compile pianobar and libao with debug symbols, attach a debugger
after resuming and retrieve a backtrace of all threads please
(https://wiki.ubuntu.com/Backtrace#Generation)? Make sure you remove
password before posting it anywhere.

**Comment by isaacl** [comment]
As I mentioned in my bug, I find this behavior very counterintuitive.  Especially since it used to work and suddenly does not.

When a user hits Ctrl-C, they are trying to quit the app. I don't see a compelling reason why pianobar should interpret this differently, even if some ncurses apps do so.

I suggest using different shortcut for the interrupt API call feature, or trap SIGUSR1 if you need it via a signal. Or, at the very least, print a message on single ctrl-C and quit if Ctrl-C is hit twice.

**Comment by BrandonZacharie** [comment]
PromyLOPh is right in that, technically, pianobar now does what is should do when receiving SIGINT. It may seem unfamiliar but it's actually common for interactive apps (i.e. REPLs... e.g. pianobar) to trap SIGINT for the same purpose. Node.js, Python, psql, and many others all do this. Node.js, however, allows the ^C twice thing to make it easier for the masses.

+1 on the ^C twice option
