### ISSUE TITLE
AudioComponent.h -- Deprecation WARNING

### ISSUE THREAD

**Issue by nikisix** [PromyLOPh/pianobar#565]
Since upgrading OSX from Yosimite to El Capitan, I get the following warning whenever a song plays. 

015-12-15 10:52:17.189 pianobar[89232:768420] 10:52:17.189 WARNING:  140: This application, or a library it uses, is using the deprecated Carbon Component Manager for hosting Audio Units. Support for this will be removed in a future release. Also, this makes the host incompatible with version 3 audio units. Please transition to the API's in AudioComponent.h.

**Comment by PromyLOPh** [comment]
Please use the search before opening a new issue. This is the *seventh*
issue.

https://github.com/PromyLOPh/pianobar/search?q=Carbon+Component+Manager&type=Issues&utf8=%E2%9C%93
