### ISSUE TITLE
Cannot play station, every song emits "/!\ create_filter abuffer (Invalid argument)"

### ISSUE THREAD

**Issue by Lotharyx** [PromyLOPh/pianobar#566]
This issue seems to occur independent of what station I select.
After the playlist is retrieved, each song does not play, instead emitting a series of messages:
    [...]
    |>  "Ghosts 'n' Stuff" by "Deadmau5" on "5 Years Of Mau5"    
    [mp3 @ 0x73b00480] max_analyze_duration 5000000 reached
    [abuffer @ 0x73b12ce0] Invalid channel layout 0x0.
    /!\ create_filter abuffer (Invalid argument)
    |>  "Gold Dust (Flux Pavilion Remix)" by "DJ Fresh (UK)" on "UKF Dubstep 2010" 
    [mp3 @ 0x73b00480] max_analyze_duration 5000000 reached
    [abuffer @ 0x73b3f7e0] Invalid channel layout 0x0.
    /!\ create_filter abuffer (Invalid argument)
    [...]

This continues without end until I exit pianobar.

Other resources regarding the "Invalid channel layout" message seem to suggest it's an issue with the stream, but every single one?...

Version: pianobar (2014.06.08) as installed from Raspbian Jessie distribution (armhf)
Platform: Raspberry Pi 2 B+

Thanks!

**Comment by PromyLOPh** [comment]
You’re probably encountering issue #491 fixed by commit
d888d0ac2aeb233deeb70aaca196453f8195e433. Please update to release
2015.11.22.
