### ISSUE TITLE
Detect the Current Volume Level?

### ISSUE THREAD

**Issue by reidcooper** [PromyLOPh/pianobar#568]
Is there a way to detect the current volume level so I can set that as default?

**Comment by PromyLOPh** [comment]
pianobar saves the current volume to ~/.config/pianobar/state on exit.

**Comment by ammongit** [comment]
I feel like there should be an option to display the volume when a song is playing. Do you think that's a worthwhile feature?

**Comment by PromyLOPh** [comment]
The patch below adds a config option ``format_time``, whose default is
``%r/%t``. A statusline with volume would be something like
``%r/%t (%vdB)``. I don’t want to show it by default, because the
absolute value does not matter imho.

https://gist.github.com/anonymous/b98f367211959ac3c189
