### ISSUE TITLE
Export List of Played Songs

### ISSUE THREAD

**Issue by reidcooper** [PromyLOPh/pianobar#569]
Is there a way to export the recent played list of songs? Or if it doesn't exist, could there be a feature added to allow this?

Thanks

**Comment by lordB8r** [comment]
Why not use Last.FM Scrobbler?

On Tue, Jan 19, 2016 at 11:15 AM, Reid Cooper <notifications@github.com>
wrote:

> Is there a way to export the recent played list of songs? Or if it doesn't
> exist, could there be a feature added to allow this?
>
> Thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PromyLOPh/pianobar/issues/569>.
>



-- 
JP Bader
Principal
Next Health Choice, LLC
jp@nexthealthchoice.com | 312.614.1267

**Comment by cburmeister** [comment]
@reidcooper if you didn't want to use last.fm (like me) you can use the `songfinish` event to log to a file.

**Comment by reidcooper** [comment]
@cburmeister where do you learn how to use songfinish? I have never heard of it

**Comment by cburmeister** [comment]
@reidcooper this is from the `man` page:

```
EVENTCMD
       pianobar can report certain "events" to an external application (see
       CONFIGURATION ). This application is started with the event name  as
       it's  first  argument. More information like error code and descrip-
       tion, was well as song information related to the current event,  is
       supplied through stdin.

       Currently  supported  events are: artistbookmark, songban, songbook-
       mark,  songexplain,  songfinish,  songlove,   songmove,   songshelf,
       songstart,  stationaddgenre, stationaddmusic, stationaddshared, sta-
       tioncreate, stationdelete,  stationdeleteartistseed,  stationdelete-
       feedback,   stationdeletesongseed,  stationfetchinfo,  stationfetch-
       playlist,  stationfetchgenre  stationquickmixtoggle,  stationrename,
       userlogin, usergetstations

       An  example  script can be found in the contrib/ directory of piano-
       bar's source distribution.
```

First make sure a script similar to [this](https://github.com/cburmeister/dotfiles/blob/master/.config/pianobar/eventcmd.sh) is saved and executable.

Then add this line to your config:
```
event_command = ~/.config/pianobar/eventcmd.sh
```
