### ISSUE TITLE
Provide a way to disable silent rules

### ISSUE THREAD

**Issue by ryandesign** [PromyLOPh/pianobar#571]
Your Makefile builds with silent rules: it displays lines like:

```
    CC  src/main.c
    CC  src/settings.c
```

Projects that use autoconf provide a `--disable-silent-rules` flag to the `./configure` script that can be used to disable that, and instead display the actual commands that were run.

Could you provide a way to do that in your Makefile? Other projects that don't have a configure script often use the Makefile variable `V` to define whether to build verbosely (`V=1`) or silently (`V=0`, equivalent to what you're doing now).

**Comment by PromyLOPh** [comment]
Does it work as expected with this patch?
https://gist.github.com/bbec1c8e0782602d2d5a
