### ISSUE TITLE
Optional volume-offset config item?

### ISSUE THREAD

**Issue by glyndon** [PromyLOPh/pianobar#573]
Would you consider implementing a config-file item that applies a constant offset (e.g. 'volumeoffset=n') to the volume level?

Why?
On a Raspberry Pi, there's no alsamixer item for PCM, so (at least on mine) audio sources at 0db sometimes audibly 'clip' inside the software (maybe the mixer). Turning down the main level doesn't alleviate the clipping (just makes it quieter) so I know it's not happening in the amplifier. Turning pianobar down about 10 notches, then raising the main volume in alsamixer to restore the proper output level does solve the problem.

As a workaround, I've been applying a local patch to the code every time I compile.
Line 658 in ui_act.c, I change to: 
app->settings.volume = -10;
and could be:
app->settings.volume = 0 + volumeoffset;

If there was a config line then I could use canonical code and avoid risk of clipping.

**Comment by PromyLOPh** [comment]
This seems to be a rather obscure problem, related to your hardware or
configuration. Adding that option would be like 10 LoC, but finding the
root cause of the problem seems the better alternative to me.

Which RPi model and linux distribution (Raspbian?) are you using?

**Comment by glyndon** [comment]
It's a Model B (~2012-13). Always the latest Raspbian.
I agree about finding root cause, and your question reminds me - I've been
using the workaround for so long I've not attempted to reproduce the
problem for at least a year. Maybe with the new version of libav, etc, it's
cured.
I'll do that test and advise.

On Mon, Feb 1, 2016 at 5:03 AM, PromyLOPh <notifications@github.com> wrote:

> This seems to be a rather obscure problem, related to your hardware or
> configuration. Adding that option would be like 10 LoC, but finding the
> root cause of the problem seems the better alternative to me.
>
> Which RPi model and linux distribution (Raspbian?) are you using?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PromyLOPh/pianobar/issues/573#issuecomment-177887033>.
>



-- 
   Gary Dobbins

**Comment by glyndon** [comment]
Seems to no longer be a problem, so I'd say this is solved.

Perhaps it was due the self-compiled version of libav I had to use many months ago (when Raspbian's version was too old).
