### ISSUE TITLE
Add help section/docs section

### ISSUE THREAD

**Issue by videofindersTV** [PromyLOPh/pianobar#576]
This would greatly reduce the amount of stress that new users have to go through and would be extremely convenient for new users.

**Comment by PromyLOPh** [comment]
What exactly do you propose? Add what? And where?

**Comment by videofindersTV** [comment]
I guess I worded my post a bit weird.
You should add documentation to the Wiki for the convenience of the user, if unable to hit the "?" mark at the startup of the program. (I certainly can't!)

**Comment by PromyLOPh** [comment]
The wiki should be editable by everyone. Go ahead and add the
information you feel is missing.

Help (by pressing ‘?’) becomes available once you logged in.
