### ISSUE TITLE
Repeated console error: "skipping 0 bytes of junk" 

### ISSUE THREAD

**Issue by pwenzel** [PromyLOPh/pianobar#577]
Given that this has no affect on the audio output, this is probably low priority. However I thought I'd file it in case it helped any other Pianobar developers/users.

My instance of Pianobar is printing quite a bit of noise in the terminal window when I set `audio_quality = high` in `pianobar/config`. Attached to every song is an error like `[mp3 @ 0x7fb8e3021000] Skipping 0 bytes of junk at 626.`, and occasionally `invalid new backstep -1`.

<img width="1438" alt="pianobar - skipping 0 bytes of junk - screen shot 2016-02-18 at 11 43 53 am" src="https://cloud.githubusercontent.com/assets/187949/13156688/65ce7c3e-d649-11e5-8e1a-0d046c0c5c65.png">

Under the hood, this appears to be FFmpeg printing the error message. 

Audio quality still sounds great, but I sure wouldn't mind muting these warning messages from FFMPEG, if anyone knows how.

I installed the latest version of FFmpeg and Pianobar using Homebrew on OSX Yosemite 10.10.5 (14F1509). Also am a paid Pandora subscriber.

For debugging purposes:

###### Pianobar Output

```
⋊> ~ pianobar                                                                                                                                               10:17:30
Welcome to pianobar (2015.11.22)! Press ? for a list of commands.
(i) Login... Ok.
(i) Get stations... Ok.
|>  Station "Madlib & Madvillain Radio" (2175953835283062911)
(i) Receiving new playlist... Ok.
|>  "Bullshittin' (Remix Instrumental)" by "N'Dea Davenport" on "Jay Deelicious 95-98: The Delicious Vinyl Years"
[mp3 @ 0x7fa8e2803400] Skipping 0 bytes of junk at 626.
|>  "Monkey Suite (Instrumental)" by "Madlib & Madvillain" on " Chrome Children Instrumentals, Vol. 1 & 2"
[mp3 @ 0x7fa8e2803400] Skipping 0 bytes of junk at 626.
|>  "Dftf (Instrumental)" by "Illa J" on "Yancey Boys (Instrumentals)"
[mp3 @ 0x7fa8e1808000] Skipping 0 bytes of junk at 626.
|>  "Climax (Instrumental)" by "Slum Village" on "Fantastic Vol 2 Instrumentals Pt. 1 Digi-LP"
[mp3 @ 0x7fa8e4805000] Skipping 0 bytes of junk at 626.
(i) Receiving new playlist... Ok.
|>  "Beach Dr." by "Oddisee" on "Rock Creek Park" <3
[mp3 @ 0x7fa8e2011600] Skipping 0 bytes of junk at 626.
|>  "Voyage" by "Blue In Green" on "The Break Of Dawn"
[mp3 @ 0x7fa8e2011600] Skipping 0 bytes of junk at 626.
|>  "Fomalhaut" by "Shin-Ski" on "Planetarium"
[mp3 @ 0x7fa8e1818000] Skipping 0 bytes of junk at 626.
|>  "Check The Blueprints (Instrumental)" by "Kero One" on "Windmills Of The Soul Instrumentals"
[mp3 @ 0x7fa8e2801c00] Skipping 0 bytes of junk at 626.
(i) Receiving new playlist... Ok.
|>  "Smooth Sailing" by "Pete Rock" on "Petestrumentals"
[mp3 @ 0x7fa8e100da00] Skipping 0 bytes of junk at 626.
|>  "High John (Instrumental)" by "MF Doom" on "Metal Fingers Presents... Special Herbs 7,8"
[mp3 @ 0x7fa8e102b600] Skipping 0 bytes of junk at 626.
|>  "Tear Loose" by "Bugseed" on "Bohemian Beatnik LP"
[mp3 @ 0x7fa8e1811800] Skipping 0 bytes of junk at 626.
|>  "Ny Minute" by "1988" on "Music2Escape2"
[mp3 @ 0x7fa8e2015800] Skipping 0 bytes of junk at 626.
(i) Receiving new playlist... Ok.
|>  "Get Dis Money (Instrumental)" by "Slum Village" on "Fantastic Vol. 2.10 "
[mp3 @ 0x7fa8e2011000] Skipping 0 bytes of junk at 626.
|>  "Fancy Clown (Instrumental)" by "Madvillain" on "Madvillainy (Instrumentals)"
[mp3 @ 0x7fa8e1801000] Skipping 0 bytes of junk at 626.
|>  "Black Snake Root (Instrumental)" by "MF Doom" on "Special Herbs: The Box Set Vol.0-9"
[mp3 @ 0x7fa8e1031c00] Skipping 0 bytes of junk at 626.
|>  "Sumthin'" by "Gramatik" on "Street Bangerz Vol. 1"
[mp3 @ 0x7fa8e2802800] Skipping 0 bytes of junk at 626.
(i) Receiving new playlist... Ok.
|>  "I Wonder Why" by "Ayatollah" on "Now Playing"
[mp3 @ 0x7fa8e2800e00] Skipping 0 bytes of junk at 626.
|>  "U Can Belive It (Instrumental)" by "Playaz Circle" on "U Can Belive It (Cd Single)"
[mp3 @ 0x7fa8e2001a00] Skipping 0 bytes of junk at 626.
|>  "Musical Journey (Instrumental)" by "Kero One" on "Windmills Of The Soul Instrumentals"
[mp3 @ 0x7fa8e1808000] Skipping 0 bytes of junk at 626.
|>  "Monkey Bars" by "B.Durazzo" on "Beats Vol. 1"
[mp3 @ 0x7fa8e2001a00] Skipping 0 bytes of junk at 626.
[mp3 @ 0x7fa8e1035200] invalid new updatestep -1
(i) Receiving new playlist... Ok.
|>  "Transit" by "Colossus" on "Mushroom Jazz 6 Unmixed Exclusives" <3
[mp3 @ 0x7fa8e2801c00] Skipping 0 bytes of junk at 626.
#   -02:22/04:32
```

###### FFmpeg Details

```
ffmpeg version 2.8.6 Copyright (c) 2000-2016 the FFmpeg developers
  built with Apple LLVM version 7.0.2 (clang-700.1.81)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/2.8.6 --enable-shared --enable-pthreads --enable-gpl --enable-version3 --enable-hardcoded-tables --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-opencl --enable-libx264 --enable-libmp3lame --enable-libvo-aacenc --enable-libxvid --enable-libfaac --enable-nonfree --enable-vda
  libavutil      54. 31.100 / 54. 31.100
  libavcodec     56. 60.100 / 56. 60.100
  libavformat    56. 40.101 / 56. 40.101
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 40.101 /  5. 40.101
  libavresample   2.  1.  0 /  2.  1.  0
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.101 /  1.  2.101
  libpostproc    53.  3.100 / 53.  3.100
Hyper fast Audio and Video encoder
```

###### Pianobar Audio Quality Config

```
# high-quality audio (192k mp3, for Pandora One subscribers only!)
audio_quality = high
rpc_host = internal-tuner.pandora.com
partner_user = pandora one
partner_password = TVCKIBGS9AO9TSYLNNFUML0743LH82D
device = D01
encrypt_password = 2%3WCL*JU$MP]4
decrypt_password = U#IO$RZPAB%VX2
```

**Comment by pwenzel** [comment]
Oops, I just read the wiki and found the FFMPEG notes requiring `--enable-demuxer=mp3 --enable-decoder=mp3`. I'll try that first.

**Comment by t-8ch** [comment]
FYI: this will be fixed in the next release of ffmpeg (3.1 or something): https://github.com/FFmpeg/FFmpeg/commit/8a90e0fd21f77e81abc1b5abab0eda05cc89f59b

**Comment by rdj** [comment]
Yay! If this and the deprecated API errors annoy you, you can always just ignore stderr: `pianobar 2>/dev/null`

**Comment by PromyLOPh** [comment]
> […] and the deprecated API errors annoy you […]
These must be new. Do you have an example?

**Comment by rdj** [comment]
Just #529 — which hasn't percolated into an actual libao release yet, so I'm still working around it.

**Comment by PromyLOPh** [comment]
> Just #529 — which hasn't percolated into an actual libao release yet, so I'm still working around it.
Oh right. I totally forgot about that one.

**Comment by jre** [comment]
Would it make sense to crank up the libavutil logging level to reduce this sort of spam in general? I've been building pianobar with the following patch for a year or two as running it with 2>/dev/null hides errors from my event_ommand script.

http://elsasser.org/misc/pianobar-logging.diff

**Comment by PromyLOPh** [comment]
> Would it make sense to crank up the libavutil logging level to reduce
> this sort of spam in general?
Yes, but I’m still seeing the following messages, even with your patch
applied:

--- snip ---
[aac @ 0x7fbf54005760] decode_band_types: Input buffer exhausted before END element found
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7fbf540008c0] stream 0, offset 0x46923: partial file
[aac @ 0x7fbf540a2cc0] element type mismatch 1 != 0
[aac @ 0x7fbf540a2cc0] element type mismatch 1 != 0
[aac @ 0x7fbf540a2cc0] element type mismatch 1 != 0
--- snap ---

I’ll probably use AV_LOG_FATAL instead of _ERROR to get rid of those.
