### ISSUE TITLE
Network error: Couldn't connect to server

### ISSUE THREAD

**Issue by chrisidefix** [PromyLOPh/pianobar#578]
As of today, I can no longer login to pandora using `pianobar`. It worked all through this morning. I started using the fifo option (`~/.config/pianobar/ctl`) earlier and played around with it for a while, at the same time restarted `pianobar` a bunch of times. Long story short, I can now no longer login. After entering `Email` & `Password`, I only see `(i) Login ...` while nothing is happening:

```
Welcome to pianobar (2015.11.22)! Press ? for a list of commands.
(i) Control fifo at ~/.config/pianobar/ctl opened
[?] Email: 
[?] Password: 
(i) Login... 
```

Eventually, I press `Ctrl-C` twice and get this output:

```
(i) Login... Network error: Couldn't connect to server
```

I can still use pandora through the mobile app for example. I also do have internet access, otherwise I couldn't exactly post here. I am not sure if I can get debug output at that stage.

I also deleted the fifo file and config directory, but that didn't help either :disappointed:

**Comment by PromyLOPh** [comment]
Works for me. Temporary issue?

**Comment by chrisidefix** [comment]
Don't think so - I've been trying repeatedly for the last 10 hours. I can still connect to Pandora (from the same machine as well as other machines in the same network). I can use mobile clients and the pandora website just fine. Any chance I could launch pianobar into a debug mode somehow?

**Comment by chrisidefix** [comment]
My bad, after system reboot `pianobar` works just fine again. Seems like something was blocking that process from establishing connections. Thanks for the immediate response!
