### ISSUE TITLE
Documentation regarding REMOTE CONTROL

### ISSUE THREAD

**Issue by chrisidefix** [PromyLOPh/pianobar#579]
I believe this line (and the other examples) in the `man` page regarding REMOTE CONTROL is a bit misleading:

```
echo -n 'n' > ~/.config/pianobar/ctl
```

What actually happened on my machine when calling this, is a `ban` of the current song, followed by `next` to play the next song. Maybe it's enough to call:

```
echo n > ~/.config/pianobar/ctl
```

**Comment by PromyLOPh** [comment]
Is the echo you’re using shell-builtin or something obscure? GNU
coreutils’ echo and (as far as I see) FreeBSD’s echo both accept -n.

**Comment by chrisidefix** [comment]
Looks like this issue was specific to how I called echo (through subprocess from a python script) and generally it's alright.
