### ISSUE TITLE
Several user interactions require ^C and a repeat in order to work

### ISSUE THREAD

**Issue by ijustlovemath** [PromyLOPh/pianobar#580]
I'm running 2015.11.22-dev. I've notice that when interacting with pianobar, say to "love" or "ban" a song, I need to press the required key, press ^C, then press the key again in order for it to work. Otherwise it just hangs and prevents the application from doing anything. Not sure where to start on helping debug this, but can provide a stack trace if need be.

**Comment by PromyLOPh** [comment]
Does that happen for every action involving Pandora’s API (love, ban,
search, create/delete station, …)? Have you had a look at the network
traffic generated by pianobar?

**Comment by ijustlovemath** [comment]
I believe just love/ban/tired so far. What should I be looking for in the
network traffic?

**Comment by PromyLOPh** [comment]
If there’s a request sent at all, whether Pandora responds or not.

**Comment by ijustlovemath** [comment]
Ok I'll run Wireshark and see if I can replicate.

**Comment by isaacwhanson** [comment]
I am having the same issue on two of three computers.  Must hit "+", then ^C, then "+"  a second time.  Hangs on "(i) Loving song... "

**Comment by PromyLOPh** [comment]
Please provide more information as requested above. Thanks.

**Comment by isaacwhanson** [comment]
[pianobar_tcpdump.txt](https://github.com/PromyLOPh/pianobar/files/450012/pianobar_tcpdump.txt)

here is a tcpdump (my hostname changed to example.com). is the client failing to ACK 1 ?

**Comment by PromyLOPh** [comment]
> here is a tcpdump (my hostname changed to example.com). is the client failing to ACK 1 ?
If that was the case we’d see retransmissions, but as far as I can tell
there are none. Can you generate a backtrace *before* pressing ^C?
Instructions are here: https://wiki.ubuntu.com/Backtrace#Generation –
please remove your username/password before posting it in public.
Debugging symbols must be enabled. Either install the *-dbg packet of
your distribution or compile with `make CFLAGS="-ggdb"`.

**Comment by scottidler** [comment]
[gdb-pianobar.txt](https://github.com/PromyLOPh/pianobar/files/714812/gdb-pianobar.txt)
[gdb-pianobar-copied.txt](https://github.com/PromyLOPh/pianobar/files/714813/gdb-pianobar-copied.txt)

I followed the instructions above to the best of my ability.  I pressed t (tired) it printed the text but the song kept playing.  This is exactly the behaviour expected, however to fully demonstrate it the next step is to press Ctrl-C and then the command, t again.  However, Ctrl-C kills the running program.  I have included the filed that was "tee"d to as well as the output from my shell which had more than what the file did.  I called this file, -copied above.  Please let me know if there is something more I can do to help troubleshoot this issue.

**Comment by PromyLOPh** [comment]
Oh, wait. gdb intercepts SIGINT and pianobar never receives it. Can you
execute `handle SIGINT nostop noprint pass` inside gdb before `run` and
try again? Also, you’re missing debug symbols (see above).
