### ISSUE TITLE
libavutil/frame.h file missing

### ISSUE THREAD

**Issue by CalebDW** [PromyLOPh/pianobar#582]
I've tried to compile this on two different laptops with Ubuntu 14.04 on them and am currently unable to.
I get a fatal error about there not being a libavutil/frame.h file. Here/s the output of "make" http://paste.ubuntu.com/15342998/
I have installed everything having to do with libavutil and I can't find a package that includes the frame header.

**Comment by PromyLOPh** [comment]
Support for libav 9 has been dropped with commit
39de1355e8f0565594bac973218d347c1fe02c69. I’m not sure why I did not use
#ifdefs there.

**Comment by dr-strangelove9** [comment]
I had the exact same problem about 2 weeks ago. Just go ahead and download
and compile a newer version of libav, I think mine was 10 or 11

**Comment by PromyLOPh** [comment]
Did you set LDFLAGS=-L/path/to/libav (unless it’s your system’s library
paths)? You can disable silent compiling by running `make V=1`.

**Comment by CalebDW** [comment]
I installed libav to /usr which should be my default path. I also set LDFLAGS=-L/usr and got the same result both times. http://hastebin.com/itolinemet.vbs

**Comment by PromyLOPh** [comment]
So, there’s two libav installed now? You could try giving the linker a
hint with LDFLAGS=-l/usr/lib64?/libav(util|filter).so.123 (expand and
replace 123 with actual version).

**Comment by CalebDW** [comment]
Thanks for all the help, I got it to compile.
