### ISSUE TITLE
Add configuration documentation.

### ISSUE THREAD

**Issue by skorokithakis** [PromyLOPh/pianobar#583]
I just downloaded pianobar but I can't figure out how to configure it. I didn't find any documentation as to where the config file should go or what should go into it. Can someone add something to the readme?

**Comment by rabin-io** [comment]
you have the config-example file under the contrib folder, https://github.com/PromyLOPh/pianobar/blob/master/contrib/config-example, this is a good place to start.

**Comment by skorokithakis** [comment]
Yes, but it's not visible at all. I only discovered it after you pointed it out. A link in the readme would be great.

**Comment by cburmeister** [comment]
The `man` page is pretty clear -- specifically the `FILE` and `CONFIGURATION` sections.

**Comment by skorokithakis** [comment]
I compiled from source, so the man page didn't get added. I don't see what the problem is with mentioning something in the readme.

**Comment by rabin-io** [comment]
I have added a short configuration to the [wiki](https://github.com/PromyLOPh/pianobar/wiki/Configuration).
