### ISSUE TITLE
"No package ao found"

### ISSUE THREAD

**Issue by jburris15** [PromyLOPh/pianobar#586]
I have reformatted my sd card a few times, reinstalled everything, and still run into this error:

pi@pandora:~/pianobar $ make
Package ao was not found in the pkg-config search path.
Perhaps you should add the directory containing `ao.pc'
to the PKG_CONFIG_PATH environment variable
No package 'ao' found
Package ao was not found in the pkg-config search path.
Perhaps you should add the directory containing`ao.pc'
to the PKG_CONFIG_PATH environment variable
No package 'ao' found
    CC  src/main.c
In file included from src/main.h:30:0,
                 from src/main.c:53:
src/player.h:35:19: fatal error: ao/ao.h: No such file or directory
 #include <ao/ao.h>
                   ^
compilation terminated.
Makefile:107: recipe for target 'src/main.o' failed
make: **\* [src/main.o] Error 1
- Any help would be appreciated thanks!

**Comment by dr-strangelove9** [comment]
You may not have libao compiles correctly.
