### ISSUE TITLE
Hangs after pausing or changing stations

### ISSUE THREAD

**Issue by partofthething** [PromyLOPh/pianobar#588]
Hi. I was loving pianobar on my Raspberry Pi until I did a dist-upgrade last night and now I'm having a big problem. On startup it plays the first station just fine but if I pause or change stations, it hangs indefinitely and is totally unresponsive. I recompiled just in case something changed in the libraries it's using but that didn't change anything. 

Terminal output including a pause, freeze, and a kill:
```
pianobar
Welcome to pianobar (2016.06.02-dev)! Press ? for a list of commands.
(i) Control fifo at /home/pi/.config/pianobar/ctl opened

(i) Login... Ok.
(i) Get stations... Ok.
|>  Station "Tropical House Radio" ([blah])
(i) Receiving new playlist... Ok.
|>  "Freak (Sam Feldt Remix Edit)" by "Quintino & R3hab" on "Freak (The Remixes)"
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.front.0:CARD=0'


ALSA lib conf.c:4259:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4738:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM front
Terminated/03:16
```
I had gotten warnings like what's shown above before (at least I think they are the same), and those all print out before the first song starts playing. 

`apt` history attached from last night to show what changed. 

[apt.history.txt](https://github.com/PromyLOPh/pianobar/files/311950/apt.history.txt)

**Comment by partofthething** [comment]
Actually it may be that I was connecting with `ssh -X` before and now I'm not. If I connect with `ssh -X` it appears to work. Is this expected? If so this report may be invalid.

**Comment by PromyLOPh** [comment]
Obviously pianobar shouldn’t become unresponsive. Looks like something
with your audio configuration is wrong (hence the ALSA messages). If you
believe this is a bug, create a backtrace
(https://wiki.ubuntu.com/Backtrace#Generation), remove your login
credentials, post it somewhere (or email it to me) and I’ll have a look.

**Comment by partofthething** [comment]
Hey, thanks. Yeah so if I connect over ssh with X-forwarding (`ssh -X server`), then it works great. But if I run as a service (headless) or connect with `ssh server`, then the `s` and `i` commands work fine but `p` doesn't do anything. I'm using it headless and controlling it with a home-automation system so this makes it hard. 

I'm pretty sure this particular symptom is unrelated to those ALSA warnings since sound works great and just controls are a problem (though those probably indicate something else wrong with my setup). 

So I need to debug the i/o stuff somehow. I can try a backtrace, or if there's something else you can think of that might help isolate the issue I'm happy to recompile, etc.

**Comment by PromyLOPh** [comment]
> But if I run as a service (headless) or connect with `ssh server`
What does “as a service” mean exactly?

**Comment by partofthething** [comment]
I mean it gets started as a subprocess by another program which remote controls it through `pexpect`. This is for a home automation project.

**Comment by PromyLOPh** [comment]
> I mean it gets started as a subprocess by another program which remote controls it through `pexpect`. This is for a home automation project. 
That should work, although I’d like to point you at pianod:
http://deviousfish.com/pianod/

Is PulseAudio installed/running on either side (client/server)?
Any special configuration in /etc/libao.conf or ~/.libao ?

**Comment by partofthething** [comment]
PulseAudio is running on the server. Nothing special in `/etc/libao.conf`:

```
default_driver=alsa
quiet
```
I will look into the `pianod` project too. Thanks for that.

**Comment by PromyLOPh** [comment]
> PulseAudio is running on the server. Nothing special in `/etc/libao.conf`:
Let’s just say, we’ve had some very strange issues with PulseAudio in
the past. See
https://github.com/PromyLOPh/pianobar/issues/433#issuecomment-38393851
for example.

**Comment by partofthething** [comment]
Hot dog. That led to some good errors:

```
Jun 14 07:32:26 tau pulseaudio[1502]: [pulseaudio] server-lookup.c: Unable to contact D-Bus: org.freedesktop.DBus.Error.NotSupported: Unable to autolaunch a dbus-daemon without a $DISPLAY for X11
Jun 14 07:32:26 tau pulseaudio[1502]: [pulseaudio] main.c: Unable to contact D-Bus: org.freedesktop.DBus.Error.NotSupported: Unable to autolaunch a dbus-daemon without a $DISPLAY for X11
Jun 14 07:32:26 tau pulseaudio[1502]: [pulseaudio] bluez4-util.c: org.bluez.Manager.GetProperties() failed: org.freedesktop.DBus.Error.UnknownMethod: Method "GetProperties" with signature "" on interface "org.bluez.Manager" doesn't exist
```
Thanks. I guess this issue is not with pianobar then.

**Comment by theAntiBob** [comment]
I've been a long time fan/user of pianobar. Nearly all of the issues i've had have not been an issue with pianobar AT ALL, but issues with pulseaudio or needing to point libao to the pulse driver instead of alsa.
Recently I have discovered that my soundcard (SB Audigy ZX Platinum) won't accept a sample rate of 44100khz, which is the default-sample-rate setting in /etc/pulse/daemon.conf
changing to default-sample-rate=48000 solved my most recent problem (although it was with pithos, not pianobar this time)
haven't seen this info posted anywhere, so i thought i would offer up this info to (hopefully) help other people fix their pulseaudio problems which, in turn are causing problems with other programs like pianobar.
