### ISSUE TITLE
Link to control-pianobar on https://6xq.net/pianobar/ is dead

### ISSUE THREAD

**Issue by darthwalsh** [PromyLOPh/pianobar#590]
At https://6xq.net/pianobar/ there's an External projects control-pianobar with dead link http://bruce-connor.github.com/control-pianobar/

It looks like the project moved to https://github.com/Malabarba/control-pianobar so the link should point to http://malabarba.github.io/control-pianobar/

(Hopefully this is the right place to report issues with the website!)

**Comment by PromyLOPh** [comment]
> It looks like the project moved to https://github.com/Malabarba/control-pianobar so the link should point to http://malabarba.github.io/control-pianobar/
Fixed. Thank you.

> (Hopefully this is the right place to report issues with the website!)
Sure, it’s related to pianobar.
