### ISSUE TITLE
Error: Invalid partner login.

### ISSUE THREAD

**Issue by ianjosephwilson** [PromyLOPh/pianobar#591]
I started receiving Invalid partner login when I would try to login with a version from 2015.  I just upgraded and am still receiving this error.  I just re-logged into the web interface it my login seems to be fine.  What could be causing this?  Could something be cached?

I'm currently using dadf76dc55733ec73fb11bc3ca5cc4c9eae3a24c .

I took the following steps to build:

`git pull`
`make clean`
`make`
`./pianobar`

**Comment by nharperc** [comment]
This just started for me as well. I'm using pianobar 2016.06.02 on OS X via brew.

**Comment by PromyLOPh** [comment]
Confirming, none of the partner credentials work any more (except for
the Pandora One credentials).

**Comment by cburmeister** [comment]
> This just started for me as well.

Same here -- i'm a Pandora one subscriber though...

**Comment by PromyLOPh** [comment]
Unfortunately the latest Pandora APK obfuscates the required strings.
I’ll look into it tomorrow. If someone else wants grab a decompiler:
Look for auth.partnerLogin and the method getBytes().

**Comment by AdamC1228** [comment]
The android partner keys still seem to be operational.

rpc_host = tuner.pandora.com
partner_user = android
partner_password = AC7IBG09A3DTSYM4R41UJWL07VLN8JI7
device = android-generic
encrypt_password = 6#26FRL$ZWD
decrypt_password = R=U!LH$O2B#
#tls_fingerprint = B0A1EB460B1B6F33A1B6CB500C6523CB2E6EC946

**Comment by sarana1** [comment]
2013.05.19 Windows x32 version stopped working this afternoon, and now it's back. No error message came up, though. The window just showed then closed out automatically on start up. This is on Windows 7.

**Comment by PromyLOPh** [comment]
Looks like a temparary hiccup. Keys in the Android .apk have not
changed.

**Comment by ianjosephwilson** [comment]
Yeah, weird.  Working again for me without any changes since report.  Thanks for looking at it.  I think this can be closed.

**Comment by cburmeister** [comment]
Same here. :+1:
