### ISSUE TITLE
Ubuntu 16.04 LTS Xenial

### ISSUE THREAD

**Issue by steveoh** [PromyLOPh/pianobar#593]
I just upgraded and am getting the following error. Can you offer any suggestions on how to remedy this?

```
pianobar: error while loading shared libraries: libgnutls.so.26: cannot open shared object file: No such file or directory
```

**Comment by steveoh** [comment]
I fixed this by building source, installing `libcurl4-openssl-dev`, `make clean` , `make`, `make install`

**Comment by lfaraone** [comment]
@steveoh did this happen when you were using the distro packages, or another locally-built package?

**Comment by steveoh** [comment]
This was distro packages. Piano bar is the only thing I have built locally
on this machine.

On Aug 7, 2016, at 2:04 PM, Luke Faraone <notifications@github.com> wrote:

@steveoh <https://github.com/steveoh> did this happen when you were using
the distro packages, or another locally-built package?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/PromyLOPh/pianobar/issues/593#issuecomment-238104929>,
or mute the thread
