### ISSUE TITLE
'using the deprecated Carbon Component Manager for hosting Audio Units' OSX: 

### ISSUE THREAD

**Issue by mark-a-s** [PromyLOPh/pianobar#595]
pianobar[6007:149202] 11:14:55.701 WARNING:  140: This application, or a library it uses, is using the deprecated Carbon Component Manager for hosting Audio Units. Support for this will be removed in a future release. Also, this makes the host incompatible with version 3 audio units. Please transition to the API's in AudioComponent.h.

ideas on what to do here ?

OSX: 10.11.6
using homebrew to install pianobar currently 2016.06.02.

**Comment by PromyLOPh** [comment]
See #529.
