### ISSUE TITLE
SIGINT during password prompt does not quit immediately

### ISSUE THREAD

**Issue by specious** [PromyLOPh/pianobar#600]
Using the latest git version (fd5bbd8d823d8f284c482aa8cace9e09fd1eac78), pressing `^C` does not quit immediately as I'd intuitively expect, but rather appears to attempt a login which subsequently fails:

```
$ ./pianobar
Welcome to pianobar (2016.06.02-dev)! Press ? for a list of commands.
[?] Email: specious@gmail.com
[?] Password:
(i) Login... Error: Wrong email address or password.
```

I've looked at issue #564.  Perhaps this case stands on its own?

**Comment by PromyLOPh** [comment]
Indeed, that’s a bug. Thanks for reporting!
