### ISSUE TITLE
Feature request: Use a socket instead of a linux FIFO for commanding pianobar externally

### ISSUE THREAD

**Issue by ijustlovemath** [PromyLOPh/pianobar#605]
It would be more cross platform, compatible with the current architecture (eg read/write/open work the same), and a fairly simple change. Thoughts?

**Comment by PromyLOPh** [comment]
Named pipes are available on any POSIX-compatible system, which is what
pianobar targets. What OS are you trying to port pianobar to?

**Comment by ijustlovemath** [comment]
Trying to emulate the control-pianobar script on Windows, but since Windows has no FIFOs, I thought a socket might work just as well. It could even be just another element of your input.fds[] array, which you open/add in main.c and check in ui_readlines.c. If you like, I could submit a PR?

**Comment by PromyLOPh** [comment]
I don’t think pianobar will compile/work on Windows and it was never
meant to. That’s why https://github.com/thedmd/pianobar-windows exists.
