### ISSUE TITLE
Feature Request: List seeds and thumbed up/down tracks for station

### ISSUE THREAD

**Issue by specious** [PromyLOPh/pianobar#607]
When logged in, https://www.pandora.com/station/167866705205165786 allows you to view the station's seeds and thumbed-up/down tracks.

For example:

![pandora-station-info](https://cloud.githubusercontent.com/assets/451178/21918760/c86ce542-d922-11e6-9e2d-c93a62100682.png)

Having a way to show that in pianobar would be awesome!

**Comment by PromyLOPh** [comment]
Press ‘=’.

**Comment by specious** [comment]
'=' is listed as:
```
=    delete seeds/feedback
```
When I press it, I see:
```
(i) Fetching station info... Ok.
[?] Delete [a]rtist seeds or [f]eedback?
```
What if I want to just view?

**Comment by PromyLOPh** [comment]
It won’t delete anything unless you explicitly pick a song/artist.

**Comment by specious** [comment]
I was honestly afraid to click it.  What if it said:
```
[?] View and manage [a]rtist seeds or [f]eedback?
```

**Comment by PromyLOPh** [comment]
Not sure if “view or manage” is enough of a warning, since pianobar does
not ask for confirmation once you selected a song/artist :-/
