### ISSUE TITLE
Unable to open audio file (Immediate exit requested) is back

### ISSUE THREAD

**Issue by scottidler** [PromyLOPh/pianobar#608]
I noticed that this was a previous issue, but it seems it came back today.  I have been listening via pianobar all day, and then this error suddenly started happening.  I then went to my checkout of this repo and moved master to the tip (9b26abba399a9b6d779713033693b631e5084458) and rebuilt and reinstalled.  The error persists.  This is an uptodate (fresh dnf update) Fedora 25 system.  I am not sure how to tell if I have ffmpeg or libav installed.

I am willing to try some things to help debug the issue.

**Comment by PromyLOPh** [comment]
I don’t remember this being a problem before. Do you know the issue id?

Does pianobar play some songs or none at all? Does the issue persist
across station changes and application restarts? Is the audio URL (press
$) accessible?

> I am not sure how to tell if I have ffmpeg or libav installed.
libavformat’s version in /usr/lib/ ends with a number >= 100, if ffmpeg
is installed.

**Comment by scottidler** [comment]
I guess the issue is not exactly the same: https://github.com/PromyLOPh/pianobar/issues/478.  However, I wonder if this was youtube.com issue, as it has completely gone away.  Meaning I have not received this error for days now.  I still have issues with having to Ctrl-C any command on my Ubuntu machines as opposed to my Fedora one, but that is unrelated to this issue, so I will close it.

**Comment by PromyLOPh** [comment]
Well, they could be related, since libav* only responds with “Immediate
exit requested” whenever you pressed ^C.
