### ISSUE TITLE
Unable to resolve host after Pandora update

### ISSUE THREAD

**Issue by emathia** [PromyLOPh/pianobar#612]
After Pandora update, the following error occurs when a file is accessed for steaming:
Failed to resolve hostname mediaserver-sv5-rt-1-v4v6.pandora.com: nodename nor servname provided, or not known.

Pianobar logs in, finds the station (OK), Recieves a playlist (OK), but cannot find the song on the list.

**Comment by blmpl** [comment]
I'm receiving "HTTP error 400 Bad Request" but I'm unable to play music in Firefox too, were you able to paly it in any browser/app? 
for me it looks like some bigger problem - see the comments here: http://downdetector.com/status/pandora

**Comment by blmpl** [comment]
and it's working again :)

**Comment by emathia** [comment]
My Pianobar is still giving the same issue.  I uninstalled and re-installed and I get the same thing.  I think the issue is Pandora's fault -  I just love my piano bar.  DId you do something special to get it working again?

**Comment by blmpl** [comment]
no, I just quit program and start again (I'm not sure if it was necessary) but (finally) I was also able to play some music from web page. I'm not sure what happened.

**Comment by emathia** [comment]
Ah, it is still a problem from Pianobar.

**Comment by PromyLOPh** [comment]
Works fine for me. The problem sounds like a DNS caching issue. Nothing
I can fix on my end.
