### ISSUE TITLE
getting access denied randomly(?)

### ISSUE THREAD

**Issue by derfy321** [PromyLOPh/pianobar#616]
Every so often, I'll get
```
[?] Select station: 9
|>  Station "Thumbprint Radio" (3239531473221066642)
(i) Receiving new playlist... Error: Access denied. Try again later.
```

Retrying a few times will eventually retrieve songs.  This seems to happen after I've skipped often (I'm a pandora plus account) but I thought the hypothesis for the server denying you was 42 seconds of silence.

Let me know what other info you may need to proceed and instructions for me on how to collect it.

```
[fagricola@l6 pianobar-master]$ uname -a
Linux l6.noc.al.privatesystems.net 4.8.13-1-ARCH #1 SMP PREEMPT Fri Dec 9 07:24:34 CET 2016 x86_64 GNU/Linux
----
Welcome to pianobar (2016.06.02-dev)! Press ? for a list of commands.

```

**Comment by derfy321** [comment]
Note: I cloned the latest git and the problem is still there.

**Comment by PromyLOPh** [comment]
Works for me. I don’t see what I can do about server-side issues.

**Comment by vahidhashemi** [comment]
I have the same problem here too. I have to use a proxy since I'm outside the U.S.
