### ISSUE TITLE
Failure data from the peer

### ISSUE THREAD

**Issue by HoussemCharf** [PromyLOPh/pianobar#621]
```
Unrecognized key tls_fingerprint at /home/pi/.config/pianobar/config:65
Welcome to pianobar (2016.06.02-dev)! Press ? for a list of commands.
Control fifo at /home/pi/.config/pianobar/ctl opened
Login... Network error: Failure when receiving data from the peer

Linux raspberrypi 4.9.20-v7+ #985 SMP Mon Apr 3 10:30:44 BST 2017 armv7l GNU/Linux

```
i ve tried digging through issues but none seems to work for me.
 the unrecognized key issue is what i dont get most cause i made sure i had the current fingerprint

**Comment by PromyLOPh** [comment]
The fingerprint has been removed long ago, see commit
61dbc218e747f1b550a2615ffe3065024db29239

Connecting to Pandora works for me, so this might be a temporary error.

**Comment by HoussemCharf** [comment]
i am still getting the error even after deleting the fingerprint line :/

**Comment by HoussemCharf** [comment]
i solved it by changing my dns ... still tho it's worth investigating sound like proxy problem cause i ve tried working proxies yet nothing.

**Comment by PromyLOPh** [comment]
Can you be a little more specific?

**Comment by HoussemCharf** [comment]
i live outside of the us so obviously i had to activate the proxy setting in config somehow that didnt work for me it kept showing me the error i mentioned it but an idea crossed my mind i am used to open pandora in my laptop using dns provided here portaller.com so i applied the same thing in my raspberry 
i set up the DNS and desactivated proxy setting then it was fixed but as i said the real issue is worth investigating when proxy setting is on `Network error: Failure when receiving data from the peer` still show up now i made sure the proxies i used in the config are working so there is an issue there :/

**Comment by PromyLOPh** [comment]
Which proxy did you use and did you set up `proxy = XXX` or
`control_proxy = XXX`?

**Comment by HoussemCharf** [comment]
i did use a US based proxy and i did set it up in the config as it should be with the port i even tested it with my browser 
ofc i also  removed the #
control_proxy = http://52.34.132.230:3128/ it was something like this .
Anyway, thank you soo much for the project btw i wish i can be more helpful to track the issue but i am not really good at C.
strangly no one reported this before :/

**Comment by PromyLOPh** [comment]
This particular proxy asks for credentials and thus won’t work.
However in general control_proxy works fine for me.

**Comment by tkfu** [comment]
Proxies can be a a bit finicky, especially if you're just grabbing a random free one. I recently wrote a script to generate config files for pianobar as part of a Yocto layer; @HoussemCharf you could easily just factor out the proxy finding logic if you don't want the rest of it: https://github.com/advancedtelematic/meta-jukebox/blob/master/recipes-multimedia/patiobar/files/start-patiobar.py
