### ISSUE TITLE
Unable to make pianobar under jessie

### ISSUE THREAD

**Issue by ldeforre** [PromyLOPh/pianobar#625]
pianobar has been working fine for me, until today.
Am getting the following errors:
[mp3 @ 0x73b00480] max_analyze_duration 5000000 reached
[abuffer @ 0x73b12be0] Invalid channel layout 0x0.
/!\ create_filter abuffer (Invalid argument)

checked pianobar's version.   (2014.06.08-1), which is rather old.
So I am attempting to build pianobar from git.
However, most build instructions are based on Wheezy and require the following package that is not found in Jessie:  libgnutls-dev.

Can someone point me to good build instructions for Jessie?

**Comment by PromyLOPh** [comment]
> However, most build instructions are based on Wheezy and require the
> following package that is not found in Jessie:  libgnutls-dev.
That package is not required any more. You’ll need libcurl (and -dev)
instead.

**Comment by ldeforre** [comment]
I got it to work using your hint.

Thanks!
