### ISSUE TITLE
possible to auto-retry after access denied?

### ISSUE THREAD

**Issue by derfy321** [PromyLOPh/pianobar#626]

**Comment by derfy321** [comment]
Stupid...enter should not auto-submit a blank entry...
Anyway, can you auto-retry the current station after an access denied?

https://pastebin.com/q7qbSQie

**Comment by PromyLOPh** [comment]
Sorry for the delay. I’m not sure automatic retries are appropriate
here. A retry usually fails as well (c.f. your paste) and there’s no way
of knowing how long the error persists i.e. how long pianobar should
wait between retries. Also I’m not sure what causes the error.

**Comment by derfy321** [comment]
Normally it rarely happens, but I can increase the chances if I interrupt via ctrl+c while retrieving playlist takes too long.

Also, 4 days is not that long of a delay.  No worries! :)

**Comment by sharpentheaxe** [comment]
Hi,
I would also like to have a retry if the network fails to connect.  Is there a way to do this through the eventcmd?   Can I detect a particular network error event then wait a set time in the script and then restart pianobar?

**Comment by PromyLOPh** [comment]
libcurl’s return code and error text are available to your script. Check
the wRet and wRetStr keys. You can certainly restart pianobar, but
retrying a particular operation won’t be easy.
