### ISSUE TITLE
Unofficial Pandora API Discord

### ISSUE THREAD

**Issue by FireController1847** [PromyLOPh/pianobar#627]
Hello! 👋 

💠 I'm going around all of the Pandora Libraries's as well as their products, and telling users about a Discord server I've been making to allow us all to communicate easily and quickly. All library creators will be given their own role and their own support channel to (optionally) help users. All product creators will be given their own role, and their own support channels as well. Please join! We're looking to get as many Unofficial Pandora API dev's to come together, and allow for easy communication.

💠 Some more info about me: A simple Discord user. I'm looking to create Node.js API, but noticed there was no way to contact anyone nor a simple community behind it that I could talk to, so I've made this guild to try to make the community visible as one giant group.

💠 We think you'd be an awesome addition to the community, please, join! Let's bring this Unofficial API all into one place for easy support and documentation, as well as product listings and library listings. Hope to see you there! 👍 

[Join Here](https://discord.gg/VqzGTV8)
https://discord.gg/VqzGTV8

**Comment by PromyLOPh** [comment]
See https://github.com/pithos/pithos/issues/479

**Comment by FireController1847** [comment]
You too huh. I was just trying to get the community together... :/
