### ISSUE TITLE
Volume has dropped off on Centos 7

### ISSUE THREAD

**Issue by aghoras** [PromyLOPh/pianobar#629]
I've been running pianobar 2016.06.02-dev for a while now. A few weeks ago the volume dropped off to the point I can't hear anything. If I increase the volume from the CLI client, it is still faint and very distorted. The pandora webclient plays fine on the same machine. 

Does anybody else have this problem? Did something on the server side change?

Thanks

**Comment by PromyLOPh** [comment]
Working fine for me, so probably not a server issue. If you reset
pianobar’s volume (press ^) there might be per-application volume
controls (pulseaudio offers this, afaik) limiting pianobar’s output
volume.

**Comment by aghoras** [comment]
Thanks Lars. That was it. I don't know how it got changed in pulse audio. I had to install pavcontrol and then I was able to change the volume back to normal levels. 
-Ali
