### ISSUE TITLE
audio stutter/warble during disk I/O after upgrade to Stretch

### ISSUE THREAD

**Issue by glyndon** [PromyLOPh/pianobar#630]
Latest code has been running well on Raspbian Jessie.
Upgraded to Stretch.
Now, whenever any process performs I/O, the pianobar playback audio stutters.
renice to -20 didn't help at all.

What details could I supply that would be helpful in identifying the cause?

**Comment by PromyLOPh** [comment]
I assume you are using a Raspberry Pi? If so which revision? Which
pianobar version are are we talking about (i.e. compiled from git,
Debian repository + version number)? Since I have access to a Pi 2B I
can test this myself later this week, but it needs to be upgraded first.

**Comment by glyndon** [comment]
Yes, a Pi 1B, with a C-Media USB audio device.
Code is compiled from git (2016.06.02-dev).
libav 12.1, compiled locally.

**Comment by glyndon** [comment]
I can report (happily) that after building pianobar on a fresh install of 'stretch' (from a virgin image), the problem does *not* occur for me.
So this issue may be moot and close-able (your call).
May it serve as a warning to others that a raspbian/debian/any OS upgrade-in-place may yield such anomalies (as if that weren't already sufficiently warned about).

**Comment by PromyLOPh** [comment]
My setup is slightly different (Pi 2B, analog audio output; libav and
pianobar are both the same though) and I cannot reproduce the issue,
even with `dd if=/dev/mmcblk0 of=/dev/null` running concurrently. So
this is an issue with either your configuration or hardware (Pi 1B not
powerful enough?). I doubt I can help you with either, sorry.

**Comment by glyndon** [comment]
I'll give it a try on a 2B, and post what I find, in case it helps someone who runs into this syndrome. 
Seems like whatever changed had to be in the OS update. The 1B machine has been quite sufficient up till this point, with pianobar using a consistent 17% CPU and never stuttering even while I compile libav on it.

**Comment by glyndon** [comment]
Confirmed.
I have a Pi2B which I upgraded to Stretch in the same manner as the Pi1B, but pianobar plays smoothly on the Pi2B.
Looks like I'll have to find a new use for the 1B.
