### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by lfaraone** [PromyLOPh/pianobar#631]
I'd be O.K. with packaging a git snapshot in Debian, but there are some new features it'd be great to ship. (`gain_mul`, `bind_to`)

**Comment by PromyLOPh** [comment]
You’re right. It’s been more than a year since 2016.06.02, so I’ll
prepare a release in the next days. First I want to verify pianobar
still works with ffmpeg 3.3.

**Comment by PromyLOPh** [comment]
Done. Thanks for packaging pianobar!
