### ISSUE TITLE
tcp connection failed, trying next address

### ISSUE THREAD

**Issue by treewolf** [PromyLOPh/pianobar#632]
Starting today, i started getting these error messages when i play music. It doesn't seem to affect my listending experience, only the usual output in pianobar is missing and getting errors instead. I can still issue key commands.

`[tcp @ 0x7fcf78113c20] Connection to tcp://mediaserver-sv5-rt-1-v4v6.pandora.com:80 failed (Connection refused), trying next address`

Is this a server issue, maybe related to the 400 error issue?

**Comment by PromyLOPh** [comment]
Is this still a problem? Is your IPv6 connectivity working?

**Comment by treewolf** [comment]
Hi,

My ipv6 is enabled and working. I ran pianobar this morning and it still shows the connection refused error. Did you need any logs, just let me know.

**Comment by treewolf** [comment]
My ipv6 is enabled and working. I ran pianobar this morning and it still shows the connection refused error. Did you need any logs, just let me know. Also, when i try to cancel the pianobar process (eg, when i am done listening to music) i like to press ctrl + c, and that will sigint the process. Now when i try it i get the message:

`
[http @ 0x7fe2180d3b00] HTTP error 403 Forbidden
/!\ Unable to open audio file (Server returned 403 Forbidden (access denied))
`

Instead, now i need to suspend the process and subsequently kill it, or just close my terminal altogether.

**Comment by treewolf** [comment]
As of right now, the error is gone. Thank you a bunch!
