### ISSUE TITLE
Clarification for audio_quality =

### ISSUE THREAD

**Issue by Mibo5354** [PromyLOPh/pianobar#634]
Could you put some information on the wiki or the example config for what settings that can actually be put in "audio_quality = {high|192k mp3|???}"

**Comment by PromyLOPh** [comment]
Have a look at the manpage.

**Comment by Mibo5354** [comment]
So does "audio_quality = high" automatically gets the highest quality for Pandora One subscribers?

**Comment by PromyLOPh** [comment]
I’m not sure, to be honest. Can you apply this patch[1], recompile and
send me pianobar’s output (lars+pandora@6xq.net – please remove password
and auth token)?

[1] https://gist.github.com/7c0c7c69d0607f3d120efac5fac1b10a

**Comment by Mibo5354** [comment]
I'm sorry but where do I put the verbose.patch file?

**Comment by Mibo5354** [comment]
Done

**Comment by PromyLOPh** [comment]
Thanks. You’re receiving 64 kbit/s AAC. According to [1] “mobile devices
receive a variety of different rates depending on the capability of the
device and the network they are on, but never more than 64k AAC+.” Since
pianobar uses the mobile API I believe there is nothing I can do to
retrieve 192kbps audio files mentioned on the same page.

[1] http://help.pandora.com/customer/portal/articles/1468387-change-your-account-settings#7

**Comment by albertsj1** [comment]
@Mibo5354 Take a look at the config here: https://github.com/PromyLOPh/pianobar/blob/master/contrib/config-example#L62

**Comment by Mibo5354** [comment]
@albertsj1 What is your point?

**Comment by albertsj1** [comment]
Beginning at line 62, it shows the configuration you need to use high quality audio if you have a pandora one account.  I just set those same values in my config file and the audio quality sounds great, though I haven't tried the patch suggested above to determine the actual bit rate.

**Comment by PromyLOPh** [comment]
The comment is a lie.

**Comment by albertsj1** [comment]
@PromyLOPh No.  My comment is definitely not a lie.  My claim that the quality 'seems' great is certainly true.  Though, as I indicated in my comment, I didn't confirm using the patch that the bit rate is indeed higher than normal, so this claim should be taken with a grain of salt.

**Comment by PromyLOPh** [comment]
Sorry, I was refering to the comment in the example config file you
linked. It was true a long long time ago, though.

**Comment by albertsj1** [comment]
Thanks for clarifying. :)
Do those config settings I linked to have any affect at all then?

**Comment by Mibo5354** [comment]
The config file should be updated with the new information. Clarifying the maximum quality available is 64k AAC+ not 192k mp3.

**Comment by PromyLOPh** [comment]
> Do those config settings I linked to have any affect at all then?
Yes, you can actually *lower* the quality to 32k if I recall correctly.

> The config file should be updated with the new information.
It’s on my todo list.

**Comment by b01t** [comment]
@PromyLOPh With Pandora Plus, Pianobar actually seems to play 192k mp3 now. I verified this by applying the patch from the 4th post above, and seeing that the highQuality audiomap returns stuff like:
"highQuality":{"bitrate":"192","encoding":"mp3","audioUrl":"http://t3-3.p-cdn.us/access/6630948428793542401.mp3?version=5&lid=.........

**Comment by PromyLOPh** [comment]
You’re using the default credentials (partner_user/_password)? Can you
paste the entire response somewhere?

**Comment by b01t** [comment]
Sure. Here you go: http://paste.debian.net/1040938/
Yes, I'm using the default credentials.

I've gone into my settings on the Pandora site and enabled high quality, which was disabled after they moved the high quality things from Plus to Premium, which I upgraded to. I am also currently on the 6 month premium trial, but I doubt that affects stuff.

It would be shitty business practice, after all, to give the trial users better quality than the ones who are paying the premium price for the premium service.

**Comment by PromyLOPh** [comment]
You’re right, that looks alot like 192k mp3. This page now also mentions
192k mp3 on Android, so they must’ve changed it:
https://help.pandora.com/s/article/Change-your-Personal-Settings-1519949296224?language=en_US
Either way, pianobar plays the highest quality available by default,
which should be fine for most people.
