### ISSUE TITLE
sometimes starts at station list other times just starts playing...

### ISSUE THREAD

**Issue by artphotodude** [PromyLOPh/pianobar#635]
Is there a way to have it do one or the other?  Seems very unpredictable whether I'll get the list or having it just take off with the last one played - and honestly I'd prefer to always get the station list at startup.

**Comment by PromyLOPh** [comment]
pianobar remembers the last station you played. You can override this
behavior by adding ``autostart_station = 0`` to your config file.

**Comment by artphotodude** [comment]
I suspected there was some way.  Thanks some much for the reply!!
