### ISSUE TITLE
[FR] Show playtime in history

### ISSUE THREAD

**Issue by RichiH** [PromyLOPh/pianobar#636]
When showing history, I would love to see the playtime of the songs which had been played.

**Comment by PromyLOPh** [comment]
Playtime as in “how long is this song in total”? Since there is a custom
format string already I could add that option to BarUiListSongs. However
this applies to *all* song selection lists.

**Comment by RichiH** [comment]
How long in total and actual playtime I listened to. If I skipped a 5 minute song after one minute, it would show

`1:00/5:00`

**Comment by PromyLOPh** [comment]
I did not add actual playtime, because it is not a song property (right now).
