### ISSUE TITLE
[FR] Extend history

### ISSUE THREAD

**Issue by RichiH** [PromyLOPh/pianobar#638]
Even if I can't love songs any more after a certain time, I would still like to be able to press h repeatedly to go back further in my history; and also see any station changes in the history as well.

**Comment by PromyLOPh** [comment]
You can adjust the number of songs shown via ``history = 100``. Or do
you propose a persistent song history? Showing station changes sounds
neat and should not be too difficult, since each song is associated with
a station.

**Comment by RichiH** [comment]
I didn't register `history` when reading the manpage; sorry. No need for persistence, imo.

And yes, showing changes would still be appreciated.

**Comment by PromyLOPh** [comment]
The UI is a litte verbose (i.e. showing it for every song), but it’s consistent with the way quickmix works, thus I’m reusing that design.
