### ISSUE TITLE
Previous saved feedback not displaying

### ISSUE THREAD

**Issue by basicide** [PromyLOPh/pianobar#639]
I just noticed that songs I have previously liked don't show up when they play again. I can like them again and the info shows me that they're liked, but the next time I see them again, the feedback is not displayed. I can still see the previous feedback in the station feedback history, just not when it's actually being played.

**Comment by PromyLOPh** [comment]
Works for me. Can you post your config file?

**Comment by basicide** [comment]
user = usr
password = passwd
autostart_station = 3648477479983992262
history = 10
format_nowplaying_song = [32m%t[0m by [36m%a[0m on [31m%l[0m[35m%r[0m%@%s
format_nowplaying_station = Station [34m%n[0m
format_list_song = %i) %a - %t%r

One thing I noticed that might be related, when I look at station feedback in pianobar, there are 195 saved feedback options, but using the mobile client, there are 262. I wonder if it's losing some saved feedback or not pulling it all back?

**Comment by PromyLOPh** [comment]
> when I look at station feedback in pianobar, there are 195 saved
> feedback options, but using the mobile client, there are 262.
That is strange indeed. I’m not aware of any pagination for this API
request. Apparently positive/negative feedback disappears from that
list in chronological order when it grows larger than 100 items. But the
feedback is not removed, just hidden, since totalThumbsUp has the value
169 which – plus 96 totalThumbsDown – adds up to 265. Close enough.

So, does the mobile client actually show every single feedback or just
that number?

Example regarding the original issue:

Upcoming:
	 1) Killercats - Tell Me (03:02)
Feedback:
	33) Killercats - Tell Me (Feat. Alex Skrindo) <3 (??:??) @ (deleted)

So Pandora has this song in the database twice. One of them is marked
liked while the other is not. Can you confirm this is the issue you
initially reported?

**Comment by basicide** [comment]
It does show the list in the iOS client as well as the number, but upon further inspection it doesn't show every one of the thumbs up tracks. It only shows roughly 100 like you mentioned and it does match up with the list pianobar generates. Same story for the thumbs down tracks. Given that, it's very possible that a multiple database entry situation occurred similar to the example you gave.

With that in mind, is there a way for me to query either the full list of thumbs up/down tracks for reference or query their song database to see if there are multiple tracks if I notice it happening again?

**Comment by PromyLOPh** [comment]
> is there a way for me to query either the full list of thumbs up/down tracks for reference
The web interface maybe?

> query their song database to see if there are multiple tracks if I notice it happening again?
Yes, the “create a new station” command does that:

[?] Create station from artist or title: Killercats - Tell Me
(i) Searching... Ok.
[?] Is this an [a]rtist or [t]rack name? t
	 0) Killercats - Tell Me (Feat. Alex Skrindo) (??:??)
	 1) Killercats - Tell Me (??:??)

**Comment by basicide** [comment]
It's funny, since I've been using pianobar, I've forgotten the web interface was still a thing. Sure enough, it has the full list. I'll use it for comparison in the future along with new station creation to check for duplicates. I think I'm squared away for now. Thanks for the help!
