### ISSUE TITLE
Adding shared station... Error: Internal error.

### ISSUE THREAD

**Issue by jrogers512** [PromyLOPh/pianobar#641]
Version: 2016.06.02
Platform: Mac OSX
Installation method: brew install pianobar

Steps to reproduce (not certain all are necessary):

1. s Play quickmix, select the station id for quickmix
2. c Create a new station (I chose one that includes an apostrophe when I created this), search for artist "The W's"
3. s List current stations, take note of the number by the new station ("The W's")
4. j add shared station, when prompted enter the number obtained in previous step.

Result: 
`(i) Adding shared station... Error: Internal error.`

**Comment by PromyLOPh** [comment]
Can you reliably reproduce the problem? Works fine with both HEAD and
2016.06.02 for me. Also the error message suggests an internal error *at
Pandora’s end*.

**Comment by jrogers512** [comment]
Yes, i'm able to reliably reproduce these results.  I suspect that the issue has something to do with the station having an apostrophe in the name?

`Welcome to pianobar (2016.06.02)! Press ? for a list of commands.
(i) Login... Ok.
(i) Get stations... Ok.
|>  Station "QuickMix" (2730933063951646540)
(i) Receiving new playlist... Ok.
|>  "Holiday" by "Weezer" on "Weezer" @ Weezer Radio
[?] Station id: 43
(i) Adding shared station... Error: Internal error.
#   -03:18/03:24`

I pressed J and entered 43, which is the station id for "The W's"

**Comment by PromyLOPh** [comment]
The number pianobar shows in front of a station is not its globally
unique id.

> |>  Station "QuickMix" (2730933063951646540)
You’re looking for this one instead ↑
