### ISSUE TITLE
Install/Make Error on RPI

### ISSUE THREAD

**Issue by engineerjoe440** [PromyLOPh/pianobar#646]
Newbie here!

I am trying to install or make the latest version of Pianobar to alleviate the issue of Pandora timeouts. Trouble is, my RPI (running Jessie) thinks that pianobar is up to date. It is not.

`i@raspberrypi:~ $ pianobar
Welcome to pianobar (2014.06.08)! Press ? for a list of commands.`

Thus I have tried to install it again, and received the following message, even after updating and upgrading my RPI.

`sudo apt-get install pianobar
Reading package lists... Done
Building dependency tree       
Reading state information... Done
pianobar is already the newest version.
The following packages were automatically installed and are no longer required:
  libkeybinder0 python-gst0.10 python-keybinder python-libxml2 python-notify
Use 'apt-get autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.`

From this, I decided to try making Pianobar, so I first made ffmpeg. After doing so, I was able to see that it (in fact) had been made on the system.

`ffmpeg
ffmpeg version N-88408-g86c446e Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 4.9.2 (Raspbian 4.9.2-10)
  configuration: 
  libavutil      56.  0.100 / 56.  0.100
  libavcodec     58.  1.100 / 58.  1.100
  libavformat    58.  0.102 / 58.  0.102
  libavdevice    58.  0.100 / 58.  0.100
  libavfilter     7.  0.101 /  7.  0.101
  libswscale      5.  0.101 /  5.  0.101
  libswresample   3.  0.100 /  3.  0.100
Hyper fast Audio and Video encoder
usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile}...

Use -h to get full help or, even better, run 'man ffmpeg'
`

Now, after copying the repository, I performed the make clean command and my RPI responded, signifying that the make was clean. I then proceeded to make receiving the following.

`make
    CC  src/main.c
In file included from src/main.h:30:0,
                 from src/main.c:53:
src/player.h:37:39: fatal error: libavfilter/avfiltergraph.h: No such file or directory
 #include <libavfilter/avfiltergraph.h>
                                       ^
compilation terminated.
Makefile:107: recipe for target 'src/main.o' failed
make: *** [src/main.o] Error 1
`
Any suggestions would be greatly appreciated! Thanks in advance!

**Comment by PromyLOPh** [comment]
Jessie is quite old. You should upgrade to stretch (current stable),
which includes a newer version of pianobar.

**Comment by engineerjoe440** [comment]
Great! Thank you! I'll try that today!

**Comment by engineerjoe440** [comment]
That worked! Upgrading to Stretch fixed the problem, now I'm running into an issue with auto-starting Pianobar on boot though. I've tried several methods including adding code to rc.local and LXDE-pi/autostart to get Pianobar to start when the pi boots. Nothing's working... any suggestions? Thanks!

**Comment by PromyLOPh** [comment]
Try starting it like this `nohup pianobar`.
