### ISSUE TITLE
Question: Multiple event_cmd scripts

### ISSUE THREAD

**Issue by USAFPride** [PromyLOPh/pianobar#648]
Is it possible to have multiple event_cmd scripts?

**Comment by PromyLOPh** [comment]
Yes, see contrib/eventcmd-examples/multi.sh

**Comment by USAFPride** [comment]
Just to clarify:  

I would add:  
```
event_command = /home/pi/Patiobar/eventcmd1.sh
event_command = /home/pi/Patiobar/eventcmd2.sh
```
in a file called `eventcmd.d`?

**Comment by PromyLOPh** [comment]
No, the idea is to put all your (executable!) event scripts into the
directory ~/.config/pianobar/eventcmd.d/ and add

event_command = /path/to/multi.sh

to your config file. multi.sh basically acts as a “trampoline”,
executing all scripts in eventcmd.d.

I probably should add this description to the top of multi.sh, shouldn’t
I?

**Comment by USAFPride** [comment]
Sorry for the late response. A bit of a holiday.  I would recommend some specific examples/clarifications to the use.  I haven't tried anything as I didn't want to break something right before I left.
