### ISSUE TITLE
Feature Request: Like previous song

### ISSUE THREAD

**Issue by haxwithaxe** [PromyLOPh/pianobar#650]
It would be really helpful to be able to like a song after it has finished playing. It would be even better if it were possible to like songs arbitrarily far back in the current session.

**Comment by PromyLOPh** [comment]
The feature you are craving for exists already ;) Pressing ‘h’ pulls up a
list of recently played songs. Select one and press ‘?’ to show a list
of supported actions.

**Comment by haxwithaxe** [comment]
Derp. Sorry.  I don't know what I was looking at. Can the numbers go back beyond the ones listed or is it limited to those?

**Comment by PromyLOPh** [comment]
You can increase the number of songs shown by adding ``history = 10``
(or whatever number you choose) to your config file.
