### ISSUE TITLE
TLS-fingerprint mismatch

### ISSUE THREAD

**Issue by chrisjosack** [PromyLOPh/pianobar#652]
How do I fix a TLS-fingerprint mismatch in LINUX Debian. Just installed it then ran upgrades and updates.

**Comment by PromyLOPh** [comment]
You must be running a pretty old version of pianobar. You can run
./contrib/tls_fingerprint.sh and set tls_fingerprint in your config file
or – recommended – update pianobar itself.

**Comment by chrisjosack** [comment]
I am new to Linux so I may not be working from the right place. I redownloded the newest pianobar, Unzipped it then I used sudo apt-get install. then I used sudo apt-get udate and it updated a lot of OS files but not Pianobar. Must I be in a certain directory when i update?
Thanks in advance.

**Comment by nikty** [comment]
@chrisjosack you are doing 2 unrelated things. You don't unzip anything when using apt-get.
Check the version of pianobar that is installed via apt-get:
$ dpkg -l | grep pianobar
If it's old, either upgrade your system (see system's manual) or install pianobar from the source code (now, HERE you unzip things and run commands like `make').

**Comment by bgarr33434** [comment]
sorry, but what constitutes "old"?  I'm told by folks at Mycroft that this hasn't been touched in years?

**Comment by PromyLOPh** [comment]
Everything but the latest release (right now that’s 2018.06.22) is old
and unsupported, unless your distribution steps in and provides
support/patches. Sorry.

**Comment by bgarr33434** [comment]
no worries.  Do I have to compile my own, or can I install from the command line.  When I do an apt-get install pianobar, it tells me I have the most current version

**Comment by bgarr33434** [comment]
the actual error is Network error: TLS fingerprint mismatch.  Perhaps this is a network error, not a mismatch error?
