### ISSUE TITLE
Display station being played

### ISSUE THREAD

**Issue by robcazzaro** [PromyLOPh/pianobar#659]
I might be missing something, but where can I see the station being played? My Patiobar/pianobar is used by two people listening to different stations. Would be good to be able to see which station is playing, in addition to the song being played

BTW: thanks for the awesome Patiobar!

**Comment by PromyLOPh** [comment]
I can’t help you with issues regarding patiobar.

**Comment by robcazzaro** [comment]
That was dumb, sorry :( I entered this in the wrong browser tab/git page. 

Closing it right away (and also a big thank to you for making pianobar available and open source, I love it)
