### ISSUE TITLE
avfiltergraph.h Depreciated/merged into avfilter.h

### ISSUE THREAD

**Issue by EndlessEden** [PromyLOPh/pianobar#660]
avfiltergraph.h was merged into avfilter.h, on ffmpeg commit 38f0c07(2013) [https://source.ffmpeg.org/?p=ffmpeg.git;a=commit;h=38f0c0781a6e099f11c0acec07f9b8be742190c4](url)
Please remove the include for it. As it causes builds to fail.

**Comment by EndlessEden** [comment]
[player.c.txt](https://github.com/PromyLOPh/pianobar/files/1906615/player.c.txt)
[player.h.txt](https://github.com/PromyLOPh/pianobar/files/1906616/player.h.txt)

**Comment by EndlessEden** [comment]
I use git builds -  N-90704-g23e994ca49 - avfiltergraph.h is not created anymore. Hasnt for some time, on my platform(Arch Linux).

**Comment by PromyLOPh** [comment]
Ah yes, now I see. The header was removed from ffmpeg with commit
f5950b8fd61ec85e0ad8790bea56b37ceea19436, which did not make it into any
release yet. Fixed, thank you!
