### ISSUE TITLE
Adding station Name to ~/.config/pianobar/currentSong

### ISSUE THREAD

**Issue by robcazzaro** [PromyLOPh/pianobar#661]
I'm using Pianobar together with Patiobar on my Raspberry Pi. I'm trying to get the station name displayed on the Web Ui of Patiobar, and according to this https://github.com/kylejohnson/Patiobar/issues/18, I need to add the station name to the ~/.config/pianobar/currentSong file

Is there a way to do so with configuration files?

**Comment by PromyLOPh** [comment]
You’ll need to set up eventcmd scripts. Those can write the current
station name to that file. Have a look at the directory
contrib/eventcmd-examples for inspiration.

**Comment by robcazzaro** [comment]
Got it... seems easy enough, sorry for missing it
