### ISSUE TITLE
Cannot find decoder

### ISSUE THREAD

**Issue by cazador481** [PromyLOPh/pianobar#662]
When I try to run pianobar nothing will play, and I get the following.

> pianobar
debug: Loaded driver null (built-in)
debug: Loaded driver wav (built-in)
debug: Loaded driver raw (built-in)
debug: Loaded driver au (built-in)
debug: Loading driver plugins from /usr/lib64/ao/plugins-4...
debug: Loaded driver alsa
debug: Loaded driver oss
debug: Loaded driver pulse
Welcome to pianobar (2017.08.30)! Press ? for a list of commands.
(i) Login... Ok.
(i) Get stations... Ok.
|>  Station "Alicia Keys Radio" (125211095811683310)
(i) Receiving new playlist... Ok.
|>  "Say Goodbye" by "Chris Brown" on "Chris Brown"
/!\ find_decoder (Success)
|>  "Fallin' Out" by "Keyshia Cole" on "Just Like You"
/!\ find_decoder (Success)
|>  "Bust Your Windows" by "Jazmine Sullivan" on "Fearless"
/!\ find_decoder (Success)
|>  "Broken-Hearted Girl" by "Beyoncé" on "I Am...Sasha Fierce"
/!\ find_decoder (Success)
(i) Receiving new playlist... Ok.
|>  "Twisted" by "Keith Sweat" on "Keith Sweat"
/!\ find_decoder (Success)
|>  "Until The End Of Time" by "Justin Timberlake" on "Futuresex/Lovesounds"
/!\ find_decoder (Success)
|>  "Yo (Excuse Me Miss)" by "Chris Brown" on "Chris Brown"
/!\ find_decoder (Success)
|>  "Sweet Lady" by "Tyrese" on "Tyrese"
/!\ find_decoder (Success)

**Comment by PromyLOPh** [comment]
I need more information: Your Linux distribution and version, ffmpeg
version and whether you compiled that yourself, as well as your config
file (redact username and password). Also it would be nice if you could
press '$' while the playback is failing and post its output here.

**Comment by cazador481** [comment]
Turns out the ffmpeg that suse is using doesn't have AAC installed.  I switched to a different version and now things are working better.
