### ISSUE TITLE
Pianobar returning tls fingerprint mismatch on PI

### ISSUE THREAD

**Issue by bgarr33434** [PromyLOPh/pianobar#663]
the exact same config file is working fine on Ubuntu box.  Pianobar date is 2014.06.08

**Comment by PromyLOPh** [comment]
See https://github.com/PromyLOPh/pianobar/issues/652#issuecomment-367021972 for example.

**Comment by bgarr33434** [comment]
Is it possible for there to be more than one .config/config file?  Maybe I updated the wrong one?

**Comment by PromyLOPh** [comment]
Please: Don’t post in two different issues simultanously, use the search
function (other people had the same issue, trust me), read the manpage
(path to the config file is in there) and try the solution I’ve pointed
you at.

I don’t mean to be rude, but this is a bug tracker and not a support
forum. And the problem you’re experiencing has been addressed years ago.

**Comment by bgarr33434** [comment]
not to be rude, but why is it listed if its broken?

**Comment by PromyLOPh** [comment]
I don’t know. Ask your distribution’s package maintainer.
