### ISSUE TITLE
"Error: Internal Error" upon launching pianobar

### ISSUE THREAD

**Issue by ldeforre** [PromyLOPh/pianobar#666]
Upon launching pianobar, I receive the following message:

pi@xxxxxx:~ $pianobar 
Login... Ok.
Get stations... Error: Internal error.
pi@xxxxx:~ $

This error occurs on three different Raspberry Pis, One running Jessie (3B) and two running Stretch (one a 3B and one a 3B+).
Running standard pianobar from apt-get  (20016.06.02)
Was working for over a year.  Started receiving the error message a week ago Sunday.  Started working again this past Saturday (two days ago).  Started receiving this error again today.
Standard config with changes for username and password only.
Web Pandora works fine.

Any ideas what would cause this error message?

**Comment by PromyLOPh** [comment]
This “internal error” is usually sent by Pandora without further information. Thus I/pianobar can’t tell you exactly what is wrong on their end.

**Comment by ldeforre** [comment]
Sure - do you have instructions I can use?

**Comment by ldeforre** [comment]
I'm having troubles building pianobar from scratch.  Its dependencies are giving me trouble.    Do you have a good set of build instructions for Raspbian Stretch?

**Comment by PromyLOPh** [comment]
There’s an old wiki page here: https://github.com/PromyLOPh/pianobar/wiki/Compiling-on-Ubuntu

Where are you stuck at exactly?

**Comment by ldeforre** [comment]
This is what I get when I execute the old wiki command:
pi@WiFi_Pi_1:~ $ sudo apt-get install -y libgcrypt11-dev libjson0-dev libgnutls28-dev libav-tools libao-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package libjson0-dev

**Comment by PromyLOPh** [comment]
libjson-c-dev could be the package missing.

**Comment by ldeforre** [comment]
tried:
 sudo apt-get install libjson-c
still unable to locate it.

**Comment by PromyLOPh** [comment]
Have a look at https://packages.debian.org/search?suite=stretch&searchon=names&keywords=libjson

The binary package is actually called libjson-c3

**Comment by ldeforre** [comment]
I installed libjson-c3 and libjson-c-doc.
did a make clean.  could not find the packages libavcodec, libavformat libavutil libavfilter libavcodec libavformat libavutil libcurl

**Comment by PromyLOPh** [comment]
I’m sorry, but I can’t look up every single package in Debian’s package
dababase for you.
