### ISSUE TITLE
Login...network error...ssl error

### ISSUE THREAD

**Issue by pianotuner** [PromyLOPh/pianobar#667]
### Subject of the issue: 
Briefly describe your issue here. I can login via web browser(pandora) using pia vpn. I can login via pianobar w/ free proxy( control_proxy) and even pianobar for windows w/ pia vpn system wide and control proxy  but using mxlinux 16.1 and pianobar w/ pia vpn system wide, I cannot..I get network error...ssl error. It was working couple of months back so I dont know if its linux(update) or pia (ciphers, etc.)

### Your environment
* version of pianobar  2016
* your Linux distribution and release version mxlinux 16.1  64bit
* ffmpeg/libav version and the flags it was compiled with (if you compiled yourself)   ffmpeg version 2.8.6-1mx150+1   built with gcc 4.9.2 (Debian 4.9.2-10)
* your config file

### Steps to reproduce  
Tell us how to reproduce this issue. using pia vpn and login w/ pianobar

### Expected behaviour
Tell us what should happen.  login...network error...ssl error

### Actual behaviour
Tell us what happens instead, including a copy of all error messages.

**Comment by pianotuner** [comment]
login...network error: ssl connect error

**Comment by edward-p** [comment]
I've tried the 2016 version, no such issue, I think there's something wrong with your VPN. Since I'm alse living outside of the US, I use a [shadowsocks-go](https://github.com/shadowsocks/shadowsocks-go/) for socks5 proxy, and use [sockthttp](https://github.com/icexin/sockhttp) to convert socks5 proxy to a http proxy. Then configure the `control_proxy` in `~/.config/pianobar/config`. Maybe we should add support for socks5 proxy directly, since it's widely used recently. @PromyLOPh

**Comment by PromyLOPh** [comment]
I’m pretty sure pianobar already accepts a socks server as
control_proxy, since libcurl does:
https://curl.haxx.se/libcurl/c/CURLOPT_PROXY.html

**Comment by edward-p** [comment]
Yeah, that's pretty cool, thanks for curl!

**Comment by edward-p** [comment]
@pianotuner
I tried with socks5 proxy. If you want to set up a socks5 proxy for pianobar just add a line to `~/.config/pianobar/config ` like this:

```
control_proxy = socks5://server_ip:port
```

`control_proxy` is a feature that provided by libcurl.

 So pianobar support all types of proxy that `control_proxy` supports here [https://curl.haxx.se/libcurl/c/CURLOPT_PROXY.html](https://curl.haxx.se/libcurl/c/CURLOPT_PROXY.html)

**Comment by pianotuner** [comment]
Hello again 

This is a different subject. I was wondering what services does pianobar for windows use to make it run properly. I ask because i have a build of windows 10 i like,,,stripped down and smooth. I have pianobar running on another 7/10 but they are untouched. I have read a thread before but cannot seem to find it again something to do with pianobar uses windows media...? to run in windows and I have tried to use player = ds and I am always behind vpn. 

Thank you

**Comment by PromyLOPh** [comment]
The Windows port is not developed here. Head over to https://github.com/thedmd/pianobar-windows/issues
