### ISSUE TITLE
Change the user agent?

### ISSUE THREAD

**Issue by midicase** [PromyLOPh/pianobar#671]
Poking around at the stream I'm getting a paltry 64 kbps rate, even though being a premium subscriber and high-quality set.  Is Pandora using the user-agent to also determine which additional constraints to place on the the rate?

Do I need to do something else to get 192 kbps offered to the flash client?

**Comment by PromyLOPh** [comment]
No, see https://github.com/PromyLOPh/pianobar/issues/634#issuecomment-418995188

**Comment by midicase** [comment]
I see the blurb in the Pandora page:

**Change Audio Quality on Mobile**
If you have a free account or Pandora Plus subscriber:

- Start from the Now Playing screen, and touch the back arrow in the upper left.
- Tap the menu icon and select Settings. 
- Then select Advanced. 
- Next, under Cell Network Audio Quality either toggle the switch for High quality audio or disable it for normal quality audio.

They don't really say what normal or High are. Is this 32 and 64?

My question still stands for mimicking the flash client since it is capable of getting better quality:

**Change Audio Quality on the Web**

- Pandora on the Web plays 64k AAC+ for free listeners and 192kbps for Pandora Plus and Pandora Premium subscribers.

**Comment by PromyLOPh** [comment]
I’m not a subscriber and therefore can only relay what the other user
wrote in the comment I refered to above. Mimicking the flash client
(didn’t they move to HTML5 a few years ago?) is more complicated than
just changing the user agent. It uses a different API, see
https://6xq.net/pandora-apidoc/rest/
