### ISSUE TITLE
SSL Connect Error

### ISSUE THREAD

**Issue by grayhavenmotel** [PromyLOPh/pianobar#674]
### Subject of the issue
Hello. We are getting the following error after successfully receiving several playlists:

`Receiving new Playlist... Network error: SSL connect error`

At this point we just quit and restart and everything is fine again for a few playlists then we get error again. This just started happening within the last two weeks.

### Your environment
* version of pianobar = apt version (2017.08.30)
* Lubuntu 18.04
* ffmpeg 3.4.4

### Steps to reproduce
Let play for about an hour.

### Expected behaviour
playlists should continue to be received and played.

### Actual behaviour
After successfully receiving several playlists the following error occurs:

`Receiving new Playlist... Network error: SSL connect error`

**Comment by grayhavenmotel** [comment]
i just build and and running 2018.06.22. so far so good. 

how can we get newer version in apt repo?

**Comment by OvalPiston** [comment]
I am experiencing this also on my pianobar. How do we get the newer version?

@grayhavenmotel - how did you build 2018.06.22?

**Comment by grayhavenmotel** [comment]
just running `make` works fine but you will get a bunch of errors if the dev files are not installed. so I just installed each dev package one-by-one according to errors until it all built.

let me know if you need more verbose instructions.

**Comment by gms8994** [comment]
I'm getting this error just recently on 2018.06.22 from Homebrew. Earlier today I could play tracks just fine.

**Comment by rjpcomputing** [comment]
I get this error all day long. I can only have Pianobar run for anywhere from 15 min to 3 hours. It used to stream 24 hours a day for months at a time. I am running both the 2016.06.02 and the latest out of Git.

Changed hardware (I am running on a Raspberry Pi 2 and now a 3). I have been fighting this for almost 2 weeks. I even had my internet provider come out and make sure it was not my internet.

I have seen this at login and most often at `Receiving new Playlist...`

**Comment by rjpcomputing** [comment]
@PromyLOPh - Here is a log of playback and what happens after it quits. I pressed 'n' for next track and it said no station selected.
```
$ pianobar
Welcome to pianobar (2018.06.22-dev)! Press ? for a list of commands.
(i) Control fifo at /var/www/.config/pianobar/ctl opened
(i) Login... Ok.
(i) Get stations... Ok.
         0)  Q  QuickMix
         1)     60s, 70s, and 80s Hits Radio
         2)     Christian Metal Radio
         3) q   Christian Rock Radio
         4)     Classical Christmas Radio
         5) q   Dance Radio
         6)     Holiday Radio
         7)     Kids Radio
         8) q   Pop Fitness Radio
         9)     Swing Radio
        10)     Symphonic Radio
        11) q   The Black Keys Radio
        12) q   TobyMac Radio
        13) q   Today's Hits Radio
[?] Select station: q
         0)  Q  QuickMix
[?] Select station: 0
|>  Station "QuickMix" (1257597005407931927)
(i) Receiving new playlist... Ok.
|>  "Happier" by "Marshmello & Bastille" on "Happier (Single)" @ Today's Hits Radio
|>  "Your Woman" by "White Town" on "Women In Technology" @ The Black Keys Radio
|>  "Exhibition" by "Falling Up" on "Dawn Escapes" @ Christian Rock Radio
|>  "Lights (Bassnectar Remix)" by "Ellie Goulding" on "Lights (The Remixes) Pt. 1 EP" @ Pop Fitness Radio
(i) Receiving new playlist... Ok.
|>  "Mind Of A Beast" by "The Glitch Mob" on "Love Death Immortality" @ Dance Radio
|>  "1-800-273-8255 (Feat. Alessia Cara & Khalid)" by "Logic" on "Everybody" @ Today's Hits Radio
|>  "Centuries" by "Fall Out Boy" on "American Beauty/American Psycho" @ Pop Fitness Radio
|>  "I'll Keep On (Feat. Jeremiah Carlson)" by "NF" on "Mansion" @ TobyMac Radio
(i) Receiving new playlist... Ok.
|>  "Never Let Me Go" by "Florence + The Machine" on "Ceremonials" @ The Black Keys Radio
|>  "I Will Wait" by "Mumford & Sons" on "Babel (Deluxe Edition)" <3 @ Pop Fitness Radio
|>  "Lost In Japan (Remix)" by "Shawn Mendes & Zedd" on "Lost In Japan (Remix) (Single)" @ Today's Hits Radio
|>  "Out Of Hell" by "Skillet" on "Unleashed" @ Christian Rock Radio
(i) Receiving new playlist... Ok.
|>  "Smile?" by "The Crystal Method" on "Divided By Night" @ Dance Radio
|>  "Believe" by "The Bravery" on "The Sun And The Moon" <3 @ The Black Keys Radio
|>  "Eastside" by "Benny Blanco, Halsey & Khalid" on "Eastside (Single)" @ Today's Hits Radio
|>  "Connection" by "OneRepublic" on "Connection (Single)" @ Pop Fitness Radio
(i) Receiving new playlist... Network error: SSL connect error
/!\ No station selected.
```

**Comment by PromyLOPh** [comment]
I can’t reproduce this error with git HEAD. Also, since the issue seems
to be transient I doubt there is anything I can fix on my end. So my
guess would be an issue on Pandora’s end or somewhere inbetween (proxy).

**Comment by rjpcomputing** [comment]
I don't use a proxy of any kind. I am a Pandora One subscriber.

I started doing a keep alive script to restart Pianobar and it needs to be restarted at least 30+ times a day. I am using a delay and checking for actual sound output from the sound card to determine if Pianobar is working.

**Comment by grayhavenmotel** [comment]
> I started doing a keep alive script to restart Pianobar

@rjpcomputing actually sounds nifty and  useful. mind sharing script?
