### ISSUE TITLE
pianobar stops after 1-3 seconds of first song and process hangs

### ISSUE THREAD

**Issue by RevCivic** [PromyLOPh/pianobar#678]
Pianobar will start, log in, and begin playing a song, but instantly cuts out. I have tried reinstalling many times. The time for the song does not change at all in the course of it playing the song (maybe 1-3 seconds at most). It almost seems as when it attempts to update something it breaks. I am able to see the menu items by pressing "?" for a few moments (not sure exact time) but that will also crash as soon as I attempt to use "q" to quit. I have had to manually kill the process to close pianobar. I have done various amounts of reboots, updates, upgrades, rpi-updates. I am not sure what files would be most helpful to share, but please let me know and I will be happy to provide.

### Your environment
Pianobar Ver. 2018.06.22-dev
Raspbian Stretch Kernel 4.14.94-v7+
ffmpeg version N-92238-gb7b3e8c5c7 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 6.3.0 (Debian 6.3.0-18+deb9u1) 20170516
  configuration:
  libavutil      56. 19.101 / 56. 19.101
  libavcodec     58. 33.102 / 58. 33.102
  libavformat    58. 19.101 / 58. 19.101
  libavdevice    58.  4.105 / 58.  4.105
  libavfilter     7. 37.100 /  7. 37.100
  libswscale      5.  2.100 /  5.  2.100
  libswresample   3.  2.100 /  3.  2.100

user = *********@******.com
password = *******
audio_quality = high

### Steps to reproduce
run make, make config file, run "pianobar"

### Expected behaviour
pianobar should play full songs

### Actual behaviour
No errors, process seems to hang up, song stops playing after 1-3 seconds, time remaining/total time is never updated, "q" does not work to quit the program.

**Comment by edward-p** [comment]
Will you be able to press "s" to reselect a station?

**Comment by PromyLOPh** [comment]
Have a look at issue #672 – it seems to be quite similar. The
quintessence is: Disable compiler optimizations when building (-O0).
Also, please test if the master branch exhibits this behavior as well.

**Comment by vandys** [comment]
Happens here on trunk, with -O0 or -O2 no diff.  Interestingly, it was working, then I went premium
and it stopped working.  I changed config to quality low and it went back to working (though with
reduced audio quality, of course).  So it's a problem ticked by the high quality audio rate.

**Comment by PromyLOPh** [comment]
That is weird. Can you check out the branch `debug`, compile it, run
`PIANOBAR_DEBUG=1 ./pianobar` and post the last 30/40 lines here?

**Comment by vandys** [comment]
I had to remove NDEBUG from the Makefile, too.
Here's the output.
[debug.txt](https://github.com/PromyLOPh/pianobar/files/2848978/debug.txt)

**Comment by PromyLOPh** [comment]
Did you set buffer_seconds to zero in your config file? (minHealth is
zero) Can you try different values (5, 10, 1000, 10000, …)?

**Comment by vandys** [comment]
No, no config entry for buffer_seconds.  I set it to 100 and it plays for about that many seconds before stopping.  The time counter does not change during all of that; it sticks at the initial (track length)
time value.  I'm wondering if the fact that minHealth is 64 bits is messing with the debug output,
rather than telling the true story.  I'll look into that and post more if I find anything.

**Comment by vandys** [comment]
Yup, those were 64-bit long long's, fixed the format.
So here's a new debug log.
[debug.txt](https://github.com/PromyLOPh/pianobar/files/2849541/debug.txt)

**Comment by PromyLOPh** [comment]
Guess I should be using PRIxx macros when printing integer values, oops.

So, to get this right: Debug output continues even after audio output
stopped and there’s no message saying “ao player is waiting for more
frames …” right before the music stops playing (example:
https://github.com/PromyLOPh/pianobar/issues/672#issuecomment-453180460)?

What OS/machine are you running pianobar on, @vandys?

**Comment by vandys** [comment]
I apologize, let me include the complete debug log of a hang, which does indeed end with:

ao player is waiting for more frames after code -11 (Resource temporarily unavailable)

and the (never counting down) time marker.

This is 686 Linux (Mint 19).

[debug.txt](https://github.com/PromyLOPh/pianobar/files/2851557/debug.txt)

**Comment by RevCivic** [comment]
I just got back to looking into this, I did recompile, same issues, however, setting the audio quality to low did seem to resolve the issue as a temporary solution. Going to test it for a while to see if any errors spring up.

**Comment by PromyLOPh** [comment]
I pushed fixes into the branch fixes-678. Please give it a try.
Apparently this is not a threading issue as I thought initially. I’ve
simply been using the wrong time_base to calculate timestamps, which
never was an issue with AAC/MP4.

**Comment by vandys** [comment]
Nice!  Fixes the problem here.

**Comment by PromyLOPh** [comment]
Release 2019.02.14 fixes this issue.
