### ISSUE TITLE
current version (2019.02.14) build fails

### ISSUE THREAD

**Issue by PhilT001** [PromyLOPh/pianobar#680]
I'm trying to build the current version (2019.02.14) but the Build fails with the following:

(Nokia-N810-43-7) pianobar-2019.02.14 $ make
    CC  src/player.c
src/player.c: In function `BarAoPlayThread':
src/player.c:522: warning: implicit declaration of function `av_buffersink_get_time_base'
src/player.c:522: error: incompatible type for argument 1 of `av_q2d'
Makefile:107: recipe for target 'src/player.o' failed
make: *** [src/player.o] Error 1

Device: Nokia N810 tablet (2008)

Processor: ARMv6-compatible processor rev 2 (v6l)
CPU architecture: 6TEJ

gcc version 3.4.4 (release) (CodeSourcery ARM 2005q3-2)

ldd (GNU libc) 2.5

Linux (Debian based) (2008)

ffmpeg: 3.1.10 (minimal build)

I currently have version 2018.06.22 installed/working on this device.

**Comment by PromyLOPh** [comment]
ffmpeg 3.1 is pretty old and not maintained. I’ve tested pianobar with
3.4 and 4.1. Can you upgrade?

**Comment by PhilT001** [comment]
Thanks for the suggestion. 3.4 fails to build (missing linux/perf_event.h header file) but 4.1 built OK. This has allowed me to build the latest version of pianobar successfully.
