### ISSUE TITLE
avcodec API changes

### ISSUE THREAD

**Issue by vandys** [PromyLOPh/pianobar#681]
### Subject of the issue
While trying to build on Ubuntu Xenial, I get:

unknown type name 'AVCodecParameters'

among many related compilation errors.  It appears the avcodec API has
changed quite a bit.  For instance, avcodec_send_packet is no longer
known as a function.

### Your environment
* verified on trunk
* Ubuntu Xenial amd64
* libavcodec-dev_7%3a2.8.15-0ubuntu0.16.04.1_amd64

### Steps to reproduce
Just try to build...

**Comment by PromyLOPh** [comment]
Xenial ships ffmpeg 2.8, which is old and lacks important APIs. I can’t support that version right now, but if you want to provide a patch, feel free to submit a pull request and I’ll have a look.

**Comment by vandys** [comment]
Not being conversant with the ways of libavcodec, I thought I was filing on a _newer_ API.
Ubuntu is mostly being phased out here, and I'm happy that you're not going to work on an
outdated API.  Thanks!
