### ISSUE TITLE
Compile error in player.c

### ISSUE THREAD

**Issue by wellsa-usa** [PromyLOPh/pianobar#682]
### Subject of the issue
I downloaded the latest pianobar from github: https://github.com/PromyLOPh/pianobar :
(git clone https://github.com/PromyLOPh/pianobar.git).
After i run sudo make clean, then make, I get the following error:
 CC src/main.c
 CC src/player.c
src/player.c: In function ‘BarAoPlayThread’:
src/player.c:522:34: warning: implicit declaration of function ‘av_buffersink_get_time_base’ [-Wimplicit-function-declaration]
 const double timeBase = av_q2d (av_buffersink_get_time_base (player->fbufsink)),
 ^~~~~~~~~~~~~~~~~~~~~~~~~~~
src/player.c:522:34: error: incompatible type for argument 1 of ‘av_q2d’
In file included from /usr/include/arm-linux-gnueabihf/libavutil/avutil.h:292:0,
 from /usr/include/arm-linux-gnueabihf/libavutil/samplefmt.h:24,
 from /usr/include/arm-linux-gnueabihf/libavcodec/avcodec.h:31,
 from src/player.c:45:
/usr/include/arm-linux-gnueabihf/libavutil/rational.h:104:22: note: expected ‘AVRational {aka struct AVRational}’ but argument is of type ‘int’
static inline double av_q2d(AVRational a){
 ^~~~~~
Makefile:107: recipe for target 'src/player.o' failed

### Your environment
* version of pianobar: 2019.02.14-dev
* your Linux distribution and release version: Linux 4.14.98-v7+ armv7l
* ffmpeg/libav version and the flags it was compiled with (if you compiled yourself)
(I did not compile it myself):
ffmpeg version 3.2.12-1~deb9u1+rpt1 Copyright (c) 2000-2018 the FFmpeg developers
built with gcc 6.3.0 (Raspbian 6.3.0-18+rpi1+deb9u1) 20170516
configuration: --prefix=/usr --extra-version='1~deb9u1+rpt1' --toolchain=hardened --libdir=/usr/lib/arm-linux-gnueabihf --incdir=/usr/include/arm-linux-gnueabihf --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libebur128 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-omx-rpi --enable-mmal --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libiec61883 --arch=armhf --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
libavutil      55. 34.101 / 55. 34.101
libavcodec     57. 64.101 / 57. 64.101
libavformat    57. 56.101 / 57. 56.101
libavdevice    57.  1.100 / 57.  1.100
libavfilter     6. 65.100 /  6. 65.100
libavresample   3.  1.  0 /  3.  1.  0
libswscale      4.  2.100 /  4.  2.100
libswresample   2.  3.100 /  2.  3.100
libpostproc    54.  1.100 / 54.  1.100

* your config file ? which config file?

### Steps to reproduce
sudo make, make

### Expected behaviour
clean compile
### Actual behaviour
 CC src/main.c
 CC src/player.c
src/player.c: In function ‘BarAoPlayThread’:
src/player.c:522:34: warning: implicit declaration of function ‘av_buffersink_get_time_base’ [-Wimplicit-function-declaration]
 const double timeBase = av_q2d (av_buffersink_get_time_base (player->fbufsink)),
 ^~~~~~~~~~~~~~~~~~~~~~~~~~~
src/player.c:522:34: error: incompatible type for argument 1 of ‘av_q2d’
In file included from /usr/include/arm-linux-gnueabihf/libavutil/avutil.h:292:0,
 from /usr/include/arm-linux-gnueabihf/libavutil/samplefmt.h:24,
 from /usr/include/arm-linux-gnueabihf/libavcodec/avcodec.h:31,
 from src/player.c:45:
/usr/include/arm-linux-gnueabihf/libavutil/rational.h:104:22: note: expected ‘AVRational {aka struct AVRational}’ but argument is of type ‘int’
static inline double av_q2d(AVRational a){
 ^~~~~~
Makefile:107: recipe for target 'src/player.o' failed

**Comment by wellsa-usa** [comment]
I forgot to add, this is running on a Raspberry Pi 3 - Model B+ - 1.4GHz Cortex-A53.
I have the same version of s/w on an older Raspberry Pi 3 - Model B - ARMv8 with 1G RAM and it compiles and runs just fine.

**Comment by PromyLOPh** [comment]
See #681
