### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by Malarne** [PromyLOPh/pianobar#689]
### Subject of the issue
I was trying to run pianobar on my win10 computer, after setting up some free proxy to have it not throw "pandora not available in your country" i faced a new error: Segmentation fault (https://imgur.com/a/xT1fFJI)

### Your environment
* version of pianobar: 2019.05.03
* Windows 10
* ffmpeg/libav version and the flags it was compiled with (if you compiled yourself) -> no idea
* your config file
control_proxy = http://my.proxy.url:port/
user = my@email
password = MyAmazingP4SsW0rD

### Steps to reproduce
Try setting up a control_proxy with some free http proxy found on the web ?

### Expected behaviour
pianobar run fine and play music

### Actual behaviour
Segmentation fault

**Comment by PromyLOPh** [comment]
The Windows-port is a separate project and maintained over here: https://github.com/thedmd/pianobar-windows
