### ISSUE TITLE
Choppy Audio on Ubuntu 18.04 WSL

### ISSUE THREAD

**Issue by jarussell** [PromyLOPh/pianobar#690]
### Subject of the issue
Audio playback is choppy on the Windows Subsystem for Linux. It takes 3-4 seconds (variable) to play 1 second of music in pianobar. This same behavior is not experienced with cmus, paplay, nor vlc.

### Your environment
* Tried 2 different versions of pianobar building from source (2019.02.14-dev) and from the Ubuntu repository (2017.08.30)
* Linux Distribution is Ubuntu 18.04.2 LTS but it is in the Windows Subsystem for Linux which has many differences
* ffmpeg/libav version and the flags it was compiled with (if you compiled yourself)
ffmpeg version 3.4.6-0ubuntu0.18.04.1 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.3.0-16ubuntu3)
  configuration: --prefix=/usr --extra-version=0ubuntu0.18.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-librsvg --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
  libavutil      55. 78.100 / 55. 78.100
  libavcodec     57.107.100 / 57.107.100
  libavformat    57. 83.100 / 57. 83.100
  libavdevice    57. 10.100 / 57. 10.100
  libavfilter     6.107.100 /  6.107.100
  libavresample   3.  7.  0 /  3.  7.  0
  libswscale      4.  8.100 /  4.  8.100
  libswresample   2.  9.100 /  2.  9.100
  libpostproc    54.  7.100 / 54.  7.100
* Tried both with and without a config file, behavior is the same and should be reproducible without a config file

### Steps to reproduce

1.  Install pulseaudio server in Windows by extracting https://github.com/kitor/wsl/blob/master/pulse6.zip to any directory
2.  Add "default-server = 127.0.0.1" to /etc/pulse/client.conf (within the WSL environment)
3.  sudo apt-get install --no-install-recommends libpulse0 pavucontrol pianobar (within the WSL environment)
4.  Start the pulseaudio server on windows (with a flag so that it does not timeout ("--exit-idle-time=-1")
5.  Run pavucontrol to ensure that the pulseaudio server is running and has a device
6.  Play a song with cmus to make sure that pulseaudio is not the problem
7.  Run pianobar, login, and select station

### Expected behaviour
Music should play with 1 second lapsing as it plays 1 second's worth of music

### Actual behaviour
Music plays, but it plays 1/3-1/4 of a second, pauses for a little bit, and plays another fraction of a second. It takes 3-4 seconds to play 1 actual second of music.

The only error that occurs is "shared memfd open() failed: Function not implemented" but it occurs right before music starts playing (the music still plays, just slowly).

**Comment by PromyLOPh** [comment]
Are you aware there’s a native Windows port of pianobar available at
https://github.com/thedmd/pianobar-windows ?

**Comment by jarussell** [comment]
I was not aware. It seems like it doesn't really solve the use case that I am looking for because in WSL if I start the windows binary in tmux and detach it to get a headless version like I would on linux, it crashes. I suppose I can report it upstream at WSL.
