### ISSUE TITLE
Has anyone tried to compile this on Buster?  have you had success? 

### ISSUE THREAD

**Issue by kentisevil** [PromyLOPh/pianobar#691]
### Subject of the issue
Attempting to compile on RPiZeroW on buster

### Your environment
* latest download from github
* your Linux distribution and release version buster

pi@EvilPhatBeat:~ $ lsb_release -a
No LSB modules are available.
Distributor ID: Raspbian
Description:    Raspbian GNU/Linux 10 (buster)
Release:        10
Codename:       buster

* ffmpeg/libav version and the flags it was compiled with (if you compiled yourself)
ffmpeg -version
ffmpeg version 4.1.4-1+rpt7~deb10u1 Copyright (c) 2000-2019 the FFmpeg developers
built with gcc 8 (Raspbian 8.3.0-6+rpi1)
configuration: --prefix=/usr --extra-version='1+rpt7~deb10u1' --toolchain=hardened --incdir=/usr/include/arm-linux-gnueabihf --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-omx-rpi --enable-mmal --enable-neon --enable-rpi --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared --libdir=/usr/lib/arm-linux-gnueabihf --cpu=arm1176jzf-s --arch=arm
libavutil      56. 22.100 / 56. 22.100
libavcodec     58. 35.100 / 58. 35.100
libavformat    58. 20.100 / 58. 20.100
libavdevice    58.  5.100 / 58.  5.100
libavfilter     7. 40.101 /  7. 40.101
libavresample   4.  0.  0 /  4.  0.  0
libswscale      5.  3.100 /  5.  3.100
libswresample   3.  3.100 /  3.  3.100
libpostproc    55.  3.100 / 55.  3.100

* your config file
not applicable

### Steps to reproduce
Tell us how to reproduce this issue.
just download buster and try to compile / install required dependencies 
### Expected behaviour
when attempting to install dependencies I expect apt to either find them or suggest alternatives 
### Actual behaviour
package not found:

pi@EvilPhatBeat:~/pianobar $ sudo apt install gmake pthreads libao libcurl gcrypt json-c ffmpeg -y
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package gmake
E: Unable to locate package pthreads
E: Unable to locate package libao
E: Unable to locate package libcurl
E: Unable to locate package gcrypt
E: Unable to locate package json-c

**Comment by PromyLOPh** [comment]
The debian package description file says you need:
debhelper-compat, libao-dev, libavcodec-dev, libavfilter-dev, libavformat-dev, libavutil-dev, libcurl4-gnutls-dev, libgcrypt20-dev, libjson-c-dev, libpth-dev, pkg-config
Note there’s a prebuilt binary available for debian buster, just `apt-get install pianobar`

**Comment by kentisevil** [comment]
let me try that - thanks for the quick response - my problem with the prebuilt on my rasberry pi's it constant breaking up....

**Comment by kentisevil** [comment]
well that solved one problem - I can compile it now - but it is still horribly laggy skippy even on my raspberry pi 4 through the HDMI port .....   I don't remember having this much skippy laggy on my Pi2 - weird......

**Comment by kentisevil** [comment]
thanks for your help!
