### ISSUE TITLE
Ellipsis in Song Information Causes Internal Error

### ISSUE THREAD

**Issue by kbmorris** [PromyLOPh/pianobar#694]
### Your environment
pianobar (2019.05.03)
thedmd/pianobar-windows-build

### Steps to reproduce
Play a song with ellipsis (...) in the song information.
In the example the Album Title is "As Told on The Eve Of..."

### Expected behaviour
The song information should appear with the ellipsis.

### Actual behaviour
The song information appears with the ellipsis replaced with the text "Internal error, unknown action 0."

|>  "Thomas Edison Invents The Lazy Dance" by "Quenum, Lee Van Dowski" on "As Told On The Eve OfInternal error, unknown action 0."

**Comment by PromyLOPh** [comment]
pianobar for Windows differs significantly from the version offered here and I cannot reproduce the issue. Please report it here: https://github.com/thedmd/pianobar-windows/issues
