### ISSUE TITLE
display elapsed time instead of remaining time in timestamp

### ISSUE THREAD

**Issue by github-account1111** [PromyLOPh/pianobar#699]
### Subject of the issue
I want `[elapsed time]/[length]` as opposed to `-[remaining time]/[length]`.

### Your environment
* version of pianobar 2020.04.20
* your Linux distribution and release version Windows 10
* ffmpeg/libav version and the flags it was compiled with (if you compiled yourself)
* your config file

### Steps to reproduce
Play a song

### Expected behaviour
`[elapsed time]/[length]` in the timestamp field.

### Actual behaviour
`[-remaining time]/[length]` in the timestamp field.

**Comment by PromyLOPh** [comment]
Should be possible to extend BarMainPrintTime, there’s already a format string (`format_msg_time`).
