### ISSUE TITLE
(i) Get stations... Error: Internal error.

### ISSUE THREAD

**Issue by scoaste** [PromyLOPh/pianobar#701]
### Subject of the issue
(i) Get stations... Error: Internal error.

### Your environment
* version of pianobar
2019.02.14
* your Linux distribution and release version
cat /proc/version
Linux version 5.4.0-42-generic (buildd@lgw01-amd64-038) (gcc version 9.3.0 (Ubuntu 9.3.0-10ubuntu2)) #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020
* ffmpeg/libav version and the flags it was compiled with (if you compiled yourself)
n/a
* your config file
password = ***
autostart_station = ***
audio_quality = high
ca_bundle = /etc/ssl/certs/ca-certificates.crt
### Steps to reproduce
pianobar
### Expected behaviour
music
### Actual behaviour
error

**Comment by scoaste** [comment]
cat /var/log/apt/history.log
Start-Date: 2020-08-03  17:25:55
Upgrade: libgs9:amd64 (9.50~dfsg-5ubuntu4, 9.50~dfsg-5ubuntu4.1), ghostscript:amd64 (9.50~dfsg-5ubuntu4, 9.50~dfsg-5ubuntu4.1), libwebkit2gtk-4.0-37:amd64 (2.28.3-0ubuntu0.20.04.1, 2.28.4-0ubuntu0.20.04.1), ghostscript-x:amd64 (9.50~dfsg-5ubuntu4, 9.50~dfsg-5ubuntu4.1), libgs9-common:amd64 (9.50~dfsg-5ubuntu4, 9.50~dfsg-5ubuntu4.1), gir1.2-webkit2-4.0:amd64 (2.28.3-0ubuntu0.20.04.1, 2.28.4-0ubuntu0.20.04.1), libjavascriptcoregtk-4.0-18:amd64 (2.28.3-0ubuntu0.20.04.1, 2.28.4-0ubuntu0.20.04.1), gir1.2-javascriptcoregtk-4.0:amd64 (2.28.3-0ubuntu0.20.04.1, 2.28.4-0ubuntu0.20.04.1)
End-Date: 2020-08-03  17:26:13

Start-Date: 2020-08-04  17:30:23
Upgrade: whoopsie:amd64 (0.2.69, 0.2.69ubuntu0.1), libssh-4:amd64 (0.9.3-2ubuntu2, 0.9.3-2ubuntu2.1), libwhoopsie0:amd64 (0.2.69, 0.2.69ubuntu0.1), apport:amd64 (2.20.11-0ubuntu27.4, 2.20.11-0ubuntu27.6), ppp:amd64 (2.4.7-2+4.1ubuntu5, 2.4.7-2+4.1ubuntu5.1), python3-apport:amd64 (2.20.11-0ubuntu27.4, 2.20.11-0ubuntu27.6), libssh-gcrypt-4:amd64 (0.9.3-2ubuntu2, 0.9.3-2ubuntu2.1), apport-gtk:amd64 (2.20.11-0ubuntu27.4, 2.20.11-0ubuntu27.6), python3-problem-report:amd64 (2.20.11-0ubuntu27.4, 2.20.11-0ubuntu27.6)
End-Date: 2020-08-04  17:30:39

Start-Date: 2020-08-04  17:41:27
Remove: webext-ublock-origin:amd64 (1.22.2+dfsg-1)
Purge: chromium-browser:amd64 (83.0.4103.97-0ubuntu0.20.04.1), chromium-ublock-origin:amd64 (1.22.2+dfsg-1)
End-Date: 2020-08-04  17:41:30

Start-Date: 2020-08-05  17:34:07
End-Date: 2020-08-05  17:34:07

Start-Date: 2020-08-05  17:39:52
Upgrade: libmysqlclient21:amd64 (8.0.21-0ubuntu0.20.04.3, 8.0.21-0ubuntu0.20.04.4)
End-Date: 2020-08-05  17:39:54

Start-Date: 2020-08-05  17:40:11
Purge: webext-ublock-origin:amd64 ()
End-Date: 2020-08-05  17:40:12

**Comment by PromyLOPh** [comment]
I can’t reproduce this. Transient error?

**Comment by scoaste** [comment]
Today it works.  Must have been on their end.
