### ISSUE TITLE
Pausing a song for more than a few seconds breaks playback

### ISSUE THREAD

**Issue by nneul** [PromyLOPh/pianobar#702]
### Subject of the issue

I've seen this ever since I started using pianobar - just now getting around to reporting.

Playback hangs/stops after a little while if you pause.

### Your environment
* 0f856e8c8721537a0c945b7036351e4073dc0b04 - head of master a week or so ago
* Ubuntu 18
* from repos - 3.4.8

```
password = xxxxxxxxxxxxxxx
user = xxxxxxxxxxxxxxxxx
audio_quality = high
autostart_station = 3563273528223108439
event_command = /users/nneul/bin/lastfm-scrobble
```

### Steps to reproduce

Pause a song. 
Wait 30-40 seconds (i.e. if you took a phone call/whatever)
Unpause
Song will continue to play, possibly up until buffer empty - and will then hang. 
It may or may not recover after this if you continue to wait.

### Expected behaviour
Should be able to pause and resume.

It'd be tolerable if it broke playback of the current song and skipped to next, but as it is now, it breaks and only way to really recover is to restart app. 

### Actual behaviour

After unpausing - gets about 20 seconds of playback, then just stops. No error message. 
Sometimes it seems like if I let it sit there, it stutters after about another 10-15 seconds and then skips to next song.

**Comment by PromyLOPh** [comment]
By default it should time out after 30 seconds. You can decrease this by
setting the `timeout` option in your config file. If it does not you can
also force a reconnect by pressing Ctrl-C *once*.

**Comment by nneul** [comment]
Yes, both of those options significantly improve experience. Thank you!

**Comment by buu700** [comment]
I'm not sure if it's a change from the latest release in December or maybe something on Pandora's end, but for whatever reason, leaving a song on pause for an extended period of time and then unpausing has been working for me lately. After a few seconds it'll stutter, but then it continues playing the song to completion.
