### ISSUE TITLE
On 

### ISSUE THREAD

**Issue by baconicsynergy** [PromyLOPh/pianobar#703]
### Subject of the issue
On Alpine Linux and postmarketOS, attempting to play a radio station results in various libao and alsa errors

### Your environment
pianobar-2020.04.05-r1
Alpine Linux edge 3.13.0_alpha20200917
postmarketOS 1.22.2
ffmpeg-4.3.1-r0
gst-libav-1.16.2-r2
libao-1.2.2-r0

/etc/libao.conf

> default_driver=pulse

or

> default_driver=alsa
> dev=default

### Steps to reproduce
Install the pianobar apk package on either OS, launch pianobar, login, attempt to play radio station

### Expected behaviour
The station should play and there should be no error messages

### Actual behaviour
No playback - error messages are given depending on what is in /etc/libao.conf

If "default_driver=alsa",

> ao_alsa ERROR: Unable to open ALSA device 'default' for playback => Invalid argument
> /!\ Cannot open audio device.

If "default_driver=pulse",

> ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.front
> ao_alsa WARNING: Unable to open surround playback.  Trying default device...
> ao_alsa ERROR: Unable to open ALSA device 'default' for playback => Invalid argument
> /!\ Cannot open audio device.

**Comment by PromyLOPh** [comment]
This looks like a configuration error and from the error messages I can’t tell you what might be wrong. You can try to set `debug=1` in your libao.conf and see if it has something interesting to say.
