### ISSUE TITLE
Audio slowing down

### ISSUE THREAD

**Issue by Jefronty** [PromyLOPh/pianobar#706]
On a Raspberry Pi 3 B+ pianobar starts fine, but audio gradually slows down.
The pi is connected via Ethernet and audio_quality is set to medium.  Any idea why it can’t keep a quality stream?
This happens when no UI is loaded and no other programs running other than normal services that start on boot.
The OS is Raspbian Buster and pianobar is 2019.02.14

**Comment by PromyLOPh** [comment]
Can you try version 2020.11.28?

**Comment by Jefronty** [comment]
the version I have is the latest in the apt-get repo, but I'll try to update it manually and see if that makes a difference
