### ISSUE TITLE
zsh: illegal hardware instruction  pianobar

### ISSUE THREAD

**Issue by lewisdonofrio** [PromyLOPh/pianobar#707]
When you install pianobar from a brew on OSX 10.15.7 you get the message "zsh: illegal hardware instruction  pianobar" and it will not play like it should.

### Your environment
* 2020.11.28
* Kernel: Darwin 19.6.0 x86_64 bits: 64 compiler: N/A Console: tty 000 OS: Darwin 19.6.0
* ffmpeg version 4.3.1/avplay version 12.3
* ad-hoc

### Steps to reproduce
as outlined in paste.ubuntu outlines, install OSX 10.15.7 run Homebrew 2.6.2 then brew install pianobar from OSX Terminal and run pianobar login select a station and bam "illegal hardware instruction"

### Expected behaviour
Should have played nice music in OSX

### Actual behaviour
Tell us what happens instead, including a copy of all error messages.
https://paste.ubuntu.com/p/YyT5Kv86yr/

**Comment by PromyLOPh** [comment]
This looks more like an issue with compiler flags. Could you report this to homebrew please?
