### ISSUE TITLE
New Station Modes

### ISSUE THREAD

**Issue by BeaverTek** [PromyLOPh/pianobar#711]
The web interface now has:

*    Crowd Faves
*    Discovery
*    Deep Cuts
*    Newly Released
*    Artist Only

It'd be great if we could not only select one of these, but multiple simultaneously.

Also pinged Pithos about this: https://github.com/pithos/pithos/issues/641

**Comment by PromyLOPh** [comment]
You can change the mode by pressing `=` and then `m` (default keys), but you cannot select multiple modes at the same time, because the API does not allow that.
