### ISSUE TITLE
Most proxies don't seem to work

### ISSUE THREAD

**Issue by ufuksarp** [PromyLOPh/pianobar#713]
Most proxies don't work. Only a very low percentage of the ones that gets a pass on various proxy checkers seem to work. I also noticed the ones that work often have low, transparent, no anonymity.

**Comment by PromyLOPh** [comment]
Can you elaborate what you are commenting on? There are no proxies here.

**Comment by PromyLOPh** [comment]
Sure, but pianobar itself does not provide any proxies. You can set it up to use one via `control_proxy`, but finding one that works is up to you. The proxy feature itself is working fine from my experience and it’s also provided by libcurl (i.e. there is no proxy handling code in pianobar itself).
