### ISSUE TITLE
Authentication not possible using paid account

### ISSUE THREAD

**Issue by bkw777** [PromyLOPh/pianobar#714]
Authentication (paid account) suddenly no longer works with pianobar, or pandoroid, or pithos, latest versions of all, and all working up to an hour ago. Yet the web page works at the same time, same network, same pc.

So Pandora changed something?
https://github.com/pithos/pithos/issues/654

**Comment by PromyLOPh** [comment]
It works for me with a free account (I don’t have a paid testing account). If this is not a transient error, could you please run `PIANOBAR_DEBUG=1 pianobar 2> error.log` and send me error.log in private (lars+pianobar@6xq.net) after removing your credentials and auth token?

**Comment by jmkinny** [comment]
Stopped working yesterday for me as well.  I ran the snippet above, but error.log was created but empty.

**Comment by PromyLOPh** [comment]
Sorry, pianobar needs to be compiled with debugging support, i.e. *without* `-DNDEBUG`, so depending on the distribution you may have to build it yourself. (`make CFLAGS=-O2`)

**Comment by bkw777** [comment]
https://community.pandora.com/t5/Desktop/Can-t-Log-In-on-Pithos/m-p/68179#M5300

**Comment by bkw777** [comment]
Working again. Not just me, and not just pianobar.
