### ISSUE TITLE
station "mode" selection fails with "Error: Unknown"

### ISSUE THREAD

**Issue by netllama** [PromyLOPh/pianobar#715]
### Subject of the issue
I just upgraded to 2020-11-28 to use the new(ish) station "modes" feature.  However, when I try to set a mode, it always fails with "Error: unknown".

### Your environment
* version of pianobar: 2020-11-28
* your Linux distribution and release version: Fedora-33-x86_64
* ffmpeg/libav version and the flags it was compiled with (if you compiled yourself):
ffmpeg-4.3.2-2.fc33.x86_64
* your config file
```
user = WWW@gmail.com
password = XXX
act_stationaddbygenre = g
act_songinfo = i
act_songnext = n
act_quit = q
act_stationchange = s
```

### Steps to reproduce
```
[?] Delete [a]rtist seeds or [f]eedback? Manage [m]ode? m
(i) Fetching modes... Ok.
         0) My Station: The station experience you know and love. (active)
         1) Crowd Faves: You’ll hear the most Thumbed Up songs by other listeners.
         2) Discovery: You’ll hear more artists who don’t usually play on this station.
         3) Deep Cuts: You’ll hear less familiar songs from station artists.
         4) Artist Only: You’ll only hear songs from the station artist.
[?] Pick a new mode: 4
(i) Selecting mode "Artist Only"... Error: Unknown.
```

### Expected behaviour
Mode change should be saved

**Comment by netllama** [comment]
I've noticed that this only seems to reproduce with mode=4.  the other modes do work ok

**Comment by PromyLOPh** [comment]
*Artist Only* is only available for premium users. pianobar does not track whether you’re a subscriber or not and thus it’ll fail setting the new mode (there is no explanation from Pandora’s API when setting a mode fails, it simply does not change). I agree the error message could be more helpful though.
