### ISSUE TITLE
Pandora plays warning like: someone else is listening on your account right now, only one person can listen at a time

### ISSUE THREAD

**Issue by poetaman** [PromyLOPh/pianobar#719]
### Subject of the issue
Pandora plays warning like: someone else is listening on your account right now, only one person can listen at a time. This started happening after I killed a detached tmux session in which pianobar was playing music. I was trying out features of tmux, and ended up repeating this multiple times. At some point I started getting this warning that someone else is already listening to music from my account, and only one person can stream at a time...

### Your environment
* Latest at time of filing the report
* Apple M1 macOS 11.4 darwin arm
* ffmpeg/libav version and the flags it was compiled with (if you compiled yourself):
```
ffmpeg version 4.4 Copyright (c) 2000-2021 the FFmpeg developers
built with Apple clang version 12.0.5 (clang-1205.0.22.9)
configuration: --prefix=/opt/homebrew/Cellar/ffmpeg/4.4_2 --enable-shared --enable-pthreads --enable-version3 --cc=clang --host-cflags= --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libbluray --enable-libdav1d --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libspeex --enable-libsoxr --enable-libzmq --enable-libzimg --disable-libjack --disable-indev=jack --enable-avresample --enable-videotoolbox
libavutil      56. 70.100 / 56. 70.100
libavcodec     58.134.100 / 58.134.100
libavformat    58. 76.100 / 58. 76.100
libavdevice    58. 13.100 / 58. 13.100
libavfilter     7.110.100 /  7.110.100
libavresample   4.  0.  0 /  4.  0.  0
libswscale      5.  9.100 /  5.  9.100
libswresample   3.  9.100 /  3.  9.100
libpostproc    55.  9.100 / 55.  9.100
```
* your config file
```
user = someone@something.com
password_command = gpg --decrypt ~/.config/pianobar/reportaman_password
love_icon = ❤️
audio_quality = high
```
### Steps to reproduce
Open pianobar in a tmux session; detach and attach to another session; delete pianobar's session using tmux's ``<prefix>s`` to open session list, highlight Pianobar's session, press ``x`` followed by ``y``. Repeat the process multiple times...

### Expected behaviour
Detect the right terminal signal to logout maybe?

**Comment by PromyLOPh** [comment]
Is pianobar still running in the background after deleting the session?

**Comment by reportaman** [comment]
@PromyLOPh No it wasn't running. I also got an email from pandora today regarding multiple users...

It could be caused by this: https://github.com/tmux/tmux/issues/2778, but I am not very sure. Not sure what signal tmux sends on deleting a session. The warning was in the form of a voice that read the warning, it wasn't in text. It was played after relaunching pianobar, right before the first song began.

**Comment by PromyLOPh** [comment]
I logged in 100 times and still cannot reproduce this issue. No e-mail from Pandora either.

**Comment by reportaman** [comment]
@PromyLOPh Ok good to know, I'll wait for https://github.com/tmux/tmux/issues/2778 to be fixed, and see if the behavior repeats after that. Thanks!
