### ISSUE TITLE
Pianobar freezing after several songs

### ISSUE THREAD

**Issue by zoof** [PromyLOPh/pianobar#720]
### Subject of the issue
Pianobar freezing after several song

### Your environment
* 2020.11.28 from Debian repo
* Debian Bullseye
* your config file
```
user = user@example.com
password = ******
```

### Steps to reproduce
Start pianobar.

### Expected behaviour
Play songs until quit.

### Actual behaviour
Freezes after several songs.  Cannot quit out of pianobar.  ^Z and `kill %1` before I can restart.

I am a longtime user of pianobar and this is something that started happening this morning.  Maybe Pandora made some changes?

**Comment by zoof** [comment]
It finally seems to have happened again.  Maybe you can make something of the gdb output [here](https://controlc.com/1ad0b757).  If there are any auth tokens, I'm not sure what they are.  I used the script form at the bottom of the wiki page but I also have a manually started one if it would provide better information.

**Comment by PromyLOPh** [comment]
That log unfortunately does not have any backtraces for running threads. Could you try to apply the section “Already running programs” without step four and five when pianobar is stuck?

**Comment by zoof** [comment]
[Here](https://controlc.com/ee398889) you go.  Hopefully this one will have what you need.

**Comment by PromyLOPh** [comment]
Thread 2 looks like it’s waiting for some condition, but I can’t see where, because your `pianobar` executable does not have debug symbols. Usually I use `make CFLAGS="-ggdb -O0"`. Could you try that please?

**Comment by zoof** [comment]
I've recompiled it but I will have to wait for another bad day -- working fine today.

One thing which may or may not be apparent from the logs that I've supplied so far is that the freezing always happens at song transitions, I believe when a new song has been queued up but will confirm when the opportunity arises.

**Comment by zoof** [comment]
Finally!  I had to skip "(gdb) continue" because it was simply frozen and ctrl-c would not break out of it.  The output is [here](https://controlc.com/0209b46b).  Hopefully, this time there will be enough information for you.

**Comment by PromyLOPh** [comment]
Can you try using libao’s pulse backend directly instead of through alsa?

**Comment by zoof** [comment]
That seems to have done the trick.  Haven't had any freezes for several months now.
