### ISSUE TITLE
pianobar gives up immediately on certain Network errors

### ISSUE THREAD

**Issue by haarp** [PromyLOPh/pianobar#725]
### Subject of the issue
When pianobar encounters some Network errors, such as `Login... Network error: Failure when receiving data from the peer` or `Network error: SSL connect error`, it'll immediately give up, ignoring the `max_retry` value in the config. This is problematic when using public proxies as `control_proxy`, as these tend to be very unreliable but usually work eventually.

### Your environment
pianobar 2020.11.28 on Gentoo Linux
config: 
```
control_proxy = ...
max_retry = 30
```

### Steps to reproduce
- Have unreliable proxy set as `control_proxy`
- Start pianobar, see it fail on login

### Expected behaviour
Multiple retries

### Actual behaviour
No retry

Thanks a lot! :)

**Comment by PromyLOPh** [comment]
I looked at libcurl’s error codes and added those, which looked like temporary errors to a list of errors to retry. Does this work for you?
https://6xq.net/paste/pianobar-temperror.patch.html

**Comment by haarp** [comment]
This seems better in my testing so far, thanks! Some errors still instantly make it bail out tho, such as `Error: Invalid response.`. Funny what kind of network problems hese proxies can deliver...

**Comment by PromyLOPh** [comment]
That particular error is not coming from the network layer/curl though. Your proxy is most likely serving you something that is not coming from Pandora (i.e. not a proper JSON response). What else are you seeing?

**Comment by haarp** [comment]
> What else are you seeing?

I've been testing with that patch for a month now, and haven't seen any errors besides the `Invalid response` one.

**Comment by governor22** [comment]
@haarp   @PromyLOPh 
I just installed pianobar and get this error:

_(i) Login... Network error: Couldn't resolve proxy name_


I've looked at the pianobar config file and it shows:

**control_proxy = http://xxx.xxx.xxx.xxx:xx**


Do i need to change or delete this ?
thank you
