### ISSUE TITLE
Pianobar Network Error

### ISSUE THREAD

**Issue by Lvl4Sword** [PromyLOPh/pianobar#727]
### Subject of the issue
Briefly describe your issue here.
Today when I run pianobar I get the following and it fails login:
> Welcome to pianobar (2019.02.14)! Press ? for a list of commands.
> (i) Login... Network error: SSL peer certificate or SSH remote key was not OK

### Your environment
* version of pianobar
2019.02.14

* your Linux distribution and release version
Ubuntu 20.04 LTS

* ffmpeg/libav version and the flags it was compiled with (if you compiled yourself)
N/A

* your config file
> user = [REDACTED]
> password = [REDACTED]

### Steps to reproduce
Tell us how to reproduce this issue.
Run `pianobar`, receive the error

### Expected behaviour
Tell us what should happen.
Pianobar should login

### Actual behaviour
Tell us what happens instead, including a copy of all error messages.
Pianobar does not login

**Comment by tyleradams** [comment]
Also got this

**Comment by hobbes1069** [comment]
Seeing this with 2020.11.28.

**Comment by rjpcomputing** [comment]
I am also seeing this.

**Comment by rjpcomputing** [comment]
I tested it on 2 different versions and it is now working.
Has it started to work for others?

**Comment by tyleradams** [comment]
Works for me now
 Tyler

**Comment by Lvl4Sword** [comment]
LGTM

**Comment by hobbes1069** [comment]
Working for me now too...

**Comment by nick-ulle** [comment]
Seeing this again with 2024.12.21.

**Comment by axelson** [comment]
@nick-ulle I think that was Pandora letting their SSL certificates lapse. It is fixed now (for me at least)

**Comment by nick-ulle** [comment]
Working again for me as well. Thanks.
