### ISSUE TITLE
Feature request: --env for environment

### ISSUE THREAD

**Issue by tyleradams** [PromyLOPh/pianobar#728]
Can you add a --env flag which returns the environment info you need to debug pianobar?

**Comment by PromyLOPh** [comment]
What do you mean by “environment info”?

**Comment by tyleradams** [comment]
This part of the bug template
![image](https://user-images.githubusercontent.com/4683873/148076089-4c9e0698-d509-4aa3-be05-2a1d814cde48.png)

**Comment by PromyLOPh** [comment]
I feel the [template](https://github.com/PromyLOPh/pianobar/blob/master/.github/issue_template.md) doesn’t ask for information impossible to obtain without an `--env` flag, does it?

**Comment by tyleradams** [comment]
If it's automatable, why not automate it? More people will do it (people
are lazy) and there will be no mistakes and omissions.

 Tyler

**Comment by PromyLOPh** [comment]
I’m not aware of any mechanism to reliably determine the distribution. Also pianobar currently does not have an argument parser, so that’d have to be added too. I don’t see the value in adding this feature right now.

**Comment by minecraftchest1** [comment]
> I’m not aware of any mechanism to reliably determine the distribution. Also pianobar currently does not have an argument parser, so that’d have to be added too. I don’t see the value in adding this feature right now.

Take a look at https://www.man7.org/linux/man-pages/man5/os-release.5.html
