### ISSUE TITLE
Error: Access denied

### ISSUE THREAD

**Issue by ASoTNetworks** [PromyLOPh/pianobar#729]
### Subject of the issue
Getting Access denied errors sometimes when receiving new playlist.
`(i) Receiving new playlist... Error: Access denied. Try again later.`

### Your environment
* version of pianobar
  *  `2020.11.28-dev` and `2019.02.14` from repo
* your Linux distribution and release version
  * `Ubuntu 20.04`
* ffmpeg/libav version and the flags it was compiled with (if you compiled yourself)
  *  `4.2.4-1ubuntu0.1`
* your config file
  * defaults

### Steps to reproduce
Start the program and play sometimes it happens immediately or when trying to get new playlists in between.

### Expected behaviour
Should not have access denied.

### Actual behaviour
It will display the error and stops playing.
`(i) Receiving new playlist... Error: Access denied. Try again later.`

**Comment by PromyLOPh** [comment]
Is it still happening? Usually this is just a temporary issue when Pandora is doing maintenance.

**Comment by ASoTNetworks** [comment]
Yes it have been happening for a while now.

**Comment by PromyLOPh** [comment]
I’m not sure what I can do about that, since this is a server-side error.

**Comment by ASoTNetworks** [comment]
That explains why. I am also using the QuickMix station.

**Comment by PromyLOPh** [comment]
Interesting. I remember Pandora officially switched from providing a “QuickMix” to “Shuffle Stations” and the Android client for example explicitly requests shuffle stations via `includeShuffleInsteadOfQuickMix`. Can either of you @K37V1N or @ASoTNetworks successfully pick QuickMix stations using the `x` keybinding?

**Comment by K37V1N** [comment]
When I try using X to select quickmix stations then I get: /!\ Please select a QuickMix station first. 

My free premium trial for Pandora also just ran out, so I'm not sure if that has anything to do with it or not?

**Comment by PromyLOPh** [comment]
Actually, I’ve seen issues when the free trial runs out before. Years ago there was a notification API, which needed to be called before any station worked again. Can you run the web client once and then try again with pianobar?

**Comment by PromyLOPh** [comment]
That sounds indeed what I encountered with the notification API. I have an extremely old branch with some code to “dismiss” that, but no way of testing it unfortunately.
