### ISSUE TITLE
[feature request] Build-in proxy list

### ISSUE THREAD

**Issue by iAmInActions** [PromyLOPh/pianobar#732]
### Subject of the issue
I am outside the US and want to use pianobar. To get it running I made a small python script.

I have attached the script as an attachment. Its not very polished but its good enough for me for now. Would be cool to see something like this build into the program in the future though.

It depends on FreeProxy and pathlib. Its only Unix-compatible as i dont use any windows machines.

[pianobar4everyone.txt](https://github.com/PromyLOPh/pianobar/files/8750155/pianobar4everyone.txt) (its a .py but github doesnt allow those to be uploaded. rename it before running)

**Comment by PromyLOPh** [comment]
I’m not going to include any proxies or means to obtain them, because I cannot vouch for the proxies. Feel free to maintain the script externally. I’ll add a link to pianobar’s project page if you decide to polish it. Also base64 is not “for security”.
