### ISSUE TITLE
Cannot log in on VPN | Error: Invalid auth token.

### ISSUE THREAD

**Issue by jmelahman** [PromyLOPh/pianobar#733]
### Subject of the issue
Maybe only worth posting to help others troubleshoot, but it won't let me log in while connect to PrivateInternetAccess VPN. Effectively any backend call fails i.e. switching on the VPN after signing in hangs.

### Your environment
`pianobar-2022.04.01-1`

```
$ uname -a
Linux kyoko 5.19.2-arch1-1 #1 SMP PREEMPT_DYNAMIC Wed, 17 Aug 2022 13:48:51 +0000 x86_64 GNU/Linux

$ lsb_release -a
LSB Version:    n/a
Distributor ID: Arch
Description:    Arch Linux
Release:        rolling
Codename:       n/a
```

```
user = my_email
password = my_password
```

**Comment by PromyLOPh** [comment]
Does the website work through the VPN?

**Comment by jmelahman** [comment]
Yep. I am able to log out and log in through the webapp with the identical credentials with no issue. Also confirmed with Incognito enabled.

**Comment by PromyLOPh** [comment]
Have you tried the `bind_to` option? Maybe you have to tell pianobar explicitly to use your VPN interface? Apart from that I have no idea why it would tell you “invalid auth token” on login. You can try building with debug support and run `PIANOBAR_DEBUG=1 ./pianobar` – perhaps the raw response has more information, but I don’t expect it to.

**Comment by Erfboom** [comment]
Same issue here.

`Linux arch 6.0.9-arch1-1 #1 SMP PREEMPT_DYNAMIC Wed, 16 Nov 2022 17:01:17 +0000 x86_64 GNU/Linux`

`Welcome to pianobar (2022.04.01)! Press ? for a list of commands.`
`[?] Email:` 
`[?] Password:` 
`(i) Login... Error: Invalid auth token.`

Currently using a VPN. Am able to log into the web version just fine. Was using pianobar a couple hours ago using the same VPN at a different network. Changed locations, same VPN, pianobar gives this error.

**Comment by PromyLOPh** [comment]
Please see my comment above. Also make sure the *mobile* (Android/iOS) version works for you. The website uses a different API.

**Comment by jmelahman** [comment]
Just to circle back here, I tried using bind_to option to no success. I also tried compiling with debug mode -- not sure if I did it correctly because I didn't seen any debug messages.

Also, seems to be working as expected on my VPN set up now. i.e. not reproducible from my end.

If there's no reason to think this is client-side, I think closing this makes the most sense. Appreciate the help.

**Comment by governor22** [comment]
I'm also having the same error: Error: Invalid auth token.   

pianobar version 2022.04.01

did anyone figure it out ?
