### ISSUE TITLE
Minimalistic effort aimed to support service Pandora

### ISSUE THREAD

**Issue by Ricky-Tigg** [PromyLOPh/pianobar#734]
Hello. The presence of [instructions](https://github.com/PromyLOPh/pianobar/blob/master/INSTALL), while minimalistic and at best better than nothing, contributes, even weakly to support project Pandora. Though It might deserve a little better. As little as the presentation of installation methodologies dedicated for Debian and Red Hat systems alike. As it is in real world, installation attempts failed (for me) respectively in Ubuntu and Fedora. That's perhaps no surprise when required components are undocumented not to mention that the service is solely covering USA territory and won't be accessible from outside unless while relying on VPN service offering an IP address relayfor that territory. Pity.

**Comment by PromyLOPh** [comment]
What is your point?

**Comment by Ricky-Tigg** [comment]
All right then; closing accordingly.

**Comment by Ricky-Tigg** [comment]
All right then; closing accordingly.
