### ISSUE TITLE
Rename station not working

### ISSUE THREAD

**Issue by snakedoctr** [PromyLOPh/pianobar#736]
### Subject of the issue
`rename` functionality appears to be broken and returns a `Call not allowed` error.

### Your environment
* version of pianobar: 2020.11.28

### Steps to reproduce
Press `r` to rename the current station.
Enter a new name.

### Expected behaviour
The current station is renamed accordingly.

### Actual behaviour
> [?] New name: test
> (i) Renaming station... Error: Call not allowed.

**Comment by PromyLOPh** [comment]
Works fine with 2022.04.01 for me. Can you try that version please?
