### ISSUE TITLE
pianobar works with ffmpeg6  but old dependency still in MacPorts

### ISSUE THREAD

**Issue by Behinder** [PromyLOPh/pianobar#743]
I was able to compile pianobar by hand from Macports tree against ffmpeg6. Homebrew have no problem with dependency for v6 but Macports people still thinks base version is 4.4.3. 
I locally modified Portfile on `/opt/local/var/macports/sources/rsync.macports.org/macports/release/tarballs/ports/audio/pianobar` section
```
depends_lib                 port:curl \
                            path:lib/libavcodec.dylib:**ffmpeg6** \
                            port:libao \
                            port:libgcrypt \
                            port:json-c
```

In the Makefile perhaps `PREFIX:=/usr/local` should be changed but not sure to what. I was able to build from source directory `/opt/local/var/macports/sources/rsync.macports.org/macports/release/tarballs/ports/audio/pianobar/work/pianobar-2022.04.01`

by adding `export PKG_CONFIG_PATH=/opt/local/libexec/ffmpeg6/lib/pkgconfig/`  before `sudo gmake && sudo gmake install` because ffmpeg6 put the all required .pc files to reference libavformat libavaudiocodec etc there. 

But when I tried to install git from macports it wanted also to rebuild libpiano and pianobar because by itself they couldnt find referenced *.dylib files so I am sure you must change something in includes in `config.h` but I don't know what.

Anyway after compiling manually and installing pianobar works and I haven't encounter any issues so far.

**Comment by PromyLOPh** [comment]
I think you have to head over to the macports issue tracker and file your report there, since I’m not maintaining the Mac version.

**Comment by Behinder** [comment]
I posted here because you are the author and code is the same, so who uploading code to macports tree?

**Comment by PromyLOPh** [comment]
MacPorts contains a recipe that builds pianobar for this particular distribution. I don’t know who is maintaining it.
