### ISSUE TITLE
[Feature] output upcoming track to upcomingTrack text file

### ISSUE THREAD

**Issue by bonelifer** [PromyLOPh/pianobar#746]
Feature request for outputting upcoming track so that external 3rd party apps can access that information.

**Comment by PromyLOPh** [comment]
We’re kind of hitting the limits of the eventcmd “serialization format”, here, but the branch eventcmd-upcoming has a working implementation. Is that what you were looking for?

**Comment by bonelifer** [comment]
This request was facilitated by my patiobar feature request to be able to show the upcoming artist -title on the page.
https://github.com/kylejohnson/Patiobar/issues/43  I don't always want to go to another room just to look at the terminal. So this would be helpful there.

**Comment by PromyLOPh** [comment]
I merged the branch into master. Enjoy :)
