### ISSUE TITLE
Set a number of minutes to run pianobar (pianomin), or --minute flag

### ISSUE THREAD

**Issue by MichaelDimmitt** [PromyLOPh/pianobar#754]
### Subject of the issue
Wanted to reach out to see if you wanted this as a feature. 

I use pianomin everyday and I need it to shut off when I have a meeting approaching.
So when I turn on pianobar, I do so with a timeout so the music will stop when it is time for my meeting.

This is the code I currently put in my rc file that defaults to 20 minutes. However, if a number like 5 is given it will timeout when 5 minutes has past. 

```bash
function pianomin() {
    time=${1:-20};
    ask="timeout ${time}m pianobar; reset";
    echo $ask;
    eval $ask;
}
```

### Your environment
* Mac Sonoma 14.6.1 (23G93)

**Comment by Jeremyrobinson42** [comment]
That sounds very useful 👍

**Comment by PromyLOPh** [comment]
You could also do this via the remote control fifo: `sleep 5m && echo q > ~/.config/pianobar/ctl`. If you use `p` instead of `q` it will just pause pianobar.

**Comment by MichaelDimmitt** [comment]
Any interest in having a pr and what it would look like? Adding something as a flag or adding a readme. Happy to help.

**Comment by PromyLOPh** [comment]
I feel the eventcmd interface is more flexible and powerful than a command line flag and already supports your use-case well.
